### ISSUE TITLE
Request for 100% Save File

### ISSUE THREAD

**Issue by AcerUp** [Mr-Wiseguy/Zelda64Recomp#101]
Requesting a 100% save file (Preferably named "Link") for experimental and debugging purposes.

**Comment by FSR-1** [comment]
why specifically link

**Comment by AcerUp** [comment]
Thank you for the quick response. It does not have to be named Link, but I'm mainly searching for a generic 100% save file. Either way, it would be greatly appreciated. Oftentimes I search for bugs in completed save files to help report any issues I find.

**Comment by FSR-1** [comment]
i dont have all the people in the bombers note book il send you the link with it once iv found them and added them, everything else i believe is 100%

**Comment by FSR-1** [comment]
https://github.com/FSR-1/Zelda64Recompiled-100-save-file here it is tell me if theirs a part which isnt 100%

**Comment by AcerUp** [comment]
Thank you very much. I was not expecting this so soon, but it is much appreciated.

**Comment by AcerUp** [comment]
Save works well, thank you.
