### ISSUE TITLE
Where is the save file directory located?

### ISSUE THREAD

**Issue by anthonys211** [Mr-Wiseguy/Zelda64Recomp#102]
I would like to be able to move my saves between my PC and steamdeck but I cant seem to find where the game is storing my save file. Any insight would be appreciated.

**Comment by Marcelo20XX** [comment]
C:\Users\YourUserNameHere\AppData\Local\Zelda64Recompiled\saves

**Comment by FSR-1** [comment]
> C:\Users\YourUserNameHere\AppData\Local\Zelda64Recompiled\saves

thx

**Comment by udance4ever** [comment]
and for the macOS users out there: `~/Library/Application Support/Zelda64Recompiled/saves`
