### ISSUE TITLE
Linux save location

### ISSUE THREAD

**Issue by Teedler** [Mr-Wiseguy/Zelda64Recomp#106]
Trying to locate the save file for the linux version to sync between desktop and deck.

I'm aware that the windows save are located in C:\Users\YourUserNameHere\AppData\Local\Zelda64Recompiled\saves but I'm unable to track down the linux save.

Thank you.

**Comment by FSR-1** [comment]
have you found it yet im currently having trouble with a virtual machine so i cant help you find the save im guessing its probably in the home directory in your user folder

**Comment by vgmoose** [comment]
On linux, it's located in `~/.config/Zelda64Recompiled/saves` (hidden folder in the home folder)

**Comment by FSR-1** [comment]
> On linux, it's located in `~/.config/Zelda64Recompiled/saves` (hidden folder in the home folder)

thx i do know enough linux that ~ is your home folder if im right

**Comment by SpicyWheatPeppers** [comment]
Does anyone know the windows directory? 


found it C:\Users\USERNAME\AppData\Local\Zelda64Recompiled\saves

**Comment by FSR-1** [comment]
why do people want to know the save locations

**Comment by Reonu** [comment]
Thanks for the interest.

This is now answered in the FAQ section of the readme.

**Comment by yllekz** [comment]
Are we sure ``~/.config/Zelda64Recompiled/saves`` is the location? I just played for a while, saved, and there is no such directory. When I relaunched the game, it actually didn't even remember the save file.
