### ISSUE TITLE
[Request] Permission to package Zelda64Recomp for Flathub

### ISSUE THREAD

**Issue by FakeSalamander** [Mr-Wiseguy/Zelda64Recomp#107]
Hi! This project is absolutely wonderful, and I can't thank you enough for all the work you've put in to make it possible; the Linux binaries are especially appreciated  as well. 

I'd like to help make it easier for folks to access this tool: Would the be all-right if I packaged and uploaded it to Flathub? I'd happily hand over the fork to the project leads here if you ever wish so, of course.

**Comment by eaglewin64** [comment]
You will probably need to wait for building instructions

**Comment by Deozaan** [comment]
You can do whatever you want with it according to the limits of the license.

**Comment by Mr-Wiseguy** [comment]
As mentioned, redistribution falls within the limits of the GPL license as long as the terms of the license are followed. With that said, if you're able to get a Flatpak build made I would definitely appreciate a contribution back to this repo with the build setup for that so it can be upstreamed.

**Comment by Reonu** [comment]
Closing since the question has been answered, and a Flatpak version request is a duplicate of #44 .
