### ISSUE TITLE
[Feature Request] Add native support for N64 controllers

### ISSUE THREAD

**Issue by Cameron9635** [Mr-Wiseguy/Zelda64Recomp#109]
Tried hooking up my N64 controller with a USB adapter and it wouldn't work. This same setup works with other N64 emulators.

**Comment by rkroll17** [comment]
I have the same issue. C-Right is being detected as the escape button and I cannot assign it to C-Right in game.

**Comment by rkroll17** [comment]
Also duplicate of issue #41

**Comment by Mr-Wiseguy** [comment]
Closing as duplicate of #41 and because rebinding the menu button was added in 1.1.0.
