### ISSUE TITLE
Segmentation fault (core dumped) on Fedora

### ISSUE THREAD

**Issue by YO-SC** [Mr-Wiseguy/Zelda64Recomp#116]
Hello, I am trying to run the Linux executable on Fedora via the terminal, but I am getting the following error:

```
Segmentation fault (core dumped)
```

I also tried the Windows executable via several methods (like Steam/Proton, Bottles) to no avail 😢. The executable crashes when attempting to run it. 

Maybe I am being dumb idk. 

# System Details Report
---

## Report details
- **Date generated:**                              2024-05-12 22:51:30

## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. MS-7B51
- **Memory:**                                      64.0 GiB
- **Processor:**                                   Intel® Core™ i9-9900K × 16
- **Graphics:**                                    AMD Radeon™ RX 6700 XT
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            1.80
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.9-300.fc40.x86_64

**Comment by Fondant** [comment]
its a known issue on most distros as seen [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/28) and [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/71) and compiling it for different distros is [thorny](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/46) atm, but Mr-Wiseguy is aware of it and working on documentation and fixes

**Comment by YO-SC** [comment]
> its a known issue on most distros as seen [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/28) and [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/71) and compiling it for different distros is [thorny](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/46) atm, but Mr-Wiseguy is aware of it and working on documentation and fixes 

Oh I see, no problem. I wish them the best, this is a really cool project. I wish I had the technical capabilities to contribute somehow xD

I am not sure if to close the issue. In order to have it just for awareness to others. What do you think?

**Comment by Fondant** [comment]
up to you, just be back to close it later when it gets updated at the very least

**Comment by dwestford17** [comment]
I managed to get the linux version working through the Lutris flatpak. This was on Fedora Silverblue 40 btw, so that's something you can try if you wanna get it working.

**Comment by YO-SC** [comment]
> I managed to get the linux version working through the Lutris flatpak. This was on Fedora Silverblue 40 btw, so that's something you can try if you wanna get it working.

Holy moly it works. Thanks! I am going to close the issue since the problem was technically solved. I just wanna test it out. That said, I will have my eyes opened for a proper Flapak or AppImage in the future.

Thank you both @Fondant and @dwestford17 for your time.

**Comment by CharlieQLe** [comment]
Instead of using Lutris, at least on Wayland, try running it as `WAYLAND_DISPLAY="" ./Zelda64Recompiled`. That seems to work for me, at least on GNOME 46. That should force it to use XWayland.

**Comment by YO-SC** [comment]
> Instead of using Lutris, at least on Wayland, try running it as `WAYLAND_DISPLAY="" ./Zelda64Recompiled`. That seems to work for me, at least on GNOME 46. That should force it to use XWayland.

I can confirm this works too

**Comment by prurigro** [comment]
Additionally, if `SDL_VIDEODRIVER` and/or `GDK_BACKEND` has been set to wayland in your env you should start it with:

```
GDK_BACKEND=x11 SDL_VIDEODRIVER=x11 WAYLAND_DISPLAY="" ./Zelda64Recompiled
```
