### ISSUE TITLE
Delay before you start moving in the camera direction when Z-targeting

### ISSUE THREAD

**Issue by AQDuck97** [Mr-Wiseguy/Zelda64Recomp#125]
**Describe the bug**
If you try to move when Z-targeting (to quickly run a corner, etc.) there's a slight delay before the movement direction is affected, this has led to lots of jumping-off-edges on my part.
I can't remember if this is something that was in the original MM, but it does feel like a bug.

**To Reproduce**
1. Change Link's direction
2. Z-target to make the forward direction the direction Link is looking at
3. Quickly tell Link to move forward

**Expected behavior**
Movement direction should be paired with camera direction during Z-target animation (e.g camera is behind Link, forward is forward)

**Screenshots**
https://streamable.com/spcgya

Short clip, had to use keyboard for this as I had issues using remote play with my Steam Deck where I primarily play the game, in my experience it's much easier to replicate on controller but you can see in this clip that Link strafes for half a second or so even though the camera is right behind him and I press `W` (forward)

**Desktop (please complete the following information):**
 - OS: Arch Linux / SteamOS
 - Version: Linux Zen 6.8.9 
 - CPU: Ryzen 7 5800X
 - GPU: RX 580

**Additional context**

**Comment by Feli-Heli** [comment]
This is how the camera works normally in the game, not an issue with recomp.

**Comment by Reonu** [comment]
Thanks for the issue report, but this is how the game works originally, which means there is nothing to fix!

Closing issue.
