### ISSUE TITLE
game crashes after clicking start game

### ISSUE THREAD

**Issue by ToonBRlol** [Mr-Wiseguy/Zelda64Recomp#128]
**Describe the bug**
when i select my rom and click start game my MM crash

**To Reproduce**
1. select rom
2. click start game

**Expected behavior**
.

**Screenshots**
(my rom hashs)
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/127896421/f09264cc-448a-49f3-95b6-1395fc672615)

**Desktop (please complete the following information):**
 - OS: windows 10 home 22H2
 - Version: 1.0.0
 - CPU: intel Celeron N3450
 - GPU: Intel HD graphics (direct X12 & vulkan 1.3, updated drivers)

**Additional context**
I already tried changing the rom but it keeps crashing

**Comment by kpd328** [comment]
I don't know if the project expect little endian or big endian, but I tried with a little endian .n64 rom and it worked perfectly, so I'd try converting to little endian and see if that works for you.

**Comment by ToonBRlol** [comment]
Did not work

**Comment by Aravolt** [comment]
I'm having this issue as well. Any fix yet?

**Comment by auwsmit** [comment]
> Intel HD graphics

RT64 (the renderer that powers this project) probably doesn't work with Intel HD graphics. I could be wrong, but you probably just need a better GPU.

**Comment by Primis185** [comment]
I’m having the same issue

**Comment by ToonBRlol** [comment]
In the requirements it says that you need Vulkan 1.2 and DirectX12, and also that the minimum is an HD graphics 510. But as I have the requirements (DirectX12 and Vulkan 1.3) I think my GPU works and this is just a bug in the initial version

**Comment by ToonBRlol** [comment]
> I’m having the same issue


what is your gpu

**Comment by ToonBRlol** [comment]
> I’m having the same issue

what is your gpu?

**Comment by ToonBRlol** [comment]
> I'm having this issue as well. Any fix yet?

what is your gpu?

**Comment by Primis185** [comment]
Gtx 1650

**Comment by ToonBRlol** [comment]
> gtx 1060

see @auwsmit , It's probably an error in the initial version

**Comment by ToonBRlol** [comment]
the only way is to wait a new version that fix this issue

**Comment by auwsmit** [comment]
> the minimum is an HD graphics 510

ah, sorry I suck and didn't read the readme very thoroughly

> Gtx 1650

tried updating the graphics driver? I had a similar issue crashing at startup until I updated the driver

**Comment by Primis185** [comment]
I’ll try it after work thanks for the suggestion, I always forget about that

**Comment by Aravolt** [comment]
> > I'm having this issue as well. Any fix yet?
> 
> what is your gpu?

I have an RX 5500 XT

**Comment by JustinBrow** [comment]
@ToonBRlol 
># System Requirements  
>A CPU supporting the AVX instruction set is also required  

Intel Celeron N3450 does not support AVX Extension. Might be why you are crashing.
https://en.wikipedia.org/wiki/Goldmont

**Comment by Breakingnorms** [comment]
> @ToonBRlol
> 
> > # System Requirements
> > A CPU supporting the AVX instruction set is also required
> 
> Intel Celeron N3450 does not support AVX Extension. Might be why you are crashing. https://en.wikipedia.org/wiki/Goldmont

maybe, but the problem persist in a pc with different requierements looks like https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/117#issue-2291884815

The question is, what do they have in common to have the same problem?

**Comment by Aravolt** [comment]
it appears our pc's don't have anything in common, at least that I can find

**Comment by Deozaan** [comment]
> **Screenshots**
> (my rom hashs)

Slightly off-topic, but what is this screenshot from? What program are you using to calculate the hash and show that info?

**Comment by auwsmit** [comment]
> Slightly off-topic, but what is this screenshot from? What program are you using to calculate the hash and show that info?

ROM Hasher

**Comment by ToonBRlol** [comment]
sooo... Has anyone found a way to fix it?

**Comment by ToonBRlol** [comment]
> @ToonBRlol
> 
> > # System Requirements
> > A CPU supporting the AVX instruction set is also required
> 
> Intel Celeron N3450 does not support AVX Extension. Might be why you are crashing. https://en.wikipedia.org/wiki/Goldmont

I didn't find anything about this avx in the wikis for the Intel HD graphics 500 or the Celeron N3450. maybe that's it

**Comment by Zelda04** [comment]
> > @ToonBRlol
> > > # System Requirements
> > > A CPU supporting the AVX instruction set is also required
> > 
> > 
> > Intel Celeron N3450 does not support AVX Extension. Might be why you are crashing. https://en.wikipedia.org/wiki/Goldmont
> 
> I didn't find anything about this avx in the wikis for the Intel HD graphics 500 or the Celeron N3450. maybe that's it

I have the same issue in Intel Hd graphics 520, but i have the extension AVX, you can check it with HWinfo app

**Comment by Aravolt** [comment]
I found what my issue was. I was running an insider version of Windows. I reinstalled windows and didn't join the insider program and now it works.

**Comment by PTRosa** [comment]
I have an intel HD 520, with Vulkan 1.3 and direct 3d 12, still, i am having this issue too. I tried everything, even checked the Windows insider program thing (i haven't joined). So if anyone with a similar setup finds out how to solve this, please comment your solution so i can try too.

**Comment by ToonBRlol** [comment]
Apparently it's not the AVX

**Comment by Zelda04** [comment]
> I have an intel HD 520, with Vulkan 1.3 and direct 3d 12, still, i am having this issue too. I tried everything, even checked the Windows insider program thing (i haven't joined). So if anyone with a similar setup finds out how to solve this, please comment your solution so i can try too.

I have this exactly setup, and nothing works to run the game, but the port based on decompilation works fine for me

**Comment by PTRosa** [comment]
> > I have an intel HD 520, with Vulkan 1.3 and direct 3d 12, still, i am having this issue too. I tried everything, even checked the Windows insider program thing (i haven't joined). So if anyone with a similar setup finds out how to solve this, please comment your solution so i can try too.
> 
> I have this exactly setup, and nothing works to run the game, but the port based on decompilation works fine for me

Same here lol. Fortunately, the ship of harkinian port came out on the day i posted the comment, and it worked superfine too. Talk about luck lol.

**Comment by ToonBRlol** [comment]
I updated to version 1.1.1 and it keeps giving this error...

**Comment by Mr-Wiseguy** [comment]
This is due to a lack of AVX support. [Wikichip](https://en.wikichip.org/wiki/intel/celeron/n3450) shows that this CPU only has SSE4.2 and is missing AVX, which is a requirement as stated in the readme.
