### ISSUE TITLE
[Question] I have a fork and I I don't know how to build

### ISSUE THREAD

**Issue by TheTrueShadow** [Mr-Wiseguy/Zelda64Recomp#132]
I have a fork of this and I I don't know how to build my own to test the code that I have changed 

Any help is appreciated in this 

(The code I have have changed so far is autosave features)

**Comment by Fondant** [comment]
on windows?

**Comment by TheTrueShadow** [comment]
Yes

**Comment by Fondant** [comment]
i cant overly give advice on this but for the linux side of things, over here on issue https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/46 we have been trying to build the game just to play on other linux distros.
look into running CMake via Visual studio or terminal

**Comment by TheTrueShadow** [comment]
Alright I will try on windows too

**Comment by Fondant** [comment]
it will probably fail though as we are unsure of exactly how the project needs to be set up (as in the issue) to build correctly. though i do not know if that is the case on windows, would love to hear back about what happens :+1:

**Comment by TheTrueShadow** [comment]
Alright I will let you know how it goes

**Comment by Reonu** [comment]
Thank you for your interest in building!

Wiseguy is working on build instructions. They will be ready soon.

**Comment by Mr-Wiseguy** [comment]
Build instructions are now available here: https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/dev/BUILDING.md.
