### ISSUE TITLE
[Bug] SDL Audio Subsytem not Initialized

### ISSUE THREAD

**Issue by elvircrn** [Mr-Wiseguy/Zelda64Recomp#138]
**Describe the bug**
After downloading the linux version and running the binary, I get the following error:
`
SDL error opening audio device: Audio subsystem is not initialized
`
**To Reproduce**
1. Download the latest linux build
2. Extract the zip
3. Run the executable
4. Observe the error in the terminal.

**Expected behavior**
The software should run.

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/5296734/ebb4968a-5db2-450c-b167-ae519647ce81)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 24.10
 - CPU: Ryzen 3900X
 - GPU:RTX 3060 12Gb

**Comment by dcvz** [comment]
@elvircrn do you get the same issue if you run via the AppImage here?

https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9215322540

**Comment by elvircrn** [comment]
When I use the AppImage, the game loads just fine.

Thanks!

**Comment by dcvz** [comment]
Glad to hear that! We'll be distributing the AppImage as well in future releases.
