### ISSUE TITLE
[Feature Request] Native macOS Build 

### ISSUE THREAD

**Issue by AarnavSin** [Mr-Wiseguy/Zelda64Recomp#141]
I think a native macOS build would be great for a project like this! Lots of Mac players would wanna play this iteration.

**Comment by zroes** [comment]
I was going to make the same request. The Windows version doesn't appear to work in Parallels, and I was hoping a Mac version was in the works.

**Comment by DarioSamo** [comment]
The biggest hurdle to a Mac port is the [lack of a Metal backend on RT64](https://github.com/rt64/rt64/issues/6#issuecomment-2106382071) as I don't have the hardware to develop one myself. However, a few people are already attempting to implement one so you can follow the progress there.

**Comment by Reonu** [comment]
Closing as duplicate of #66
