### ISSUE TITLE
(Request) Texture Upscaling 

### ISSUE THREAD

**Issue by FoxbitDreamtail** [Mr-Wiseguy/Zelda64Recomp#142]
Would it be theoretically possible to use upscaling like seen in 2D emulators to allow for upscaled textures? I'm not asking for the models to be upscaled just the textures, model upscaling is something that can only be done in blender and it would require a lot of additional work to be added.

**Comment by gumbyscout** [comment]
You can probably just wait until texture packs are supported, as there is a complete hand painted hd texture pack by Nerrel (and I learned of this project through Nerrel's video).

**Comment by DarioSamo** [comment]
This is out of scope of the renderer and will be left to be achieved through texture packs if someone desires it.

**Comment by Reonu** [comment]
Closing as not planned.
