### ISSUE TITLE
[Feature Request] Nearest neighbor texture filtering

### ISSUE THREAD

**Issue by emeraldroguefan** [Mr-Wiseguy/Zelda64Recomp#147]
![Screenshot 2024-05-14 17-03-56](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/55709254/87ebec08-0748-44fc-8cc7-81402456985b)

Screenshot is from Dolphin, but I think most N64 games greatly benefit from nearest neighbor texture filtering (Pokemon Snap being another great example)

Love the Zelda64Recomp a lot & hope to see this grow even bigger

**Comment by Reonu** [comment]
Thank you for the suggestion!

However, this is outside of the scope of the project and seems better suited to be made as a mod instead when mod support is released.
