### ISSUE TITLE
Auto save resets dungeon collectibles (stray fairies)

### ISSUE THREAD

**Issue by Rob-McCor** [Mr-Wiseguy/Zelda64Recomp#151]
**Describe the bug**
If you have autosaved in a dungeon and have collected stray fairies, keys etc and reset the game. The dungeon resets and stray fairies, locked doors, keys respawn but Links inventory retains what has been collected meaning you can basically get infinite stray fairies and keys in any dungeon if you reset the game after an autosave.

**To Reproduce**
1. Go to any dungeon. This happened to me in snowhead temple.
2. Collect an easy to get stray fairy or a small key chest
3. Wait for an autosave
4. After auto saving reset the game 
5. Return to the stray fairy location or small key chest.
6. Stray fairy/small key should have respawned

**Expected behavior**
After an auto save and I reset my game I expect my progress through the dungeon to be retained.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Linux, Steam Deck]
 - Version: [e.g. 1.0.0]
 - CPU: [AMD Zen 2]
 - GPU: [AMD RDNA2]

**Additional context**
N/A

**Comment by Fondant** [comment]
did it reset stray fairies completely (setting your in-game fairy count to 0) or does it just reset the ones you have already collected without changing your fairy count (allowing you to get more then 15)?

**Comment by Rob-McCor** [comment]
It resets the ones I have already collected without changing my counter. I had 11 stray fairies before I rebooted my game and I still had 11 when I was back in game. Also I am able to get more than 15 I had 16/15 stray fairies when I finished snowhead.

**Comment by Fondant** [comment]
fair enough, looks like there is more then just chests with this one though, as this may be a duplicate issue a la issue https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/59

**Comment by Mr-Wiseguy** [comment]
This is fixed in version [1.0.1](https://github.com/Mr-Wiseguy/Zelda64Recomp/releases/tag/v1.0.1).
