### ISSUE TITLE
[Feature Request] add sliders for FX volume and master volume to audio settings

### ISSUE THREAD

**Issue by Bordraw** [Mr-Wiseguy/Zelda64Recomp#155]
It's slightly strange that the only slider we can control is for the background music, and this would be a nice setting to have for gaming while listening to a video/podcast

**Comment by Calinou** [comment]
To control master volume, you can use your system's audio mixer options which should have controls for per-app volume on both Windows and Linux. (You need third-party apps for this on macOS though.)

It still makes sense to have a built-in option (particularly if macOS support is added later on), but this can suffice for now.

**Comment by Reonu** [comment]
Now being tracked in #207, PRs welcome.
