### ISSUE TITLE
[Feature request] Support for patched ROMs (from Patcher64+)

### ISSUE THREAD

**Issue by meegsmusic** [Mr-Wiseguy/Zelda64Recomp#157]
**Is your feature request related to a problem? Please describe.**
No - not exactly, it's a request related to supporting patched ROMs (more below).

**Describe the solution you'd like**
The ability for the system to support patched ROMs from Patcher64+, as currently, when attempting to run a patched version of the game (set to NTSC-U, US), the following error appears:
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/37029756/eeeaa5fa-c64c-4de6-98c1-670ab6e930db)

**Describe alternatives you've considered**
Using emulators to run the patched ROM, but the game runs SO well on this system (thank you!).

**Additional context**
See information on Patcher64+ here, where you can patch N64 ROMs (in particular, Majora's Mask and Ocarina of Time): [https://github.com/Admentus64/Patcher64Plus-Tool](https://github.com/Admentus64/Patcher64Plus-Tool)

--

Thank you in advance :) ! This system runs SO well, I think this would just be a cherry on top haha.

**Comment by meegsmusic** [comment]
Oop! Just saw this in the "Planned Features" section of the main page:
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/37029756/2894f828-ca88-4ef3-a59c-3be6dcb01bd3)

^^ This is nice, not sure if it's still worth keeping this open since I think those planned features opens options to what I'm looking for :)

**Comment by Shivaan88k** [comment]
I'm hoping that all these PC port projects (this, the ship one, and the new perfect dark one, mainly) will eventually be able to use source files for mods, and enable us to add multiple non-overhaul mods at once. We'll see.

**Comment by Mr-Wiseguy** [comment]
> I'm hoping that all these PC port projects (this, the ship one, and the new perfect dark one, mainly) will eventually be able to use source files for mods, and enable us to add multiple non-overhaul mods at once. We'll see.

Yup, that's the plan here. No ETA currently on when it'll be done, but mods will be built similarly to how the included patches work (check out the `patches` folder) and then will be able to be installed and toggled while in the launcher. I'll have more details about it written up as modding gets closer to release.

**Comment by meegsmusic** [comment]
> > I'm hoping that all these PC port projects (this, the ship one, and the new perfect dark one, mainly) will eventually be able to use source files for mods, and enable us to add multiple non-overhaul mods at once. We'll see.
> 
> Yup, that's the plan here. No ETA currently on when it'll be done, but mods will be built similarly to how the included patches work (check out the `patches` folder) and then will be able to be installed and toggled while in the launcher. I'll have more details about it written up as modding gets closer to release.

I appreciate all your work! I'll close this since there's already plans for this. Thank you!!!
