### ISSUE TITLE
Winodws update = game will not launch

### ISSUE THREAD

**Issue by McBeefy34** [Mr-Wiseguy/Zelda64Recomp#169]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
Updated a windows security patch 5/15/2024 and now the app will not open. Graphics drivers are up to date

**To Reproduce**
1. update windows to 5/15/2024 windows update
2. restart computer
3. launch game

**Expected behavior**
Application should launch but does not.

**Screenshots**
Please attach a screenshot of the bug.

**Desktop (please complete the following information):**
 - Windows 11
 - Version: 1.0.0
 - CPU: Ryzen 7 5700x
 - GPU: NVIDIA GeForce RTX 3060 8GB

**Additional context**

**Comment by Fondant** [comment]
1) are your divers up to date?
2) anything beyond it just does not start? does it open then close? never show any window?
thanks for your time

**Comment by McBeefy34** [comment]
My drivers are up to date.
Nothing else it waits for the app to open but then dies before opening any
windows.

**Comment by McBeefy34** [comment]
I also uninstalled and reinstalled the graphics driver to make sure.

**Comment by Skedog** [comment]
Had a similar issue where it stopped launching, and for me the issue ended up being related to my default audio device. For some reason the Z64 Recomp will only launch if my default audio device is selected as one of the USB audio devices I have available, and it will *not* launch if my default device is set to the 3.5mm jacks on my mobo.

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. Error messages for common problems were added in the new 1.0.1 release, do you get one on startup with that version?

**Comment by Skedog** [comment]
@Mr-Wiseguy I just downloaded to check it out, and no, still nothing if my audio device is set to "default". I try opening the game, and then it does basically nothing. If you watch task manager you can see it open for half a second and then it instantly closes.

Is there a place/way that I can get log files for you to help out?

**Comment by McBeefy34** [comment]
I've been looking into a way to pull a log file, but the background process
did open and close immediately. I also did not get an error message when i
tried opening version 1.0.1.

**Comment by LO0K0UT** [comment]
> Had a similar issue where it stopped launching, and for me the issue ended up being related to my default audio device. For some reason the Z64 Recomp will only launch if my default audio device is selected as one of the USB audio devices I have available, and it will _not_ launch if my default device is set to the 3.5mm jacks on my mobo.

This worked for me. I am running on a machine with no audio device and it wouldn't launch. Connected a bluetooth speaker just to have some audio output device and it launched for the first time.

**Comment by moeiscool** [comment]
figured it out for mine. I'm on Asus ROG Ally and could not change audio between anything other than Stream Speakers, it did not work.

This is how i got mine to work : delete all the json files here `%LOCALAPPDATA%\Zelda64Recompiled`

- controls.json
- graphics.json
- sound.json
- general.json

**Comment by Mr-Wiseguy** [comment]
Any luck with this on 1.1.1? The issue that @moeiscool had with needing to delete the json files was fixed in that version, so if your issue was the same then yours should be fixed as well.

**Comment by McBeefy34** [comment]
Yes, deleting the JSON file worked. I'll try 1.1.1

**Comment by Skedog** [comment]
@Mr-Wiseguy version 1.1.1 does indeed launch now with my "default" audio settings!

**Comment by McBeefy34** [comment]
Version 1.1.1 works now for me!!! Thank you!

**Comment by Mr-Wiseguy** [comment]
Thanks for the confirmation that it's been fixed, closing this issue now.
