### ISSUE TITLE
Noncollectable Stray Fairy 

### ISSUE THREAD

**Issue by thomas992** [Mr-Wiseguy/Zelda64Recomp#174]
I have 14/15 stray fairies in Great Bay Temple and I have triple verified that I have every fairy, VERY FRUSTRATING. Spending an entire 3 hour cycle not being able to do what I actually did. I went through and checked EVERY location TWICE. The first time I did the dungeon I didn't collect the fairies, I think that's what caused the bug. I am very annoyed I was going for a hundred percent run and now the game just feels broken I need a cheat engine or something.

**Comment by thomas992** [comment]
Where is the save file located can I just edit it??? I could upload my save to be verified too

**Comment by ShinyHobo** [comment]
https://github.com/Mr-Wiseguy/Zelda64Recomp?tab=readme-ov-file#where-is-the-savefile-stored

**Comment by thomas992** [comment]
https://file.io/v27XXYfAby4N

I am using Linux (Zorin OS) if that matters. I can not find a save editor. I heard of someone called HatCat that made a save editor but I can't find it. I found https://github.com/zeldaret/mm/blob/fd3431fa486543ea8ced10b946a4e41d49698d10/include/z64save.h#L2

but I do not understand how to use the values to edit the save file.

**Comment by FSR-1** [comment]
why didn't you just get all the fairies the first time

**Comment by Mr-Wiseguy** [comment]
I downloaded your save file to check and it seems like you missed this stray fairy in the pot at the bottom of the central room.
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/68165316/3a0ab1dd-e5f9-4816-867e-662f58b8d11e)

**Comment by thomas992** [comment]
I swear to god I hit that thing like 5 times I still consider it a bug

**Comment by FSR-1** [comment]
lol
