### ISSUE TITLE
Unable to open Gauntlet Legends instead of Majoras Mask

### ISSUE THREAD

**Issue by MoxieSwaygan** [Mr-Wiseguy/Zelda64Recomp#176]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**

I keep trying to import Gauntlet Legends and the program won't let me.

**Comment by Reonu** [comment]
Hello. This project is specifically to play Majora's Mask (and OoT in the future).
