### ISSUE TITLE
Adjustable deadzone for stick

### ISSUE THREAD

**Issue by rock-x-00** [Mr-Wiseguy/Zelda64Recomp#177]
My controller has a slight drift but ingame it's like Im moving the stick a lot.

I wonder if It's possible to add an adjustment for the stick deadzone

**Comment by FSR-1** [comment]
already a planned feature

**Comment by Mandras2** [comment]
For all those poor souls out there using a DualSense or PS4 controller with stick drift or too sensitive joysticks...

**Install HidHide:** 
follow the instructions and hide your physical controller (Zelda64Recomp seems to natively support Playstation controllers, which interferes with input remappers like DS4Windows).
**Use DS4Windows**
set up an emulated device profile (I use xbox360) and set custom deadzones on each stick to counteract drift.

**Comment by Reonu** [comment]
Duplicate of #110
