### ISSUE TITLE
Dualsense input dropped

### ISSUE THREAD

**Issue by srjghseruikg** [Mr-Wiseguy/Zelda64Recomp#179]
Randomly after a couple hours of normal gameplay, my Dualsense controller's input was completely dropped. 

**To Reproduce**
1. Play the game??
2. ???

**Expected behavior**
All i can say is, i played the game fine over a wired USB connection all the way to the end of snowhead temple, midway through the boss my controller stopped responding, it seemed the last buttons i pressed were held indefinitely until i took control with the keyboard.
The controller was working fine in other games which i launched while the game was paused, control panel showed all buttons and analog functioning fine.
Also tried another controller while i was at it, dualshock 4, with the ds4windows wrapper, that wasn't picked up whatsoever.

**Desktop (please complete the following information):**
Operating System: Windows 10 IoT Enterprise LTSC 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: Micro-Star International Co., Ltd.
             System Model: MS-7C56
                     BIOS: 1.91 (type: UEFI)
                Processor: AMD Ryzen 5 5600X 6-Core Processor              (12 CPUs), ~3.7GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32694MB RAM
                Page File: 15100MB used, 33377MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
Dualsense Model number if relevant: CFI-ZCT1W
**Additional context**
I don't use a wrapper for the dualsense, the game's launched through steam and steaminput isn't doing anything to the game either.
Relaunching the game it seems the controller works fine, so it's definitely a bug with this recomp.

-I want it noted on my epitaph that i forgot to f*cking turn in the stray fairies, so this bug just completely annihilated the time i spent on that temple. Gonna go cry in a corner for this is the 2nd time i've been cheated out of snowhead temple this past 3 years. :) long story.

**Comment by Fondant** [comment]
like are we talking a hard wired dualsense controller or a wireless dualsense controller with a wired connection?

**Comment by srjghseruikg** [comment]
> like are we talking a hard wired dualsense controller or a wireless dualsense controller with a wired connection?

they make that? Its just a normal dualsense connected to USB-C. CFI-ZCT1W

**Comment by Fondant** [comment]
knowing 3rd party makers, probably. though i should have been able to tell from the controllers m#. anyway, i would not be supprized if the cable was moved far enough out of the controller to disconnect and produce the effect here. but lets go thru this, beyond the wrapper not being supported (which probably is something that might get worked on in the future, i imagine) you were saying that the controller dropped inputs. did you attemped to reconnect the controller after it dropped inputs?

**Comment by Mr-Wiseguy** [comment]
I did most of my playtesting with a Dualsense and never encountered this issue.
> I don't use a wrapper for the dualsense, the game's launched through steam

Steam is acting as a wrapper in that case, it automatically translates controllers to an xbox controller interface which isn't needed for recomp. Recomp is able to handle controller disconnects and reconnects without an issue at runtime, so I do think this was an issue on Steam's end. I would suggest not launching recomp through Steam if you had issues like this.
> Also tried another controller while i was at it, dualshock 4, with the ds4windows wrapper, that wasn't picked up whatsoever.

Again, as the readme states there's no need to use wrappers. You can use a dualshock 4 directly with recomp, and wrappers generally tend to cause issues.

Closing as this is most certainly not an issue on recomp's side.
