### ISSUE TITLE
Controller Support - Input Issues

### ISSUE THREAD

**Issue by SomeRandoPeep** [Mr-Wiseguy/Zelda64Recomp#187]
**Describe the bug**
When playing with a Nintendo Switch Pro Controller the up input on the left stick
switches to the first person view despite that being mapped to up on the
right stick by default.

**To Reproduce**
I am unaware if this can be reproduced on other hardware.

**Expected behavior**
I just expected to be able to move up with the left stick without
it making the perspective change.

**Screenshots**
![First Person Input Glitch](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/170202658/f0ce4d78-788e-4993-a3ac-f0bb9f191b0d)

**Desktop Info:**
 - OS: Windows 11
 - Version: 10.0.22631 Build 22631
 - CPU:  AMD Ryzen 7 3750H
 - GPU: Nvidia GTX 1650

**Additional context**
I am using the controller through Bluetooth.
I had a fresh install of the recompilation.

**Comment by sfried8** [comment]
Do you have Steam open? It might be interfering with your inputs. Try closing Steam

**Comment by SomeRandoPeep** [comment]
I did have steam open when playing the game. I'll try it again when I close steam.

**Comment by Reonu** [comment]
Closing since it was presumably Steam causing the issue.
