### ISSUE TITLE
Swamp shooting gallery soft lock and not enough targets

### ISSUE THREAD

**Issue by PhantomLiberty** [Mr-Wiseguy/Zelda64Recomp#188]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug:**
Completing the swamp shooting gallery leads you to a "reward". But it sucks you back into the minigame instead with no way to quit. It also stops spawning enemies around the 40 second mark, leaving you with not enough points to win the grand prize according to the man at the counter.

**To Reproduce:**
Play and complete the swamp shooting gallery

**Expected behavior:**
You should not get locked into the minigame and there should be enough targets.

**Desktop:**
 - OS: Windows 11 23H2 Build 22631.3593
 - Version: 1.0.0
 - CPU: Intel i9 9900k
 - GPU: NVIDIA GeForce RTX 2080 Ti

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. Many people, including myself, have completed the swamp shooting gallery without an issue so this is strange to hear. Would it be possible for you to record a video showing what happens for you?

**Comment by PhantomLiberty** [comment]
Welp, I feel like a dumb ass. At the end I hadn't noticed the deku in the very top left which you are required to kill. Not killing it just looped the minigame how I described, making it seem like a bug or something.. haha.
