### ISSUE TITLE
Update instructions for building zelda decomp on Linux [BUILDING.md]

### ISSUE THREAD

**Issue by yamzee** [Mr-Wiseguy/Zelda64Recomp#189]
Apologies for not making a PR, but my English isn't the best and wouldn't know where to toss this in...

The instructions are missing two steps in Step 3:
1) Make the binaries in `tools/ido_recomp/linux/{5.3,7.1}/` executable, `make init` will fail otherwise.
2) Go into `tools/fado` and `make`  

After doing the two steps above (and the other existing instructions) it builds perfectly fine.

**Comment by Mr-Wiseguy** [comment]
The decomp's `make init` command calls the `setup` target, which in turn calls the tools/ Makefile which builds fado. Did you download the repo as a zip? That will remove file permissions, which would explain why ido wasn't marked as executable.

**Comment by Mr-Wiseguy** [comment]
Closing due to lack of response and because the instructions have been tested many times on Linux, and because those instructions belong to the decompilation project and not recomp.
