### ISSUE TITLE
[Feature request] Better sound settings

### ISSUE THREAD

**Issue by Lucaspec72** [Mr-Wiseguy/Zelda64Recomp#191]
Currently, you can set the background music volume, and enable/disable the low health alert sound.

Personally wouldn't have a need for it, but just for the sake of being comprehensive, i'd be nice to also have a slider for the sound effects.

Another thing I think would be nice would be checkbox options to disable sound/music altogether. I can cut music by putting it at 0%, but since i have to keep mashing the dpad or joystick a 100 times each time i want to do so, it gets annoying. a On/Off option would be nice. (that, or make the slider continue to change when holding left or right. [Opened another feature request for this](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/192#issue-2304356807) )

**Comment by Reonu** [comment]
Now being tracked in #207, PRs welcome.
