### ISSUE TITLE
"Dawn of the X Day" screens end too quickly

### ISSUE THREAD

**Issue by Bordraw** [Mr-Wiseguy/Zelda64Recomp#198]
**Describe the bug**
The black "Dawn of the First/Second/Final Day" transition screen disappears before its audio clip plays fully, and much faster than it did on the N64, presumably due to reduced load times.

**To Reproduce**
1. play the song of time and wait for the black screen to appear

**Expected behavior**
"Dawn of the first day, 72 hours remain" appears with a brief pause, with a dramatic clang and some birds chirping.

**Actual behavior**
The screen appears, but it doesn't linger long enough and the sound clip is cut off.

**Desktop**
 - OS: Windows 11
 - Version: 1.0.0
 - CPU: AMD Ryzen 9 5900HS
 - GPU: NVIDIA GeForce 3070

**Additional context**
This is probably a similar problem to the classic 4 giants cutscene timing issue where the limitations of the N64 hardware created the delay. I think it makes sense to manually apply a delay here to preserve the dramatic effect of the black screens.

**Comment by Reonu** [comment]
Fixed by #266
