### ISSUE TITLE
Rom Hack Support(Request)

### ISSUE THREAD

**Issue by Chen2Win** [Mr-Wiseguy/Zelda64Recomp#204]
Not a bug just a recommendation that's probably overlooked, in the future maybe add something to toggle roms, I tried installing the files twice in hopes of using a regular and a rom hack file but once you select the file it's stuck on it

**Comment by Mr-Wiseguy** [comment]
It's not stuck, you can only use the exact ROM it accepts. Recomp isn't an emulator, so it doesn't accept any ROM you throw at it.
