### ISSUE TITLE
[Feature] Camera axis inversion options

### ISSUE THREAD

**Issue by Reonu** [Mr-Wiseguy/Zelda64Recomp#206]
**Issue**

It is currently not possible to invert the axis of the camera when aiming or when looking in first person. This is necessary so everyone can play comfortably.

**Requirements**
- Add new toggles to the Controls menu to invert the first person X and Y axis. **The defaults should be vanilla and named correctly**, in other words, Y should default to inverted and X should default to non-inverted (do not consider the default Y axis behavior to be "non-inverted" just because it's the default)
- Ensure the toggle works in all instances of first person aiming (bow, hookshot, C-up, etc)
- This should not affect gyro. Gyro is never inverted.

**Comment by Deadstarrr** [comment]
I'd love to see this as well.

**Comment by Reonu** [comment]
> I'd love to see this as well.

Hi, this is already implemented in the latest update which released today, I just forgot to close the issue.

Fixed by #264
