### ISSUE TITLE
ARM64 Linux Build errors

### ISSUE THREAD

**Issue by theofficialgman** [Mr-Wiseguy/Zelda64Recomp#208]
One such error during compilation of Zelda64Recomp

```
[17041/17436] Building CXX object rt64/CMakeFiles/rt64.dir/src/hle/rt64_application_window.cpp.o
FAILED: rt64/CMakeFiles/rt64.dir/src/hle/rt64_application_window.cpp.o 
/usr/bin/clang++-15 -DFFX_GCC -DHLSL_CPU -DIMGUI_IMPL_VULKAN_NO_PROTOTYPES -I/home/gman/Zelda64Recomp/lib/rt64/src -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/D3D12MemoryAllocator/include -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/D3D12MemoryAllocator/src -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/imgui -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/hlslpp/include -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/dxc/inc -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/Vulkan-Headers/include -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/VulkanMemoryAllocator/include -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/mupen64plus-core/src/api -I/home/gman/Zelda64Recomp/lib/rt64/src/contrib/nativefiledialog-extended/src/include -I/home/gman/Zelda64Recomp/cmake-build/src -I/home/gman/Zelda64Recomp/cmake-build/rt64/src -isystem /usr/include/SDL2 -Wno-everything -Wall -Wextra -O3 -DNDEBUG -std=c++17 -fvisibility=hidden -Wno-nullability-completeness -MD -MT rt64/CMakeFiles/rt64.dir/src/hle/rt64_application_window.cpp.o -MF rt64/CMakeFiles/rt64.dir/src/hle/rt64_application_window.cpp.o.d -o rt64/CMakeFiles/rt64.dir/src/hle/rt64_application_window.cpp.o -c /home/gman/Zelda64Recomp/lib/rt64/src/hle/rt64_application_window.cpp
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/hle/rt64_application_window.cpp:18:
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/common/rt64_common.h:12:
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/common/rt64_hlslpp.h:7:
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/contrib/hlslpp/include/hlsl++.h:3:
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/contrib/hlslpp/include/hlsl++_common.h:3:
In file included from /home/gman/Zelda64Recomp/lib/rt64/src/contrib/hlslpp/include/hlsl++_config.h:169:
/home/gman/Zelda64Recomp/lib/rt64/src/contrib/hlslpp/include/platforms/hlsl++_neon.h:155:24: error: expected unqualified-id
        static const uint32_t ControlMask[4] = { 0x03020100, 0x07060504, 0x0B0A0908, 0x0F0E0D0C }; // Swizzle x, swizzle y, swizzle z, swizzle w
                              ^
/usr/include/X11/X.h:223:23: note: expanded from macro 'ControlMask'
#define ControlMask             (1<<2)
                                 ^
```

**Comment by theofficialgman** [comment]
changing the `ControlMask` in the neon header file is enough to workaround this issue.

**Comment by theofficialgman** [comment]
Refer to https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/211 and https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/212 . As of writing, these unrelated issues have not been resolved.

**Comment by Mr-Wiseguy** [comment]
ARM is not a currently supported platform. If you wish to fix compilation on the project for that platform, please submit a PR with all the required fixes as I don't have the ability to build on that platform myself.

**Comment by theofficialgman** [comment]
@Mr-Wiseguy the project builds and runs with the suggestions made.

**Comment by Mr-Wiseguy** [comment]
You can submit a pull request and set up CI for the ARM platform if that's the case, as I can't verify it on my own. A video of it running would also be appreciated since I can't run it either.

**Comment by theofficialgman** [comment]
https://github.com/Zelda64Recomp/Zelda64Recomp/assets/28281419/a0e24ee9-e90f-4f84-9235-453d86006d15

Once you have created x86_64 CI, I am happy to help with arm64 CI.

**Comment by Mr-Wiseguy** [comment]
This project already has x86_64 CI, it's applied on pull requests and the dev branch. I believe github has an action runner for ARM Linux, so it should just be a matter of adapting the existing CI to it.
As for the issues you had in hlslpp, it's better to #undef the X11 defines than rename the variables in the library, as that's how this project handles X11 define name conflicts elsewhere.

**Comment by theofficialgman** [comment]
> I believe github has an action runner for ARM Linux, so it should just be a matter of adapting the existing CI to it.

They don't yet publicly actually for Linux. ARM64 MacOS runners have released but not ARM64 Linux. Public beta will come out April to June https://github.com/github/roadmap/issues/955 (so any day now) with full release July to September https://github.com/github/roadmap/issues/960

Cross compilation of N64Recomp isn't hard but SDL2 and Zelda64Recompiled are more difficult.

**Comment by Double0Derp** [comment]
Will it run on a non-arm64 linux platform?

**Comment by Double0Derp** [comment]
Such as a 3ds or Switch with Linux installed?

**Comment by Double0Derp** [comment]
Not a joke issue; if it can be recompiled for the linux system, like the GBATEMP article said, shouldnt it run on a Linux OS on a Nintendo console?

**Comment by Reonu** [comment]
> Not a joke issue; if it can be recompiled for the linux system, like the GBATEMP article said, shouldnt it run on a Linux OS on a Nintendo console?

if that console supports Vulkan when running Linux then sure. Somebody got it running on Switch (which is **not** a supported platform either, to be clear). 

The 3DS does not support Vulkan.

This project cannot support 3DS. Please stop spamming the repository with the same question.
