### ISSUE TITLE
My start button won't work after fixing C right.

### ISSUE THREAD

**Issue by m9henri** [Mr-Wiseguy/Zelda64Recomp#209]
**Describe the bug**
As in the title, my start button won't work after playing on steam and fixing the C Right Button. I think it has something to do that the PS-Button is mapped to the start button on my controller (I use [this n64 controller](https://amzn.eu/d/8khbw9i)) and Steam doesn't let me press PS-Button.

**To Reproduce**
1. In Steam, add the z64recomp as a external Steam game.
2. Get the controller layout from the community layouts.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 1.1.0
 - CPU: Intel Core i7 11700F
 - GPU: Nvidia Geforce RTX 3060 TI

**Comment by knfyy** [comment]
Were you able to get your controls worked out? I've been trying to use a USB n64 controller too (not the same exact one as you but same concept) and I can't figure it out. So many buttons dont register as what im pressing on the controller, also have the same issue where my right C button is the start button and other controls are mapped to using a right analog stick which obviously a 64 controller doesnt have so I'm a bit at a loss of how to sort it out. Gonna try going through steam this time which I havent tried yet

EDIT- I figured it out through steam, there are even button layouts already uploaded by other people. I had to do some tweaking on the layouts they provided but it was a million times easier than the way I was trying to set it up before.. Ported recomp into steam by their "add a non-steam game to my library" in the games section at the top of steam and then set up the controller from there. Its not 100% perfect, the rumble doesnt work atleast for me but that doesn't bother me at all

**Comment by m9henri** [comment]
> Were you able to get your controls worked out? I've been trying to use a USB n64 controller too (not the same exact one as you but same concept) and I can't figure it out. So many buttons dont register as what im pressing on the controller, also have the same issue where my right C button is the start button and other controls are mapped to using a right analog stick which obviously a 64 controller doesnt have so I'm a bit at a loss of how to sort it out. Gonna try going through steam this time which I havent tried yet

My n64 controller has the buttons (on a PS3 controller) mapped as:
- Joystick: left Joystick
- whole D-Pad: D-Pad
- A: circle
- B: cross
- C-Down: triangle
- C-Left: square
- C-Right: select
- Start: PS-Button
- L: L1
- R: R1
- Z: Left Trigger
The main problem is that my start button doesn't work and I can't press it on Steam because it's PS Button

**Comment by knfyy** [comment]
Gotcha, mine is a little strange too my pause button is the top C button. Idk if it will change anything for you so I apologize if it doesnt do anything but while I was setting up steam I came across the setting "Guide button focuses steam" in the Steam settings and then opening controller down at the bottom of the settings menu. 

I turned it to off but it was on for me by default, my start button used to open a weird steam page that reminded me of when you would hit the middle button on an xbox 360. Could have nothing to do with your issue but its worth a shot or atleast a good place to start looking, I also turned off the setting "playstation controller support" which if you turned off its possible that would stop it from registering as a PS button press. Not sure if its any help either but my original comment to you I updated with how I got it to work like 1 minute before you responded just now lol. (also thank you for your detailed reply I appreciate you)

**Comment by m9henri** [comment]
> Gotcha, mine is a little strange too my pause button is the top C button. Idk if it will change anything for you so I apologize if it doesnt do anything but while I was setting up steam I came across the setting "Guide button focuses steam" in the Steam settings and then opening controller down at the bottom of the settings menu.
> 
> I turned it to off but it was on for me by default, my start button used to open a weird steam page that reminded me of when you would hit the middle button on an xbox 360. Could have nothing to do with your issue but its worth a shot or atleast a good place to start looking, I also turned off the setting "playstation controller support" which if you turned off its possible that would stop it from registering as a PS button press. Not sure if its any help either but my original comment to you I updated with how I got it to work like 1 minute before you responded just now lol. (also thank you for your detailed reply I appreciate you)

My start button is PS-Button and Steam won't read inputs from PS-Button in-game. I already have turned off the setting you said. So it didn't change anything.

**Comment by knfyy** [comment]
Ahh I see what you mean now, my bad I misread your first post. I'm sure in the near future a lot of stuff will get ironed out

**Comment by Mr-Wiseguy** [comment]
Closing as this should have been solved by allowing the menu button to be remapped, which was necessary for these N64-style controllers. Feel free to reopen if it didn't solve the issue for your controller.
