### ISSUE TITLE
Fierce Deity Link backwards walking animation is broken

### ISSUE THREAD

**Issue by Bordraw** [Mr-Wiseguy/Zelda64Recomp#213]
**Describe the bug**
When you are playing as fierce deity link and you try to walk backwards while Z-targeting an enemy, he does this strange skipping animation and doesn't move backwards at full speed correctly. 

**To Reproduce**
1. Go to a boss room and equip the Fierce Deity Mask
2. Z-Target the boss and try to walk backwards

**Expected behavior**
Fierce Deity Link should walk backwards using the same animation as adult link in Ocarina of Time

**Screenshots**
I have attached a [video](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/6955001/ce71c1ce-cc61-40fe-9dd4-3dac1811d11f) demonstrating the bug.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.0.0
 - CPU: AMD Ryzen 9 5900HS
 - GPU: NVIDIA GeForce 3070

**Additional context**
At first I thought this was a bug with the recomp because I didn't remember the bug from the original, but I have found evidence that this behavior is an accurate recreation:

[Video of this behavior from someone playing the N64 version.](https://youtu.be/lN85x6sakFw?t=688) (not sure if its emulated or original hardware)

I also found [this forum post from 2005](https://zeldauniverse.net/forums/index.php?thread/21765-the-fierce-deity/&postID=483941#post483941) that seems to corroborate the bug's existence.

Unfortunately I don't have the original hardware to check the accuracy of this behavior directly but from what I can tell it seems likely that this is accurate. Regardless, as an enhancement for this port it would be good to fix this behavior.

**Comment by Mr-Wiseguy** [comment]
As you mentioned, this is accurate behavior. Fixing this would be out of scope of the base project, but is something that can be made into a mod once modding support is added in the future.

**Comment by Bordraw** [comment]
I think it would make sense to include this in the base project rather than a mod because it is fixing a bug from the original release
