### ISSUE TITLE
Patch 

### ISSUE THREAD

**Issue by DontCallMyPhoneUnlessUGotMeMyCode** [Mr-Wiseguy/Zelda64Recomp#219]
https://github.com/Zelda64Recomp/Zelda64Recomp/blob/b791a4aa1db982a7d4982d0c0308aaee726aaadb/patches/debug_patches.c#L51

**Comment by DontCallMyPhoneUnlessUGotMeMyCode** [comment]
> <!-- #218

**Comment by DontCallMyPhoneUnlessUGotMeMyCode** [comment]
#31

**Comment by Reonu** [comment]
Please don't spam our issue tracker..
