### ISSUE TITLE
219

### ISSUE THREAD

**Issue by DontCallMyPhoneUnlessUGotMeMyCode** [Mr-Wiseguy/Zelda64Recomp#220]
https://github.com/Zelda64Recomp/Zelda64Recomp/blob/b791a4aa1db982a7d4982d0c0308aaee726aaadb/patches/debug_patches.c#L51

**Comment by DontCallMyPhoneUnlessUGotMeMyCode** [comment]
#158

**Comment by Reonu** [comment]
Again, stop spamming our issue tracker or you will be blocked.
