### ISSUE TITLE
[Feature Request] Web build

### ISSUE THREAD

**Issue by JosefKuchar** [Mr-Wiseguy/Zelda64Recomp#221]
Do you guys think that it would be possible to compile this into wasm using emscripten and run it on web platform?
RT64 does not currently support WebGL/WebGPU, but I think it would be feasible to add support using wgpu c++ bindings (https://github.com/eliemichel/WebGPU-Cpp).
Are there any other changes that would be required?

**Comment by Mr-Wiseguy** [comment]
WebGPU isn't viable for a port of RT64, as explained in this comment: https://github.com/rt64/rt64/issues/6#issuecomment-2111301292
