### ISSUE TITLE
Missing one heart piece. 

### ISSUE THREAD

**Issue by SkyeSoar** [Mr-Wiseguy/Zelda64Recomp#226]
**Describe the bug**
Me and my boyfriend are playing Majora's Mask at the same time and have the same rom we're working with to play it recompiled and we seem to both be missing a heart somewhere. We've both triple checked our saves for any missing heart pieces at all the locations and seem to have both come up 1 heart piece short to 100% completions. I can provide my .bin file for someone to check if a flag got marked at some point in the game and didn't give the heart piece for whatever reason.

**To Reproduce**
I don't know if it's the rom we used or just something wrong in general so I don't know how to reproduce this. He's been playing through it faster than me cause I'm a first time player for Majora's Mask but we've both come up one missing.

**Expected behavior**
Of course we expected to have them all to 100% the game lol.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.0.0
 - CPU: Intel Core i5
 - GPU: NVIDIA GeForce RTX 4090

**Additional context**
We would try to figure out which flag was triggered and broke but we can't read hex well at all. ;w;

**Comment by Reonu** [comment]
Thanks for the issue. 

Please do provide the savefile, otherwise it's impossible to diagnose this issue.

**Comment by SkyeSoar** [comment]
Real quick cause github doesn't support .bin files like the save is how would I go about sending it? Sorry, I haven't really used github to send stuff before.
Here's it via google drive if this works correctly:
https://drive.google.com/file/d/1Dh9yT9g5xSosP_x-3j81J-K2aObchniw/view?usp=sharing

**Comment by Reonu** [comment]
> Real quick cause github doesn't support .bin files like the save is how would I go about sending it? Sorry, I haven't really used github to send stuff before. Here's it via google drive if this works correctly: https://drive.google.com/file/d/1Dh9yT9g5xSosP_x-3j81J-K2aObchniw/view?usp=sharing

This link is private. you need to make it so that anyone with the link can see the file.

**Comment by SkyeSoar** [comment]
Here's the updated link sorry about that and thanks for helping out! 
https://drive.google.com/file/d/1Dh9yT9g5xSosP_x-3j81J-K2aObchniw/view?usp=sharing

**Comment by Reonu** [comment]
Hello. You missed the heart piece from beating the shooting gallery in the swamp for the second time.

![imagen](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/73082155-d8d1-4a4c-9052-e4e1e283d087)

Closing issue.

**Comment by SkyeSoar** [comment]
> Hello. You missed the heart piece from beating the shooting gallery in the swamp for the second time.
> 
> ![imagen](https://private-user-images.githubusercontent.com/15913880/332202863-73082155-d8d1-4a4c-9052-e4e1e283d087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDI0NzcsIm5iZiI6MTcxNjI0MjE3NywicGF0aCI6Ii8xNTkxMzg4MC8zMzIyMDI4NjMtNzMwODIxNTUtZDhkMS00YTRjLTkwNTItZTRlMWUyODNkMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIxNTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTQ4NWM0NTA3MjRkNzEyMmM2NzlmNDRmYjUwNjJjMWYzOGFjNjA2NTQ5Zjg3ODQ0Yjk2ZTlkYTE0Nzk1YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URYPetJPtSEL4lf3_8e2GxeK4v2ycCCQvdjqdZ7un_A)
> 
> Closing issue.

Thank you again for helping us ultimately it was just human error and we're sorry for wasting your time. But thank you for helping us find our last heart piece, I can't wait to keep watching this progress grow develop! Have a good day and thank you for the help and sorry for wasting some of your time.

**Comment by Reonu** [comment]
No problem, thanks for the kind words :)

**Comment by fmatzdorf** [comment]
I'm curious, how did you determine this from a save file?

**Comment by Reonu** [comment]
> I'm curious, how did you determine this from a save file?

I didn't. I made a guess and got it right on the first try.
