### ISSUE TITLE
Seahorse glow visible through walls ? (might also happen on real console, haven't tested.)

### ISSUE THREAD

**Issue by Lucaspec72** [Mr-Wiseguy/Zelda64Recomp#228]
**Describe the bug**
In Pinnacle Rock, the glow from the seahorses (both the yellow one, and the pink one),  remains visible no matter where you are on the map, even if walls obstruct them.

**To Reproduce**
1. go to Pinnacle Rock with the seahorse.
2. Defeat all the sea snakes.
4. Pull back to the surface, or near it, and look down at the direction of where they are. You'll see the glow is visible through walls.

**Expected behavior**
The glow should only be visible if directly seeing it, not through walls ? As stated in title, haven't checked if this happens on console.

**Screenshots**

![20240520223519_1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/48445530/6e8e2a20-9501-403a-a9e2-5e060ea68ea4)
![20240520223529_1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/48445530/f4ec2ccf-df55-4839-90ac-abfbd413f176)
![20240520223546_1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/48445530/a7cdd30c-20cd-4d3d-9037-f7b953c68ccb)
![20240520223623_1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/48445530/b5c08a03-7b43-414e-a6b0-406757a4ba7f)
![20240520223706_1](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/48445530/0473b03f-481f-451a-9a6c-ccf50933c78f)

 - OS: SteamOS 3.5.19, build 20240422.1
 - Version: 1.0.1
 - CPU: Steam Deck AMD APU 'Vangogh'
 - GPU: Steam Deck AMD APU 'Vangogh'

**Comment by Reonu** [comment]
Thanks for the report!

However, I just booted up my N64 and confirmed that this is how the vanilla game behaves, so nothing to fix here.

![imagen](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/eb30cd82-3505-492f-b0db-6aef0c9a1e7f)
