### ISSUE TITLE
[Feature Request] Tessellation Based on Depth

### ISSUE THREAD

**Issue by shinra358** [Mr-Wiseguy/Zelda64Recomp#230]
request the ability to have tessellation for objects close to the camera but the furture from the camera you get, the feature fades. This is to smooth out the sharp points on n64 models and ignoring the effect in the bg because it is very taxing and we wont notice it in the bg anyway. This is to enjoy the benefits of tessellation while removing some of the heavy burden on the pc by not tessellating everything that isn't close to you.

**Comment by Reonu** [comment]
First of all, this is an RT64 issue. But also, just to save your time, this is unfeasible and Darío will confirm as much if you ask. There's no displacement info to leverage.

**Comment by shinra358** [comment]
I dont really understand what you just said. i asked for the tessellation feature but you called it an issue so im confused. Is this not the place to request things for the pc port of oot? if not, where is that at?
