### ISSUE TITLE
Found an answer that might solve an issue that may be happening to others

### ISSUE THREAD

**Issue by BlueBlanket0** [Mr-Wiseguy/Zelda64Recomp#232]
So originally I had a problem where I could not open the .exe on my PC, where the file won't even try to open and nothing pops up.

What I found out is that you need to open the .exe on the admin account of your PC so Windows Defender can ask if you want to ask for it (It didn't ask me when I was on my other account). I just want to put this out here for if anyone else may have had the same problem as I did and is lost as to what may or may not be the problem.

*Running the file as an administrator might work but if it doesn't go to your admin account to then open the file*

**Comment by knfyy** [comment]
Were you able to get your controls worked out? I've been trying to use a USB n64 controller too (not the same exact one as you but same concept) and I can't figure it out. So many buttons dont register as what im pressing on the controller, also have the same issue where my right C button is the start button and other controls are mapped to using a right analog stick which obviously a 64 controller doesnt have so I'm a bit at a loss of how to sort it out. Gonna try going through steam this time which I havent tried yet

**Comment by Mr-Wiseguy** [comment]
Thank you for the suggestion, if anyone runs into a similar issue we'll point them at this for a potential fix.
