### ISSUE TITLE
keep crashing mm

### ISSUE THREAD

**Issue by 1234man32** [Mr-Wiseguy/Zelda64Recomp#235]
i have linux kubuntu os and amd driver nvidia
keep crash dont know what problem it is.. 
i activated the app and show up the app and boom show a clear screen then gone stop. 
here ya go my specs to my laptop lenovo legion 5.

OVERVIEW
1. E-camera shutter switch 6. HDMI 2.1
2. USB 3.2 Gen 1 7. USB 3.2 Gen 1 (Always On)
3. Ethernet (RJ-45) 8. Power connector
4. USB-C 3.2 Gen 2 9. USB-C 3.2 Gen 2 (data transfer / DP 1.4 only)
5. 2x USB 3.2 Gen 1 10. Headphone / microphone combo jack (3.5mm)
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
1 of 7Lenovo Legion 5 15ACH6H - March 22 2022
PERFORMANCE
Processor
Processor Family
AMD Ryzen™ 5 / 7 Processor
Processor**
Processor Name Cores Threads Base
Frequency
Max
Frequency Cache Memory
Support Processor Graphics
AMD Ryzen 5
5600H 6 12 3.3GHz 4.2GHz 3MB L2 / 16MB
L3 DDR4-3200 AMD Radeon™
Graphics
AMD Ryzen 7
5800H 8 16 3.2GHz 4.4GHz 4MB L2 / 16MB
L3 DDR4-3200 AMD Radeon
Graphics
Operating System
Operating System**
Windows® 11 Pro 64•
Windows 11 Home 64•
Windows 10 Pro 64•
Windows 10 Home 64•
No operating system•
Graphics
Graphics**[1]
Graphics Type Memory Boost Clock TGP Key Features
NVIDIA® GeForce RTX™
3060 Laptop GPU Discrete 6GB
GDDR6
1425 MHz /
1702 MHz 130W Advanced Optimus, Resizable BAR, Dynamic
Boost 2.0, VR ready, DirectX® 12 Ultimate
NVIDIA GeForce RTX
3070 Laptop GPU Discrete 8GB
GDDR6 1560 MHz 130W Advanced Optimus, Resizable BAR, Dynamic
Boost 2.0, VR ready, DirectX 12 Ultimate
Notes:
Free-Sync via integrated graphics; G-Sync via discrete graphics1.
Monitor Support
Monitor Support
Supports up to 4 independent displays (native display and 3 external monitors via HDMI® and USB-C®)
• HDMI supports up to 7680x4320@60Hz
• USB-C supports up to 5120x3200@60Hz
Chipset
Chipset
AMD SoC (System on Chip) platform
Memory
Max Memory[1]
Up to 32GB DDR4-3200 offering
Memory Slots
Two DDR4 SO-DIMM slots, dual-channel capable
Memory Type
DDR4-3200
Notes:
The max memory is based on the test results with current Lenovo® memory offerings. The system may support more memory as the
technology develops.
1.
Storage
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
2 of 7Lenovo Legion 5 15ACH6H - March 22 2022
Storage Support[1]
Up to two drives, 2x M.2 SSD
• M.2 2242 SSD up to 512GB
• M.2 2280 SSD up to 1TB
Storage Type***
Disk Type Interface RPM Security
M.2 2242 SSD PCIe® NVMe®, PCIe 3.0 x4 - -
M.2 2280 SSD PCIe NVMe, PCIe 3.0 x4 - -
Notes:
The storage capacity supported is based on the test results with current Lenovo storage offerings. The system may support larger
storage as the technology develops.
1.
Removable Storage
Optical
None
Card Reader
No card reader
Multi-Media
Audio Chip
High Definition (HD) Audio, Realtek® ALC3306 codec
Speakers
Stereo speakers, 2W x2, Nahimic Audio
Microphone
Dual array microphone
Camera
HD 720p, with E-camera shutter, fixed focus
Battery
Battery**
Integrated Li-Polymer 60Wh battery, supports Rapid Charge Pro (charge up to 50% in 30min)•
Integrated Li-Polymer 80Wh battery, supports Rapid Charge Pro (charge up to 50% in 30min)•
Max Battery Life[1]
MobileMark® 2018: 7 hr (60Wh)•
MobileMark 2018: 9.2 hr (80Wh)•
Notes:
All battery life claims are approximate maximum and based on results using the MobileMark 2014, MobileMark 2018, JEITA 2.0,
continuous 1080p video playback (with 150nits brightness and default volume level) or Google Power Load Test (PLT) battery-life
benchmark tests. Actual battery life will vary and depends on many factors such as product configuration and usage, software use,
wireless functionality, power management settings, and screen brightness. The maximum capacity of the battery will decrease with
time and use.
1.
Power Adapter
Power Adapter**[1]
230W slim tip (3-pin) AC adapter, 100-240V, 50-60Hz•
300W slim tip (3-pin) AC adapter, 100-240V, 50-60Hz•
Notes:
AC adapter offerings depend on the country.1.
DESIGN
Display
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
3 of 7Lenovo Legion 5 15ACH6H - March 22 2022
Display**[1]
Size Resolution Touch Type Brightness Surface Aspect
Ratio
Contrast
Ratio
Color
Gamut
Viewing
Angle Key Features
15.6" FHD
(1920x1080) None IPS 250 nits Anti-
glare 16:9 800:1 45%
NTSC 170° Refresh rate 120Hz, Free-
Sync, DC dimmer
15.6" FHD
(1920x1080) None IPS 300 nits Anti-
glare 16:9 1000:1 100%
sRGB 170°
Refresh rate 165Hz,
Dolby® Vison, Free-Sync,
DC dimmer, Advanced
Optimus support
15.6" FHD
(1920x1080) None IPS 300 nits Anti-
glare 16:9 1200:1 100%
sRGB 170° Refresh rate 60Hz, Free-
Sync, DC dimmer
15.6" WQHD
(2560x1440) None IPS 300 nits Anti-
glare 16:9 1000:1 100%
sRGB 178°
Refresh rate 165Hz, Dolby
Vision™, Free-Sync, G-
Sync, DC dimmer
Touchscreen
Non-touch
Notes:
California Electronic Waste Recycling Fee
In California, per state law, Lenovo charges an electronic waste recycling fee on this covered device at the time of sale of the product.
For more information, go to https://www.calrecycle.ca.gov/Electronics/Consumer
1.
Input Device
Keyboard**
Phantom blue model: 6-row, multimedia Fn keys, numeric keypad, black keycap•
Stingray model: 6-row, multimedia Fn keys, numeric keypad, moon white keycap•
Keyboard Backlight**
Blue backlight•
White backlight•
4-Zone RGB backlight•
Touchpad
Buttonless Mylar® surface multi-touch touchpad, 69 x 104 mm (2.72 x 4.09 inches)
Mechanical[1]
Dimensions (WxDxH)
362.56 x 260.61 x 22.5-25.75 mm (14.27 x 10.26 x 0.89-1.01 inches)
Weight
2.4 kg (5.3 lbs)
Case Color**
Phantom blue (top), shadow black (bottom)•
Stingray (top), dove grey (bottom)•
Surface Treatment
Painting
Case Material
PC + ABS (top), PC + ABS (bottom)
System Lighting
No system lighting
Notes:
The system dimensions and weight vary depending on configurations.1.
CONNECTIVITY
Network
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
4 of 7Lenovo Legion 5 15ACH6H - March 22 2022
Onboard Ethernet
Gigabit Ethernet, 1x RJ-45
WLAN + Bluetooth®**[1][2]
802.11ac 2x2 Wi-Fi® + Bluetooth 5.1, M.2 Card•
Wi-Fi 6, 802.11ax 2x2 Wi-Fi + Bluetooth 5.1, M.2 card•
Notes:
Bluetooth 5.2 is hardware ready but may run at a lower version due to OS limitation1.
Wi-Fi 6 full features might be limited by country-level restrictions.2.
Ports[1]
Standard Ports
3x USB 3.2 Gen 1•
1x USB 3.2 Gen 1 (Always On)•
1x USB-C 3.2 Gen 2 (support data transfer and DisplayPort™ 1.4)•
1x USB-C 3.2 Gen 2 (support data transfer, Power Delivery and DisplayPort 1.4)•
1x HDMI 2.1•
1x Ethernet (RJ-45)•
1x Headphone / microphone combo jack (3.5mm)•
1x Power connector•
Notes:
The transfer speed of following ports will vary and, depending on many factors, such as the processing speed of the host device, file
attributes and other factors related to system configuration and your operating environment, will be slower than theoretical speed.
USB 2.0: 480 Mbit/s;
USB 3.2 Gen 1 (SuperSpeed USB 5Gbps, formerly USB 3.0 / USB 3.1 Gen 1): 5 Gbit/s;
USB 3.2 Gen 2 (SuperSpeed USB 10Gbps, formerly USB 3.1 Gen 2): 10 Gbit/s;
USB 3.2 Gen 2x2 (SuperSpeed USB 20Gbps): 20 Gbit/s;
Thunderbolt™ 3/4: 40 Gbit/s
1.
SECURITY & PRIVACY
Security
Security Chip
Firmware TPM 2.0 integrated in SoC
Fingerprint Reader
No fingerprint reader
BIOS Security
Power-on password•
Supervisor password•
Hard disk password•
Other Security
E-Camera shutter
SERVICE
Warranty
Base Warranty**[1]
1-year depot service•
1-year depot with 2-year system board service (Korea only)•
2-year (1-yr battery) depot service•
3-year (1-yr battery) depot service•
Notes:
More information of warranty policy, please access https://pcsupport.lenovo.com/warranty1.
ENVIRONMENTAL
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
5 of 7Lenovo Legion 5 15ACH6H - March 22 2022
Operating Environment
Temperature[1]
At altitudes up to 2438 m (8,000 ft)
- Operating: 5°C to 35°C (41°F to 95°F)
- Storage: 5°C to 43°C (41°F to 109°F)
•
At altitudes above 2438 m (8,000 ft)
- Maximum temperature when operating under the unpressurized condition: 31.3°C (88°F)
•
Humidity
Operating: 8% to 95% at wet-bulb temperature 23°C (73°F)•
Storage: 5% to 95% at wet-bulb temperature 27°C (81°F)•
Altitude
Maximum altitude (without pressurization): 3048 m (10,000 ft)
Notes:
When you charge the battery, its temperature must be no lower than 10°C (50°F).1.
ACCESSORIES
Bundled Accessories
Bundled Accessories
Lenovo Legion™ M300 RGB Gaming Mouse (USB connector)•
None•
CERTIFICATIONS
Green Certifications
Green Certifications
ErP Lot 3•
RoHS compliant•
Feature with ** means that only one offering listed under the feature is configured on selected models.•
Feature with *** means that one or more offerings listed under the feature could be configured on selected
models.
•
Lenovo reserves the right to change specifications or other product information without notice. Lenovo is not
responsible for photographic or typographical errors. LENOVO PROVIDES THIS PUBLICATION “AS IS,”
WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES
OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions do not allow
disclaimer of express or implied warranties in certain transactions, therefore this disclaimer may not apply to
you.
•
The specifications on this page may not be available in all regions, and may be changed or updated without
notice.
•
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
6 of 7Lenovo Legion 5 15ACH6H - March 22 2022
Lenovo Legion 5 15ACH6H
PSREF
Product Specifications
Reference
7 of 7Lenovo Legion 5 15ACH6H - March 22 2022

**Comment by 1234man32** [comment]
copy and paste pdf file for convenient

**Comment by Reonu** [comment]
Hi

As stated in the readme, a possible workaround for this issue is to add the executable to Steam as a non-steam game. Then, in your Steam library, go to the properties of the Zelda 64 Recompiled entry, and go to Compatibility. Enable the "force a specific compatibility tool" checkbox and set it to "Steam Linux Runtime". Then launch it through Steam.

Let us know if this solves the issue.

**Comment by 1234man32** [comment]
ok thank man well if dont work somehow then i got to buy a new laptop or steam deck hehe

**Comment by 1234man32** [comment]
well i done with this so closing up shop
