### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by Mr-Poyetas** [Mr-Wiseguy/Zelda64Recomp#239]
I tried to run the app on Linux Mint MATE 21.3 under Steam's Linux Runtime 1.0

Error screenshot:
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/3d514433-6a98-4e85-929d-51dda268a062)

GPU features screenshot:
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/c6d3c98d-7cf1-48ea-b770-be1ebdc4da49)

Does this mean my GPU doesn't support the game?

Specs:

10GB RAM
CPU: i3-3220
GPU: AMD R5 240
Linux GPU Driver: amdgpu

**Comment by Mr-Wiseguy** [comment]
Your GPU does support the game, so I would double check that you have your Vulkan drivers installed and up-to-date. Can you download and run the Vulkan Hardware Capability Viewer (https://vulkan.gpuinfo.org/download.php) and show the results of running it?

**Comment by Mr-Poyetas** [comment]
Hello, thanks for your answer.

Here's a screenshot of the app:
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/d3fd8222-05ef-4ed1-8dc6-bc1afde59580)

And here's a full json file just in case:
[AMD Radeon HD 8500 Series (RADV OLAND).json](https://github.com/Zelda64Recomp/Zelda64Recomp/files/15427626/AMD.Radeon.HD.8500.Series.RADV.OLAND.json)

**Comment by Mr-Wiseguy** [comment]
Would you be able to build the project and do some breakpoint debugging? Breakpointing at [this line](https://github.com/rt64/rt64/blob/9b9237f097a12bcef6ab6233bcffa6764e02cad3/src/vulkan/rt64_vulkan.cpp#L3348) would help see what GPU devices RT64 is picking up. You may also be able to download a debug build CI artifact to and use that for debugging instead of building it yourself.

**Comment by Mr-Poyetas** [comment]
Hi.

I've decided to try and build the project. After many obstacles I've been able to reach step 5 of your BUILDING.MD guide.

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/b0a23b7f-acf0-44ff-987f-e297ff6f7429)


However, I don't know how to set breakpoints, unfortunately.

Besides, I'm not sure when I must use them. Before or after compiling the project (use them on the compiled binary, I mean).

Can you please help me? What terminal command do I need to use at what moment?

**Comment by Mr-Poyetas** [comment]
I've also ran GDB on a debug build of Zelda64Recompiled and I managed to get this, is it useful?

gdb  ./Zelda64Recompiled-x86_64.AppImage 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Zelda64Recompiled-x86_64.AppImage...
(No debugging symbols found in ./Zelda64Recompiled-x86_64.AppImage)
(gdb) run
Starting program: /home/[user]/Descargas/Zelda64Recompiled-x86_64.AppImage 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 103835]
process 103832 is executing new program: /usr/bin/env
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 103832 is executing new program: /usr/bin/bash
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 103840]
[Detaching after fork from child process 103842]
[Detaching after fork from child process 103850]
Gtk-Message: 01:45:33.172: Failed to load module "xapp-gtk3-module"
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Missing required extension: VK_EXT_scalar_block_layout.
Unable to create device. Required extensions are missing.
Unable to find compatible graphics device.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize RT64
/tmp/.mount_Zelda6XK2k29/AppRun: línea 14: 103850 Abortado                (`core' generado) ./Zelda64Recompiled
[Inferior 1 (process 103832) exited with code 0206]
(gdb)

**Comment by Mr-Wiseguy** [comment]
That's very useful. Unfortunately it looks like that GPU is missing support for a required Vulkan feature in radv, The official drivers on Windows support that feature, so the GPU is capable of it, meaning it's just a radv issue. There are the proprietary AMD drivers which are probably closer to the Windows drivers given that they're both developed by AMD, but it's probably not reasonable to expect users to switch drivers just to run this.

We can try looking into removing the need for this particular Vulkan feature requirement in the future, but given the "radv is not a conformant Vulkan implementation" warning I'm not sure it'd actually work even with that change. It seems that this GPU may only be viable for running this on Windows, sorry about that.

**Comment by Mr-Poyetas** [comment]
Hello. I've got some interesting information.

I can confirm the game works fine on Windows. I apologize for not testing the game there beforehand, I rarely use Windows these days.

![Screenshot_107](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/dd00a00c-fd57-4699-889d-d7f73587087d)

![Screenshot_106](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/fc76147f-d072-4b88-9623-240580fd8e30)


Also, you were right, I switched the linux video driver to the "radeon" one, and the game boots.

![2024-05-25_03-24](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/dcbfc52d-937d-4485-8efb-6fbd0bca8c15)

I did this because the "radeon" video driver was actually my gpu's default driver. I forced the "amdgpu" driver, which is much better.

However, despite the game actually booting, it runs less than 1FPS and it hangs right here:

![2024-05-25_03-27](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/143344104/2637a308-01d4-4b45-a378-5f110deeb47f)

So, I'll just stick to playing the game on Windows. You can close this issue now.

Thank you very much for your help.

**Comment by Mr-Wiseguy** [comment]
Glad you were able to find a way to run this project, thanks for helping investigate this issue.
