### ISSUE TITLE
cant change what button opens the menu

### ISSUE THREAD

**Issue by FSR-1** [Mr-Wiseguy/Zelda64Recomp#24]
can cause some controllers like the NSO n64 to have it mapped to c right causing you to lose a c button but i might just be being stupid and cant see the option to change it

**Comment by Mr-Wiseguy** [comment]
Hi, that's really good to know. You're right that it's not currently available, I'll make sure to add an option for rebinding the menu button in a future version. In the meantime you might be able to launch it through Steam as a non-Steam game and use Steam Input to remap the buttons. Let me know if that works for you!

**Comment by FSR-1** [comment]
thank you also i noticed another issue about the ends of the magic bar having lines 
![Screenshot (289)](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/169501359/0410ffea-9841-4f91-aea8-0d2995ec13eb)

**Comment by Majora170** [comment]
Came here looking to report the exact same problem. Looks like I was beaten to the mark.

**Comment by Mr-Wiseguy** [comment]
This issue will most likely go away if you turn off MSAA in the graphics settings menu. This project has to use a pretty complicated GPU feature to get MSAA to work without causing artifacts like those and should disable MSAA automatically when that feature isn't present, but it seems like that detection failed here.

I'd also recommend updating your graphics drivers, as it may be a bug in an older version that's causing that detection to fail. What graphics card or GPU does your system have?

**Comment by Gurkgamer** [comment]
> can cause some controllers like the NSO n64 to have it mapped to c right causing you to lose a c button but i might just be being stupid and cant see the option to change it

If you launch the executable through Steam, you can use the Control Layout Mapping to change the BACK button to another kind of button. I changed it to right stick press, for example, and it did allow me to play properly. I have to use ESC now to enter de menus, but I think that's a minor issue.

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/6461032/3c7f4303-d949-43c0-8b07-0a7ee04e5bd0)
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/6461032/cef23cc9-78f6-4781-86ba-5225acd76c36)

**Comment by FSR-1** [comment]
thx for the help also when i press z its permanently on  im very new to steam input usually games which i use gamepads with don't need me to configure it

**Comment by FSR-1** [comment]
used betterjoy and steam input since with out betterjoy the z button wouldn't turn off unless you held it

**Comment by Reonu** [comment]
Issue being tracked in #41
