### ISSUE TITLE
Error While Building Darwin Branch

### ISSUE THREAD

**Issue by AwayCoast23465** [Mr-Wiseguy/Zelda64Recomp#241]
when building the branch i get this output;

awaycoast@Aways-Air build % cmake -S . -B cmake-build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build . --target Zelda64Recompiled -j$(nproc) --config debug              
CMake Error: The source directory "/Users/awaycoast/Desktop/Zelda64Recomp/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
                                            [  0%] Built target file_to_c
[  0%] Built target nfd
[  0%] Built target lunasvg
[  0%] Generating ../src/shaders/VideoInterfacePSRegular.hlsl.spv
[  0%] Generating ../src/shaders/DebugPS.hlsl.spv
[  0%] Generating ../src/shaders/BoxFilterCS.hlsl.spv
[  0%] Generating ../src/shaders/ComposePS.hlsl.spv
[  0%] Generating ../src/shaders/BicubicScalingCS.hlsl.spv
/bin/sh: /Users/awaycoast/Desktop/Zelda64Recomp/lib/rt64/src/contrib/dxc/bin/x64/dxc: cannot execute binary file
/bin/sh: /Users/awaycoast/Desktop/Zelda64Recomp/lib/rt64/src/contrib/dxc/bin/x64/dxc: cannot execute binary file
/bin/sh: /Users/awaycoast/Desktop/Zelda64Recomp/lib/rt64/src/contrib/dxc/bin/x64/dxc: cannot execute binary file
gmake[3]: *** [rt64/CMakeFiles/rt64.dir/build.make:530: src/shaders/DebugPS.hlsl.spv] Error 126
gmake[3]: *** Waiting for unfinished jobs....
gmake[3]: *** [rt64/CMakeFiles/rt64.dir/build.make:502: src/shaders/VideoInterfacePSRegular.hlsl.spv] Error 126
gmake[3]: *** [rt64/CMakeFiles/rt64.dir/build.make:426: src/shaders/BoxFilterCS.hlsl.spv] Error 126
/bin/sh: /Users/awaycoast/Desktop/Zelda64Recomp/lib/rt64/src/contrib/dxc/bin/x64/dxc: cannot execute binary file
/bin/sh: /Users/awaycoast/Desktop/Zelda64Recomp/lib/rt64/src/contrib/dxc/bin/x64/dxc: cannot execute binary file
gmake[3]: *** [rt64/CMakeFiles/rt64.dir/build.make:526: src/shaders/ComposePS.hlsl.spv] Error 126
gmake[3]: *** [rt64/CMakeFiles/rt64.dir/build.make:430: src/shaders/BicubicScalingCS.hlsl.spv] Error 126
gmake[2]: *** [CMakeFiles/Makefile2:369: rt64/CMakeFiles/rt64.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
 clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing)clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
: Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
make[4]: *** [cheats.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [billboard_tagging.o] Error 1
make[4]: *** [actor_transform_tagging.o] Error 1
make[4]: *** [camera_patches.o] Error 1
make[4]: *** [cutscene_patches.o] Error 1
make[4]: *** [culling.o] Error 1
make[4]: *** [camera_transform_tagging.o] Error 1
make[4]: *** [autosaving.o] Error 1
gmake[3]: *** [CMakeFiles/PatchesBin.dir/build.make:70: CMakeFiles/PatchesBin] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:283: CMakeFiles/PatchesBin.dir/all] Error 2
 [  2%] Built target RmlCore
         [ 98%] Built target RecompiledFuncs
gmake[1]: *** [CMakeFiles/Makefile2:324: CMakeFiles/Zelda64Recompiled.dir/rule] Error 2
gmake: *** [Makefile:208: Zelda64Recompiled] Error 2

**Comment by Mr-Wiseguy** [comment]
The Darwin branch is currently a work in progress, there's no point in building it until Metal support is added to RT64. Documentation on how to build for Mac will come once that happens.

**Comment by AwayCoast23465** [comment]
> The Darwin branch is currently a work in progress, there's no point in building it until Metal support is added to RT64. Documentation on how to build for Mac will come once that happens.

Is there a way to view the progress of the metal rt64 branch?

**Comment by doctor-amaton** [comment]
I know this is closed, but I wanted to add for anyone finding this issue in the future that this issue is due to your LLVM environment not supporting MIPS as a target. If you run `clang -print-targets` you won't find MIPS listed, which is why clang doesn't know what to do with those options being passed to it.

I don't know how to solve this for macOS, but perhaps you can try the `brew` version of LLVM + clang? maybe that one has MIPS support. I had to install it manually on Windows in order to make sure I was getting a complete one.
