### ISSUE TITLE
Corrupted Save File after a Blackout [Savefile after zora temple wanted, please share one if you're at around that point in the game]

### ISSUE THREAD

**Issue by NemeZisFull** [Mr-Wiseguy/Zelda64Recomp#245]
I opened the file and there is nothing writed on it.
I dont know if i can get some one saved file i was going for the 4th temple, i would like one save that has the zora temple as least complete...
T.T
(This is like my 5th issue with this game, is like a curse a this point)

**Comment by Reonu** [comment]
Hello, thanks for the report!

First, sorry your savefile got corrupted. We're adding automatic save backups to the next release to prevent this from happening again.

I'm going to leave this issue open for a bit so that other people can see it and hopefully share a savefile at around the same point in the game.

**Comment by Mr-Wiseguy** [comment]
I have a save file from a playthrough where I had just entered Stone Tower Temple, is that good? If you load it with the Rewind option instead then it'll bring you to right after having beat Great Bay Temple.
[mm.n64.us.1.0.zip](https://github.com/Zelda64Recomp/Zelda64Recomp/files/15407570/mm.n64.us.1.0.zip)

**Comment by NemeZisFull** [comment]
> I have a save file from a playthrough where I had just entered Stone Tower Temple, is that good? [mm.n64.us.1.0.zip](https://github.com/Zelda64Recomp/Zelda64Recomp/files/15407570/mm.n64.us.1.0.zip)

It could but I need to check it and compare a little because I think I miss a lot of thing and don't wanna lose all content, but preciate.
Also my pc got fck trying to get a old build from this morning and now I'm formatting....

**Comment by NemeZisFull** [comment]
Thank you for the save! Actually was almost like mine(except masks), game actually beaten!

**Comment by Reonu** [comment]
Fixed by #260
