### ISSUE TITLE
Legend of Zelda and the Screeching Audio Nightmare

### ISSUE THREAD

**Issue by bonniebear** [Mr-Wiseguy/Zelda64Recomp#246]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
Audio quality is very poor, sounding off pitch and shrill like it went through some bad digital filter five times. Its legitimately uncomfortable to hear too so the game in pretty much unplayable in this state. I'll have a video recording linked below that demonstrates exactly what I'm experiencing.

Graphics quality looks expected as far as I can tell and the issue is consistent between all graphics, framerate and window settings. I haven't been able to test gameplay for potential input lag since I'd rather not go through the opening cinematic in its current state. If there's a way I save insert another save file into this so I could jump right into gameplay, the instructions would be appreciated.

**To Reproduce**
As soon as the game is launched

**Expected behavior**
Clean audio.

**Screenshots**
Performance appears normal
![scrnshotzelda](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70817734/6a22c11c-ffa9-4b5c-ae62-24a02ac44f4a)

Link to video:
https://drive.google.com/file/d/1YbQQSvUZs7AfdmfmtauAA9fsFj4xYcTV/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 22H2
 - CPU: Intel Core i7-8700
 - GPU 1: Radeon RX 6650XT (Driver: 24.5.1) Main display
 - GPU 2: Nvidia Quadro K600 (Driver: R470 U16) CRT Display

**Additional context**
I have tested this with both monitors, and the issue is reproduced exactly on both.

**Comment by Mr-Wiseguy** [comment]
This sounds like it may be the same as https://github.com/Zelda64Recomp/Zelda64Recomp/issues/22. Can you try the fix detailed here? https://github.com/Zelda64Recomp/Zelda64Recomp/issues/22#issuecomment-2120517612

**Comment by bonniebear** [comment]
ah ha! yes that was it! Thanks! The sound functions properly now.

A bit of feedback on this issue since, while it's not an issue of anything actually wrong with this project, I can see this being a problem showing up again with other users if they manually changed their SDL_AUDIODRIVER registry file to dsound like I had. Reason I had done that in the first place is this is common work around for Win 10 and 11 users who run games in dosbox but who can't get sound in their games (unless it has redbook audio). The issue is above my knowledge but I think it has something to do with wavetable midi sound that was used in old dos games not mixing (no pun intended) well with the modern windows audio api's... I think? Like I said, not really an expert at this or anything to do with SDL really.

So far using the legacy audio drivers have had any issues up until now. Not saying this or N64: Recompiled must accommodate this or anything, but might be something to consider adding to the FAQ or Known Issues section is this keep occurring, with this project aimed toward retrogamers and all.

Thank you again.

**Comment by Mr-Wiseguy** [comment]
Glad that solved it, and now that I have more information about how the issue pops up I should have better luck reproducing and fixing it. If that doesn't work out I'll be sure to add it to the FAQ like you suggested.
