### ISSUE TITLE
Could not find entry point SetThreadDescription

### ISSUE THREAD

**Issue by ProfeJavix** [Mr-Wiseguy/Zelda64Recomp#247]
I downloaded 1.0.1 release for Windows and this Dialog pops up
![bandicam 2024-05-22 08-32-07-923](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/134125102/d0df196f-c79f-4c84-a24c-b928cf90d11c)
If anyone knows what it means please tell me

**Comment by Reonu** [comment]
Hi, what's your OS?

**Comment by Marcelo20XX** [comment]
Did you unzipped the file? it seems that its been executed within the zip

**Comment by ProfeJavix** [comment]
> Hi, what's your OS?

It´s Windows 10

**Comment by ProfeJavix** [comment]
> Did you unzipped the file? it seems that its been executed within the zip

Yeah, I also unzipped it and got the same error

**Comment by Mr-Wiseguy** [comment]
> > Hi, what's your OS?
> 
> It´s Windows 10

More specifically, what version of Windows 10? You probably need to update your install.

**Comment by ProfeJavix** [comment]
> > > Hi, what's your OS?
> > 
> > 
> > It´s Windows 10
> 
> More specifically, what version of Windows 10? You probably need to update your install.

Oh, thats probably it. My device has Windows 10 Pro x64 from 2016. Unfortunately I cant update (tried it before without success and tons of crashes), so I think there is no solution in this case besides getting a new one

**Comment by Mr-Wiseguy** [comment]
Unfortunately, that version of Windows 10 is too old. Even if this direct issue were solved by not using SetThreadDescription, you'd run into other issues with the project and RT64 due to the features they use.

**Comment by ProfeJavix** [comment]
Ok, anyway thanks for the support
