### ISSUE TITLE
Game does not launch-- black screen (in window) briefly and exits

### ISSUE THREAD

**Issue by ClayLaMothe** [Mr-Wiseguy/Zelda64Recomp#25]
**Describe the bug**
The launcher is just closing after I have finished providing a Majora's Mask ROM file. The repository calls out the original US version of the game, but no SHA hash or anything like that, so I have no idea if I am using the correct ROM with it not launching like this. I went into C:\Users\xxxx\AppData\Local\Zelda64Recompiled and deleted the .z64 file/assets and tried again with both a .z64 and .n64 version of the ROM, still no luck.

**To Reproduce**
1. Select ROM and launch game

**Expected behavior**
The game should launch.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.0
 - CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz, 3600 Mhz, 6 Core(s), 6 Logical Processor(s)
 - GPU: NVIDIA GeForce RTX 2080 Ti

**Additional context**
N/A

**Comment by Mr-Wiseguy** [comment]
Thanks for the bug report. If you didn't get an error when providing a ROM then you gave it the correct one. This project accepts n64, z64, and even v64 formats and automatically handles all 3. It also checks the version for you and will tell you if you provided the wrong revision or region.

Would you be able to provide a crash dump? I can link a guide on how to enable those if needed.

**Comment by ClayLaMothe** [comment]
Hello Mr-Wiseguy and thanks for the speedy intel. A guide would be appreciated, I am struggling to figure out how to find resources on this myself.

**Comment by Megamixshs** [comment]
I'm having the same problem. If you provide the guide, I can copy my crash dump as well if it helps.

**Comment by Mr-Wiseguy** [comment]
To enable crash dumps, follow the guide by Microsoft here: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
I also suggest making sure your graphics drivers are fully up to date, as out of date graphics drivers can cause crashes especially once the game starts.

**Comment by pamchiis** [comment]
I can confirm I had the same issue and updating my nvidia graphics drivers solved it for me!

**Comment by Megamixshs** [comment]
Turns out it was the graphics drivers. Didn't thought it was that much time since I last updated. But hey, guess it was time enough to not work with the recomp.

Thanks!

**Comment by ClayLaMothe** [comment]
Following up to confirm that updating my graphics drivers resolved the issue. Looks like this issue can be closed, thanks everyone.

**Comment by Tommmahawk** [comment]
I'm having this exact issue. I updated my graphics card but that didn't solve it. 

I believe I attempted to use a Majora's Mask Redux ROM during the initial set up and now can't figure out how to select the correct ROM cause the application only allows me to "start Game" before crashing. 

How do I change the ROM the application is trying to play?
