### ISSUE TITLE
Some game logic (clock and maybe schedule) seems to run (significantly) too fast

### ISSUE THREAD

**Issue by LoZander** [Mr-Wiseguy/Zelda64Recomp#251]
**Describe the bug**
Comparing the clock of this to that of the Switch Online version, I could see that of the former went a bit less than twice as fast as the latter. I haven't compared it against emulation or the original game though. To check if general game logic went faster, I tried running with deku link the same distance, and it took about the same time. So it's clearly not all aspects of the game logic that runs too fast. But it seems that at the very least the clock (and thus presumably the schedule all together) runs significantly faster. It might also be that the Switch Online emulation is actually too slow. I haven't tested against other releases.

**Desktop**
 - OS: Linux, Fedora 40
 - Version: 1.0.1
 - CPU: Intel Core i7-14700KF
 - GPU: NVIDIA GeForce RTX 4070 SUPER

**Comment by Reonu** [comment]
Hello, thanks for the issue report.

However, you're getting confused because the first cycle is always way faster (66%) than any subsequent cycles. That's how the vanilla game works, nothing is running too fast. You can check it yourself by comparing it to the NSO version after you complete the first cycle in Recomp, or comparing the first cycle in both versions.

**Comment by LoZander** [comment]
> Hello, thanks for the issue report.
> 
> However, you're getting confused because the first cycle is always way faster (66%) than any subsequent cycles. That's how the vanilla game works, nothing is running too fast. You can check it yourself by comparing it to the NSO version after you complete the first cycle in Recomp, or comparing the first cycle in both versions.

Oh, I see. My bad. Ofc. you're right. I actually had never noticed that the first cycle is faster before. I'm sorry for the false alarm. Awesome work on the project btw :D

**Comment by Reonu** [comment]
Thank you, we appreciate the intention nonetheless :)
