### ISSUE TITLE
Booting Issue

### ISSUE THREAD

**Issue by camkielty97** [Mr-Wiseguy/Zelda64Recomp#253]
<img width="708" alt="Zelda error" src="https://github.com/Zelda64Recomp/Zelda64Recomp/assets/170693654/f1fb744c-9035-4ca4-a572-3208dc94956c">

When I try and boot it launches with a black window for a second and then it goes away. Event viewer says its an issues with a "d3d10warp.dll" file in System32. Any help would be appreciated! 

 - OS: Windows 10
 - Macbook Pro 15 inch 2017
 - CPU: Intel Core i7 7820HQ
 - GPU: Radeon 560

**Comment by Mr-Wiseguy** [comment]
I noticed you're running Windows on a Macbook, are you using some sort of virtualization? Based on the fact that it's trying to use d3d10warp.dll (a software renderer), I don't think the GPU is being passed through fully or at all. I would confirm that you have D3D12 available in the Windows environment, and if that's not possible then the only option may unfortunately be waiting for this project to get MacOS support (which is planned once the renderer gets a Metal backend).

**Comment by camkielty97** [comment]
> I noticed you're running Windows on a Macbook, are you using some sort of virtualization? Based on the fact that it's trying to use d3d10warp.dll (a software renderer), I don't think the GPU is being passed through fully or at all. I would confirm that you have D3D12 available in the Windows environment, and if that's not possible then the only option may unfortunately be waiting for this project to get MacOS support (which is planned once the renderer gets a Metal backend).

I got it to work. The GPU driver was not up to date. It seems to be working so far! I am running Windows on boot camp. 
![IMG_0933](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/170693654/21f55a4d-f52f-4d0d-94f2-a843d23fdf7c)

**Comment by Mr-Wiseguy** [comment]
Glad to hear you got it working, enjoy playing!

**Comment by camkielty97** [comment]
> Glad to hear you got it working, enjoy playing!

Thanks for your help.
