### ISSUE TITLE
[BUG/CRASH] Crash on boot up of the Zelda64Recompiled.exe

### ISSUE THREAD

**Issue by MegaFaresX** [Mr-Wiseguy/Zelda64Recomp#256]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
when opening the game it does nothing and crashes
**To Reproduce**
1. Open the Zelda64Recompiled exe file

**Expected behavior**
the game "launcher" thing to open then you select you're rom and play

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/83421889/2fca2396-5618-47d1-bb77-07ef8e4f7b40)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC
 - Version: 1.0.1 and 1.0.0
 - CPU: Intel Core I3 8100
 - GPU: Intel UHD 630 (integrated graphics

**Additional context**

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. What version of Win 10 LTSC are you on, and do you get any error popup on version 1.0.1? Also, are your graphics drivers up to date?

**Comment by MegaFaresX** [comment]
wait no

**Comment by MegaFaresX** [comment]
Driver version 26.20.100.7642
LTSC 2021

**Comment by Reonu** [comment]
Hi. Your GPU driver is severely out of date, it's from 2020.

As stated in the readme's system requirements, the first thing you should try if you have crashes at startup is to check if your GPU drivers are up to date.

[Here](https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html)'s the latest version of your GPU's drivers.

Please try updating them and report back.

**Comment by MegaFaresX** [comment]
Will do I only downgraded drivers because the newers ones sometimes don't work with Vulcan and sometimes doesn't

**Comment by MegaFaresX** [comment]
ok now it works Thanks so much I really love yall! ❤️

**Comment by Mr-Wiseguy** [comment]
Glad you were able to get it working.
