### ISSUE TITLE
BUILDING.md typo? at line 78

### ISSUE THREAD

**Issue by TriRetr0** [Mr-Wiseguy/Zelda64Recomp#258]
**Describe the bug**
It appears that there is an error in BUILDING.md at line 78

```bash
cmake --build build-cmake --target Zelda64Recompiled -j$(nproc) --config Release # or Debug
```

instead of :

```bash
cmake --build cmake-build --target Zelda64Recompiled -j$(nproc) --config Release # or Debug
```

**To Reproduce**
1. Follow the instructions
2. Get : "Error: " ... /build-cmake" is not a directory" / "Error: could not load cache"

**Expected behavior**
It should build as expected

**Desktop (please complete the following information):**
 - OS: [Pop Os 22.04]
 - Version: [e.g. 1.0.1]

I haven't been able to get a working version yet, it's always throwing me error on build (and the already built binary gives segmented fault). I'll do another issue for those later

**Comment by dcvz** [comment]
Thanks for the report! This was fixed in https://github.com/Zelda64Recomp/Zelda64Recomp/pull/205

**Comment by TriRetr0** [comment]
My fault :)
