### ISSUE TITLE
Unable to map Right C on Switch N64 controller

### ISSUE THREAD

**Issue by DrakenStark** [Mr-Wiseguy/Zelda64Recomp#261]
Right C on the Switch N64 controller by default acts as the select button on a regular controller. Due to this, Right C cannot be mapped to.

To work around this issue entirely, please allow the Recomp Menu to be remapped on controllers and add Select as a map-able button.

**Comment by Drihscol** [comment]
Known issue, current workaround is to launch through steam and remap C right using steaminput

**Comment by Mr-Wiseguy** [comment]
Duplicate of https://github.com/Zelda64Recomp/Zelda64Recomp/issues/41
