### ISSUE TITLE
Crash on startup, within a second

### ISSUE THREAD

**Issue by DugbyJones** [Mr-Wiseguy/Zelda64Recomp#265]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
The application crashes after it pops up a black/blank windowed window. 

**To Reproduce**
1. Attempt to start the program
2. Crashes within a second

**Expected behavior**
As it works on my Windows installation, the first thing would be to bring me to the home menu where it asks for a Rom and allows play after that.

**Screenshots**
![Screenshot from 2024-05-25 14-52-22](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/162916166/81d56fc2-b1c1-41a0-9e3f-0691872058e8)

![Screenshot from 2024-05-25 14-55-47](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/162916166/270d05ef-9105-4014-b9e9-28448f0858fb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 22.04.4 LTS x86_64
 - CPU: Ryzen 7 3700
 - GPU: Nvidia GeForce GTX 1660 Ti

**Additional context**
Runs great on windows, and I've attempted to upgrade and downgrade my graphics drivers.

**Comment by qurious-pixel** [comment]
Does the same thing happen when selecting an AppImage artifact?

These are from the "actions" tab

![Z64 Artifacts](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/62252937/d561d46e-5d6c-4bad-9777-43b81bbc0f9d)

**Comment by DugbyJones** [comment]
That would work perfectly!
Sheesh I feel silly for not having looked for an Appimage.

Thank you!
