### ISSUE TITLE
Audio is sounds crackled and sped up

### ISSUE THREAD

**Issue by EtzelKlobb** [Mr-Wiseguy/Zelda64Recomp#269]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**Describe the bug**
Upon starting the game, the audio becomes crackled and sped up.

**To Reproduce**
1. Go to Start Game. 

**Expected behavior**
The audio should sound crisp and proper.

**Screenshots**
https://youtu.be/g2NKUFFWuFI

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 22H2
 - CPU: Intel Core 12th Gen i7-12700KF 3.60GHz
 - GPU: NVIDIA GeForce 3060Ti
**Additional context**
I have ran my Majora's Mask rom through Mupen64 and Project64 and it had worked just fine with no audio issues. The moment I ran it through the recompiler, it would become crackled and sped up.

**Comment by Mr-Wiseguy** [comment]
This is probably a duplicate of #22, does the solution [here](https://github.com/Zelda64Recomp/Zelda64Recomp/issues/22#issuecomment-2120517612) work for you?

**Comment by EtzelKlobb** [comment]
Just read the thread and it fixed the audio from the user MissBoobarella. Much appreciated for the link Mr-Wiseguy. I was looking through the Issues and I must have glanced over it. Thank you very much!
