### ISSUE TITLE
[Feature request] add color correction from old color spaces like Dolphin

### ISSUE THREAD

**Issue by Filoppi** [Mr-Wiseguy/Zelda64Recomp#270]
See [https://github.com/dolphin-emu/dolphin/pull/11850](https://github.com/dolphin-emu/dolphin/pull/11850).
My guess is that Majora's Mask was developed on CRT TVs that followed the NTSC-M standard, with a gamma of about ~2.35. For the game to look as it was meant to in 2000, but on 2024 displays, gamma should be adjusted to ~2.2 and the color space from NTSC-J to Rec.709/sRGB.
*I have no proof of this, I have no insight on the game's development process, but it should be a solid guess.

**Comment by Mr-Wiseguy** [comment]
Majora's Mask disables hardware gamma correction entirely, as is the case with the vast majority of N64 games. Additionally, this would be a feature in the renderer, so it makes more sense to open the issue in [RT64](https://github.com/rt64/rt64).
With that said, do you have any comparisons in mind that lead you to believe that there's a gamma curve that needs to be applied?

**Comment by Filoppi** [comment]
The N64 HW gamma correction isn't relevant here.
Games back then didn't have a concept of linear space or gamma space colors, they just rendered "hardcoded" in gamma space, and then the TV would interpret that gamma encoded signal with a specific power function to linearize the color and display it.
On average TVs back then used a gamma of 2.35, while new TVs and Monitors average to 2.2.
For the game to look with the correct level of brightness it was meant for, the output need to be corrected with this formula:
```
// "nonGammaCorrectedOutputColor" is the game's SDR rgb output in a 0 to 1 range.
float3 linearOutputColor= pow(nonGammaCorrectedOutputColor, 2.4f);
float3 gammaCorrectedOutputColor= pow(linearOutputColor, 1.f / 2.2f);
return gammaCorrectedOutputColor;
```

Generally speaking, it's a bit sad that nobody is acknowledging that old TVs used different color spaces and gammas when remastering games (like, even Nintendo etc etc). Dolphin and RetroARCH I think are the only emulators to support that.

And yes I can move the ticket if you wish so :).
I can also help with this feature if you greenlight it, I've already added it to dolphin and I have knowledge of color spaces, gamma and swapchain formats and all of that.

Edit: see here https://dolphin-emu.org/blog/2023/08/13/dolphin-progress-report-may-june-and-july-2023/#50-19716-support-accurate-ntscpal-color-spaces-by-filoppi

**Comment by Mr-Wiseguy** [comment]
Ah, that's very interesting and makes sense. In any case it would definitely be best to move the ticket to RT64 since that's where the VI shader is (which is where you'd place tonemapping like this), which also means it's more of a question for Darío as far as greenlighting is concerned.

**Comment by Filoppi** [comment]
Moved here [https://github.com/rt64/rt64/issues/36](https://github.com/rt64/rt64/issues/36)
