### ISSUE TITLE
Sword disappears from green button and is unusable

### ISSUE THREAD

**Issue by R4mb4Z4mb4** [Mr-Wiseguy/Zelda64Recomp#274]
Happens randomly, and usually goes back to normal once you play song of time. 

Right now it happened again once I was riding Epona and then got off from it. 

https://imgur.com/kOlkYSt

Windows 11
i5 13400
rx 570

**Comment by Reonu** [comment]
Hello, thanks for the report.

I don't know how to say this, but I think your sword was stolen. Like, by a bird that roams around Termina Field and steals your sword, which is a vanilla mechanic. 

It can catch you out of guard if you aren't expecting it. 

If you go to the Curiosity Shop at night, you should be able to get your sword back.

can you confirm that this is the case?

Thanks.

**Comment by R4mb4Z4mb4** [comment]
> Hello, thanks for the report.
> 
> I don't know how to say this, but I think your sword was stolen. Like, by a bird that roams around Termina Field and steals your sword, which is a vanilla mechanic.
> 
> It can catch you out of guard if you aren't expecting it.
> 
> If you go to the Curiosity Shop at night, you should be able to get your sword back.
> 
> can you confirm that this is the case?
> 
> Thanks.

lol ... wasn't stolen but would be funny. I don't remember the bird actually being able to steal your sword as well. However, the sword is still in the menu and it has nothing to do with what you described, at all.

So no, I can not confirm this.

It happned a few times already. Just now it happened when I got on the horse at the great bay. 

Sword is there.
Get on horse, ride 2 meters.
Get off.
Sword gone from green button, but still in menu. 

Maybe it would help if I reproduce these steps with the horse, after resetting time to day 1, and then send you the log?

**Comment by Reonu** [comment]
Can you share your save file?

**Comment by R4mb4Z4mb4** [comment]
Will do. Give me a second, because I also just recorded a video to demonstrate the problem. Gonna upload it now.

**Comment by R4mb4Z4mb4** [comment]
https://drive.google.com/file/d/1kBFQzTSjp7APPnEocLt_IGnGgr1qg0oV/view?usp=sharing

Here is a demonstration.

As for the save file: I actually don't wanna do that, sorry. Because I can't see for myself how many personal information is stored in this save file and seeing how everything has unfolded with Nintendo, I don't feel good doing that.

Maybe there is none in it anyway? But I can't evne open these files to see for myself.

If this means you can't help, fair enough. But maybe someone else finds a solution at some point. I just wanted to "report" the problem.

**Comment by thecozies** [comment]
> https://drive.google.com/file/d/1kBFQzTSjp7APPnEocLt_IGnGgr1qg0oV/view?usp=drive_link
> 
> Here is a demonstration.
> 
> As for the save file: I actually don't wanna do that, sorry. Because I can't see for myself how many personal information is stored in this save file and seeing how everything has unfolded with Nintendo, I don't feel good doing that.
> 
> Maybe there is none in it anyway? But I can't evne open these files to see for myself.
> 
> If this means you can't help, fair enough. But maybe someone else finds a solution at some point. I just wanted to "report" the problem.

Could you set the video to be viewable by link? We can't access it at the moment.

**Comment by R4mb4Z4mb4** [comment]
Oops, my bad. Link updated!

But here it is again: https://drive.google.com/file/d/1kBFQzTSjp7APPnEocLt_IGnGgr1qg0oV/view?usp=sharing

**Comment by Reonu** [comment]
We can only guess, but this looks like your savefile got somehow corrupted. We expect it's some state that got set incorrectly on the save file. But, indeed, there is nothing we can do to confirm if you are not willing to send it here.

The savefile does not contain any sort of personal information. It's the exact same data that an emulator or even an N64 flashcart would generate. That being said, if you don't want to send it, then no pressure. But it does mean that we can't help further.

**Comment by thecozies** [comment]
@R4mb4Z4mb4 hmm did you somehow get hookshot before bow?

**Comment by R4mb4Z4mb4** [comment]
@thecozies Yeah...and not just that. 

I was just editing my comment above but you two guys came before me...so I make a new comment with what I just wrote, which was this:

While uploading it, it just came into my mind that maybe all that has something to do with the fact, that I glitched myself through almost everything in this game, to get all transformation masks without doing a temple.

I also bomb hovered myself over the big rock blocking the entrance to the ranch, even though I already had the Goron Mask. And this also means that I don't have a bow!

Normally you can get Epona only once you finished the first two temples, which means you already have a bow as well.

And I guess, maybe the fact that the game can't equip the bow to the green button when Im on the horse, causes some unforseen consquences.  

so @Reonu maybe the save file is not really corrupted, but the project can't handle having no bow and riding the horse, which is not the way it's inteneded. However, on original hardware it doesn't cause these problems, even if you glitched yourself to the state of getting Epona.

**Comment by Reonu** [comment]
Hello.

I just reproduced this bug on real N64 hardware. It occurs when you ride Epona without a bow.

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/39a73e58-404c-4120-9795-2b2b9f452df5

Fixing vanilla issues is out of the scope of this project and is better suited for a mod when mod support comes.

To add to this, we kindly ask that you refrain from reporting issues that occur from heavily glitched playthroughs without first confirming whether the issue also occurs in the original game (and especially, do not state that it doesn't occur on original hardware without actually checking). The time spent on confirming false alarms like this one is time that we could spend improving the project instead.

Thank you.

**Comment by R4mb4Z4mb4** [comment]
> Hello.
> 
> I just reproduced this bug on real N64 hardware. It occurs when you ride Epona without a bow.
> 
>  2024-05-26.21-15-28.mp4 
> Fixing vanilla issues is out of the scope of this project and is better suited for a mod when mod support comes.
> 
> To add to this, we kindly ask that you refrain from reporting issues that occur from heavily glitched playthroughs without first confirming whether the issue also occurs in the original game (and especially, do not state that it doesn't occur on original hardware without actually checking). The time spent on confirming false alarms like this one is time that we could spend improving the project instead.
> 
> Thank you.

Oh wow. Yeah, that were two mistakes on my side then. Sorry!

But as for you now making a big drama out of that, like an unsatisifed housewife: Chill bro, no need to cry.

Those 2 minutes of watching a video and reading 2 comments won't hurt you, and if it does, then you need to manage your time better in general. Or just watch less anime today then, to compensate. 

Anyways, thanks for the help sweehearts.

💋
