### ISSUE TITLE
"Aiming Camera Mode" should affect shield/sword aiming with R

### ISSUE THREAD

**Issue by Reonu** [Mr-Wiseguy/Zelda64Recomp#277]
Right now, shield aiming is Y-inverted and X-normal no matter what. Instead, it should follow the "Aiming Camera Mode" setting.

**Comment by Bordraw** [comment]
It would also be good if the shield could use gyro aiming like in the 3ds port: #194

**Comment by Reonu** [comment]
> It would also be good if the shield could use gyro aiming like in the 3ds port: #194

Certainly, but that's way more complicated and beyond my skillset, and Wiseguy is busy with more important changes, so for now the PR I just opened will do.

PRs welcome though :)
