### ISSUE TITLE
Issues with Xbox One controller

### ISSUE THREAD

**Issue by AbelSAnderson** [Mr-Wiseguy/Zelda64Recomp#282]
**Describe the bug**
I've encountered some issues when using a Xbox One Controller to play Majora's Mask.

1. The game seems to have some trouble disabling the mouse while using the xbox one controller.
    - For example, if I move the right stick at all while playing, it will move the mouse across the screen outside of the playable area, even if it is full screen. Pressing buttons while the cursor is elsewhere on your desktop can cause menus to pop-up, applications to open, etc.

2. The left stick seems to have multiple actions bound to it.
    - Pressing up on the left stick will move the camera into first person mode / forward conversations (extremely annoying when trying to walk)
    - Pressing any of the other directions seems to use the items slots (I only tested the right slot, but I assume the other slots would be triggered as well).
    - When navigating around the menus with the left stick, it selects every other option when going up and down / left and right.
    - Besides these issues, the character seems to walk around normally. Exiting first person mode while holding down up allows the character to walk forward, and the other directions function as normal unless an item is equipped.

There may be some other issues, but I haven't tested further.

**Addendum**
Trying to play the game while focused in a text field (such as the text field I am writing in now) causes the left stick to work as expected (no zoom issues, items are not used, and menu navigation is normal). However it still suffers the same issues as in my first point.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.1.0
 - CPU: Intel Core i7 10700F
 - GPU: NVIDIA GeForce RTX 2060

**Comment by Reonu** [comment]
You probably have Steam open, and a desktop mapping configured. This means that Recomp is seeing gamepad presses and keyboard presses at the same time. This isn't something we can fix on our end.

Your options are:
- Close Steam before playing the game
- Disable Steam Input
- Set a game template as your desktop binding on Steam
- Add Zelda 64: Recompiled to your Steam Library as a non-stean game and launch it through Steam

Please confirm that this is indeed the problem so that we can close the issue.

**Comment by AbelSAnderson** [comment]
That does seem to be the issue, thank you for your quick response.

**Comment by Reonu** [comment]
Glad to help!
