### ISSUE TITLE
Pot breaking SFX corrupted 

### ISSUE THREAD

**Issue by Emerllad12** [Mr-Wiseguy/Zelda64Recomp#287]
**Describe the bug**
Breaking the Pots in game seems to not play out the SFX correctly or it cuts off abruptly. As if it was corrupted. 

**To Reproduce**
Go to Zora Cape and break the pots next to the owl statue. 

**Expected behavior**
The Clear SFX triggers when breaking the pot. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.0
 - CPU: Intel Core i9-10920X
 - GPU: NVIDIA GEFORCE 2060

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. As shown in this N64 console captured footage (timestamped URL), this is an issue in the original game: https://youtu.be/iNjX7UzRQyU?t=32547.

Fixing vanilla issues like this is outside of the scope of the base project, but would be well suited to being a mod when mod support is released.
