### ISSUE TITLE
Does this user interpolation?

### ISSUE THREAD

**Issue by ryzendew** [Mr-Wiseguy/Zelda64Recomp#29]
I am very sensitive to interpretation. It literally makes me sick. I was wondering if this used interpretation or if it was real frames per second. There’s a huge difference if this is actual 60 FPS+ I’m all in.

**Comment by FoxbitDreamtail** [comment]
I think it's a mix, the internal logic runs at 20 FPS but the engine interpolates the internal logic and then renders it at whatever frame rate you wanted to run at, at least that's my understanding of how it works.

**Comment by Mr-Wiseguy** [comment]
This project uses the same approach that every modern game engine uses (Unity, Godot, etc.), so if you can play games made with those engines you should be fine here. The underlying transform data (positions, rotations) are interpolated, but the actual frames that are rendered are all real. There is no frame generation being used like FSR or DLSS framegen. If you do have trouble with the high framerates, then you can use the original framerate option in the graphics settings.

**Comment by ryzendew** [comment]
i gave it a try and got sickness but 20fps felt great i will wait for a another project with true 60+ thanks for making this none the less. Edit also hearing someone call unity a modern engine and godot gave me a laugh lol.

crap made people salty .. oh well
