### ISSUE TITLE
Version 1.1 does not launch the game

### ISSUE THREAD

**Issue by puddoparty** [Mr-Wiseguy/Zelda64Recomp#295]
**Describe the bug**

**To Reproduce**
1. Initially overwrote the v1.0 files with v1.1, was able to open to the launcher but when pressing "Start game" it goes to black before closing
2. I deleted all files from the folder and extracted v1.1 again, same issue
3. I deleted the entire folder and re-extracted to a new folder, same issue
4. I deleted the folder and re-extracted v1.0, and v1.0 works fine just as before and picks up my save

**Expected behavior**
Expectation is that v1.1 would launch the same as 1.0. Sorry if I'm doing something wrong here I'm new to this kind of thing

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2
 - CPU: Intel Core i9-10850K
 - GPU: NVIDIA GeForce RTX 4070 Ti

**Additional context**
Graphics drivers are up to date

**Comment by Reonu** [comment]
Hello. This is likely a known bug with older Nvidia drivers: they seem to crash when dealing with a 64-bit framebuffer, which Recomp uses as per version 1.1 to be able to render the motion blur effect correctly at high framerates.

I know you said your graphics drivers are up to date, but this seems unlikely. Check your driver version. Latest is 555.85.

Please install the latest driver for your GPU ( [here](https://www.nvidia.com/Download/driverResults.aspx/224750/en-us/) ) and report back.

Thanks!

**Comment by puddoparty** [comment]
I re-installed graphics drivers from scratch and that solved it, thank you
