### ISSUE TITLE
Cant use anything besides the camera item

### ISSUE THREAD

**Issue by GamesOnAcidzz** [Mr-Wiseguy/Zelda64Recomp#296]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes Mesa 24

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**
Yes, just regular playthrough
![Bug](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/103296087/24989027-f3ff-411c-89a4-b38a8061d652)

**Describe the bug**
Cant use or do anything besides rolling, blocking and taking pictures.

**To Reproduce**
Dont know how I did it, I was inside the fortress quit the game and the game was like this

**Expected behavior**

**Screenshots**
Please attach a screenshot of the bug.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: [e.g. 1.0.0]
 - CPU: Ryzen 5700X
 - GPU: Rx 5600 XT
 - GPU driver: Mesa 24

**Additional context**

**Comment by Reonu** [comment]
Hi, can you share your save file here so that we can look into this? Thanks

**Comment by GamesOnAcidzz** [comment]
Letting the 72 hours pass fixed it

**Comment by Reonu** [comment]
Glad to know the issue was resolved, but if you get something like this again please share the savefile so that we can look into it!
