### ISSUE TITLE
Main Menu never launches

### ISSUE THREAD

**Issue by Table-09** [Mr-Wiseguy/Zelda64Recomp#30]
I have Windows 11, GTx 1080, Ryzen 5950X 64GB RAM everything is fully up-to-date etc...

I noticed in the FAQs it mentioned things like steam overlays and wallpaper engine cause stuttering issues so when i couldn't open it I closed those, tried again, made sure nothing was starting on reboot, then rebooted the computer and i still can't get the .exe to open the menu

on my secondary computer, intel core i5-9400 16GB RAM, basic GPU (RTX A2000) and the .exe menu opens instantly no problems

I don't seem to see a log file it creates

The zelda64.exe runs for a minute or so in task manager and then goes away, but no windows pop up

EDIT - I have double checked my nvidia graphics driver and it's the newest one updated yesterday, reinstalled just incase, no difference, I enabled the full dump in regedit but it's not creating any logs

**Comment by Mr-Wiseguy** [comment]
Does the issue still happen on the latest recomp release?

**Comment by Reonu** [comment]
Closing since the user never replied, feel free to re-open if you're still having the issue.
