### ISSUE TITLE
Postman 10 Second challende counts seconds wrong in high framerate mode.

### ISSUE THREAD

**Issue by grimmotron** [Mr-Wiseguy/Zelda64Recomp#301]
Doing the 10 Second counting challenge of the Postman in Clock Town while running the game in higher framerates makes the counter too precise. Running the game in original speed fixes the issue. Can this be fixed while running higher framerates?
While running the game originally it counts seconds in 10 segments. While in 60FPS it counts each second in 99 segments, it seems.
Original: 00.0 seconds.
60FPS: 00.00 seconds. 
This jump in precision makes it basically impossible to win his challenge. Even the textbox show this difference.

**Comment by Mr-Wiseguy** [comment]
What you're describing isn't the case, as framerate settings do not affect gameplay whatsoever. The exact same game code is run regardless of what framerate you set the game to, and it's run the same number of times per second. The code is also unmodified from the original version of the game.

The bunny hood timer is still 1 decimal place and the final time is still 2 decimal places, which are how they both were in the original game. The game displays 2 decimal places, but has a much lower actual resolution for timing the minigame.

Here is footage of me beating the minigame at high framerates (I was using 144FPS at the time), with and without the bunny hood. I'm no expert at this minigame, but it only took me 2 tries without the bunny hood and 3 tries with it.

Without bunny hood:

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/1c670284-c4f3-4a45-b898-2a3572c803e7


With bunny hood:


https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/60649f2e-7627-45ad-8a41-b06f9d8e12d6

**Comment by Reonu** [comment]
To confirm what Wiseguy said, here are two videos of this minigame recorded on real N64 hardware, with and without bunny hood. You can see that the final timer declared by the postman is always 2 digits. 

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/8a4493e1-83a8-42a2-b621-a2e050e7383f

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/20d3df02-e8aa-4d20-871f-d8784acacd6b
