### ISSUE TITLE
[Feature Request] Select items in item menu/play ocarina with the D-pad

### ISSUE THREAD

**Issue by JeffGomezL** [Mr-Wiseguy/Zelda64Recomp#303]
Hi!

Would it be possible to make it so that we can select items in the item menu/play the ocarina using the D-pad instead of the analog stick, without having to remap the controls? 

Thank you.

**Comment by SonicRay100** [comment]
I almost opened a similar feature request after I saw another one close but then I discovered feature request #91. It covers generally expanding D-Pad usage and includes Ocarina notes. So it would be better to close this and support that one :).
