### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by SU-Daigoro** [Mr-Wiseguy/Zelda64Recomp#304]
I managed to get LuaJIT into the project, however i can't really interact with the game at all and it is kind of useless because i couldn't really figure out how to hook it up similar to your debug functions.

I also just noticed this piece of code:
```
std::atomic<uint32_t> pending_set_time = 0xFFFF;
void recomp::set_time(uint8_t day, uint8_t hour, uint8_t minute) {
    pending_set_time.store((day << 16) | (uint16_t(hour) << 8) | minute);
}
extern "C" void recomp_get_pending_set_time(uint8_t* rdram, recomp_context* ctx) {
    // Return the current set time value and reset it.
    _return(ctx, pending_set_time.exchange(0xFFFF));
}
```
I wonder if there is a way to create my own thing like this or even pass the GameState similar to that.

**Comment by Mr-Wiseguy** [comment]
Thanks for the interest in this. I'm actually already in the process of integrating LuaJIT myself as well, though in a different system than you may expect. I'll explain it in more detail once I finish the required changes to the recompiler, but basically it will allow you to write mods by editing functions from the decompilation project and then convert those into Lua automatically. That will make writing mods identical to the process that the patches (in the patches/ folder) were written, but with the ability to load them them from the launcher without needing to distribute a new exe for a given mod.

It'll end up being much easier to work with than having to modify ram contents like you would in an emulator, but I may also expose that functionality as well if people are interested.

**Comment by SU-Daigoro** [comment]
Thanks a lot, this sounds great. Since i am not that experienced with C and not used to deal with big/advanced projects like this, i think i will just give up for now and try to expose stuff like Vec3f, Player, Actor, GameState etc as soon as you publish some sort of Lua implementation.

I worked on some own smaller projects to expose C++ API into Lua and HTML/JS, but never went beyond building on Windows for Windows. Even building this Project took a lot more effort than i would like to admit, but i really wanted to say thank you and keep up that great work. 🙏

**Comment by Bordraw** [comment]
I bounced off of working on this project too since I have very little experience with C, but +1 to Daigoro's sentiment, this project is awesome and you're all doing great work

**Comment by Mr-Wiseguy** [comment]
Closing as this doesn't reflect the plans for how Lua will be integrated, but again I do appreciate the interest.
