### ISSUE TITLE
[Feature Request] Dual Analog Camera Control

### ISSUE THREAD

**Issue by butterbutts** [Mr-Wiseguy/Zelda64Recomp#31]
I won't pretend to know how any of this works but seeing as you've gotten gyro and mouse aiming in first person I assume that full analog camera control like in MM3D or SoH should be a possibility?
I don't know if that would be possible through this program alone or if it would require a romhack like those SM64 hacks that bind the second controllers analog stick to control the camera but analog camera controls are the thing I'm missing the most out of this.

**Comment by Mr-Wiseguy** [comment]
Thanks for the suggestion! Dual analog camera control is already a planned feature. I had a version working before release, but opted not to launch with it since it needed more polish. In fact, you can still see some remnants of the code for the original version I was testing in the patches: https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/b1109f66c16efd7913e816a03c5e7d259a4c6c61/patches/camera_patches.c#L694

**Comment by butterbutts** [comment]
Cool! Great job on everything btw. :)

**Comment by mdsmendes94** [comment]
> Thanks for the suggestion! Dual analog camera control is already a planned feature. I had a version working before release, but opted not to launch with it since it needed more polish. In fact, you can still see some remnants of the code for the original version I was testing in the patches:
> 
> https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/b1109f66c16efd7913e816a03c5e7d259a4c6c61/patches/camera_patches.c#L694

Are you planning on adding camera control with a mouse as well?

**Comment by starkle** [comment]
I hope that when dual analog is implemented, the right stick (or the D-pad) can still be used for Ocarina notes. I like having a directional input for playing Ocarina, instead of memorizing which button goes with each note.

**Comment by Reenuip** [comment]
> Thanks for the suggestion! Dual analog camera control is already a planned feature. I had a version working before release, but opted not to launch with it since it needed more polish. In fact, you can still see some remnants of the code for the original version I was testing in the patches:
> 
> https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/b1109f66c16efd7913e816a03c5e7d259a4c6c61/patches/camera_patches.c#L694

Would there be a way to enable this patch if I were to compile from source, or is this basically broken in the current release?

**Comment by Reonu** [comment]
Added by #264
