### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by matejsmycka** [Mr-Wiseguy/Zelda64Recomp#313]
while following the build tutorial, I have encountered this error:

```
Function count: 17146
Working dir: /home/matej/Desktop/Zelda64Recomp
Failed to to find jump table for `jr $a0` at 0x800B407C in ActorShadow_DrawSquare
Failed to analyze ActorShadow_DrawSquare
Error recompiling ActorShadow_DrawSquare
```

checksums are OK, and all previous steps did compile

**Comment by matejsmycka** [comment]
My bad, I used latest commit instead of `23beee0717364de43ca9a82957cc910cf818de90`.

**Comment by Mr-Wiseguy** [comment]
No worries, one of the planned updates is to simplify the build process to not even need the decomp elf so that'll get simpler in the future.

**Comment by matejsmycka** [comment]
@Mr-Wiseguy  Why is this step needed now? Isnt the compiled ROM same as the original?

**Comment by Mr-Wiseguy** [comment]
The actual recompilation process for the base game doesn't need the decompilation project's elf. It's used for turning functions from the decompilation into the patches (see the patches/ folder for examples). That significantly streamlines the process of modifying the game, to the point where it's not far off from just editing the decompilation directly like you would for making a ROM hack. Games that don't have a decompilation can use a different process for writing patches, but for ones that do (even if the decompilation is incomplete) this allows a lot of flexibility in terms of what can be modified.

**Comment by matejsmycka** [comment]
I see, thanks
