### ISSUE TITLE
Using a Switch controller, I get this weird drift

### ISSUE THREAD

**Issue by RandKaz** [Mr-Wiseguy/Zelda64Recomp#32]
I'm using the PowerA Wireless GameCube controller for Nintendo Switch, and I'm noticing that the left stick is very, very sensitive. This controller has no issues in other games, platforms, and I even tested it. I think this may be a bug.
**To Reproduce**
1. Map movement control to left stick in PowerA GameCube controller
2. A slight move up will move Link up but then down

**Additional context**
The game runs fine with a Dualsense Edge and a Switch Pro Controller, it's with this controller specifically I'm seeing the issue. But again, this controller doesn't have this behavior in other platforms/games. 

Just letting you know.

Also thank you for all your hard work!

**Comment by Mr-Wiseguy** [comment]
The next version will include a deadzone adjustment setting, so hopefully that will let you fix the issue.

**Comment by Mr-Wiseguy** [comment]
Closing as a deadzone setting has been added. Feel free to reopen if the deadzone option doesn't resolve this issue.
