### ISSUE TITLE
Update rate issues (or something like that)

### ISSUE THREAD

**Issue by SU-Daigoro** [Mr-Wiseguy/Zelda64Recomp#320]
Heya, so i have this function to convert an actor position into screen coordinates and display the actor name on screen.
```
				s16 x = 0;
				s16 y = 0;
				if (closestNpc->projectedW > 0) {
					Actor_GetScreenPos(playState, closestNpc, &x, &y);
					daigoro_add_print_px(playState, GetActorName(closestNpc->id), x, y);
				}
```
When testing this, i realized that the screen position is being updated in the original fps, which looks very stuttery since the game itself runs in far more fps than the screen position update. I am not sure if this is a bug or not tho, but i think it might be worth being mentioned.

**Comment by Bordraw** [comment]
Pretty sure that's WAI. If I understand correctly, the game logic runs at the original framerate and the higher FPS rendering is done by RT64 separately with some kind of interpolation.

**Comment by SU-Daigoro** [comment]
Oh, i just reread this. You are totally right.

> Play at any framerate you want thanks to functionality provided by RT64! Game objects and terrain, texture scrolling, screen effects, and most HUD elements are all rendered at high framerates. By default, this project is configured to run at your monitor's refresh rate. You can also play at the original framerate of the game if you prefer. Changing framerate has no effect on gameplay.

**Comment by Bordraw** [comment]
If you are running into a graphical issue with something you're working on, I think there is a way to tag the visuals for rt64 so it interpolates them properly, but I don't know the specifics.
