### ISSUE TITLE
Steam controller gyro aim support

### ISSUE THREAD

**Issue by miropaananen** [Mr-Wiseguy/Zelda64Recomp#325]
For some reason steam controlers gyro aim doesn't work while running this project on steam deck. I haven't tested on windows.

**Comment by Krutonium** [comment]
You have to configure Steam to treat the Gyro as a Mouse, and set it to be always active. The game will interpret mouse movement as Gyro input. It works quite well! (Though I wouldn't mind it if the devs added DSU support for direct gyro input from other sources.)

**Comment by Reonu** [comment]
As the comment above describes, this is already supported, you're meant to enable "Gyro as mouse" on Steam to use Gyro on the Deck.

There is no way for non-Steam games to access the gyro sensor data on the Deck directly.

**Comment by Krutonium** [comment]
> There is no way for non-Steam games to access the gyro sensor data on the Deck directly.

There actually is! https://github.com/kmicki/SteamDeckGyroDSU

It was originally for CemuHook but there's implementations for other things like Steam Controllers and other Gryo based controllers that all use this protocol.

**Comment by Reonu** [comment]
Sure, but there is no need. There is no practical advantage to using this, and asking players to install this is way more involved of a request than asking them to enable the built-in "gyro as mouse" feature, which will work just as well. That tool is also way more hacky than using the Deck's built-in feature.

The main use for SteamDeckGyroDSU is being able to properly 1:1 map the gyro data from the controller to the gyro data of an emulated controller, for example, on a Wii U emulator. There's no need to use this here.

**Comment by Reonu** [comment]
Oh, and to be clear, this project already supports direct gyro input from Switch Pro controllers, DualShock controllers, etc, via SDL. 

It's not that we don't support direct gyro input, we do, it's just that the Steam Deck won't expose its internal gyro data for us.
