### ISSUE TITLE
[Original Bug] Sounds in the Swamp Shooting Gallery are Swapped

### ISSUE THREAD

**Issue by Krutonium** [Mr-Wiseguy/Zelda64Recomp#326]
**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

No Glitches

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
Yes

**Describe the bug**
While playing the swamp shooting gallery, a lot of the monster sounds will come from the wrong side - Wolves spawning on the left will howl from the right, and birds spawning from the right will chirp on the left, for example.

**To Reproduce**
1. Play the swamp shooting gallery
2. Wearing Headphones.

**Expected behavior**
The sounds should come from the correct direction.

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Version: 1.1.0
 - CPU: Ryzen 7 5800X3D
 - GPU: nVidia RTX 3070
 - GPU driver: nVidia 555.42.02 (This is the latest Linux driver release)

**Additional context**
This bug also occurs on hardware, with my N64 & Cartridge.

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. As this is a bug in the original game like you mentioned, fixing it is more suited for a mod once mod support is added, since this project aims to preserve original bugs when reasonably possible.
