### ISSUE TITLE
[Bug] Gryo Aim doesn't work when shooting from Horse during Lon Lon Tutorial

### ISSUE THREAD

**Issue by Krutonium** [Mr-Wiseguy/Zelda64Recomp#327]
**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
N/A

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**
No Glitches

**Describe the bug**
When riding the horse, trying to aim the bow using Gyro Input does not work, but only during the first day tutorial where you're being taught how to ride the horse while shooting the "ghosts" that Romani has set up.

**To Reproduce**
1. Begin the "Tutorial" bit of the questline
2. Try to use Gyro from Horseback to shoot.

**Expected behavior**
Ideally, the Gyro would work.

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Version: 1.1.0
 - CPU: Ryzen 7 5800X3D
 - GPU: nVidia RTX 3070
 - GPU driver: nVidia 555.42.02

**Additional context**
So far it seems to work everywhere else.

**Comment by Reonu** [comment]
Hello, this is not the case.

Here's a video of me using both gyro aiming and mouse aiming while in this part of the game:

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/564a070a-d2c9-49de-b94d-b2cc11c1e6be

I'm on Linux, just like you. I've also confirmed that it works on the Steam Deck and on Windows.

Are you sure you don't have something wrong with your setup? Can you try again?

I'll reopen the issue if you can provide footage of the gyro aiming working outside of the training mini-game, and then not working anymore once you start the minigame.

Thanks.

**Comment by Krutonium** [comment]
Will do! (Also, Weird!)
