### ISSUE TITLE
Cannot tell aim direction when inside deku flower when using analog camera

### ISSUE THREAD

**Issue by halcyonhippo** [Mr-Wiseguy/Zelda64Recomp#331]
When diving into a flower as a deku scrub and the analog camera is enabled, it is impossible to tell which direction link is aimed within the flower since the camera does not lock to his direction. 

**To Reproduce**
1. Enable analog camera and use right stick at least once to "unlock" the camera.
2. Dive into a flower as Deku Link.
3. Try to aim Link using left analog stick.
4. Notice camera raises up at start of dive, but does not follow spin performed by left analog stick.

**Expected behavior**
Right stick analog camera should fully disable and revert to original design, following input made by the left analog stick. Ideally it would "unlock" as soon as you pop out of the flower but before it does the weird 45-degree pivot around Link.

**System Detail**
OS: Fedora Linux 39 (Workstation Edition) x86_64 
Kernel: 6.8.10-200.fc39.x86_64
CPU: AMD Ryzen 7 5800X3D (16) @ 4.550GHz 
GPU: AMD ATI Radeon RX6700 XT
Memory: 7901MiB / 31990MiB 

**Additional context**
Game version: v1.1.0 AppImage

**Comment by Reonu** [comment]
This is already fixed by #306 , the update just isn't out yet. You can download the artifact if you really want the fix now.
