### ISSUE TITLE
[Feature Request] 24-hour clock 

### ISSUE THREAD

**Issue by mwinding** [Mr-Wiseguy/Zelda64Recomp#333]
It would be nice to modify the current clock in the UI at the bottom of the screen with a 24-hour clock, like the option in 2ship. I was never a big fan of the sun and moon representing AM and PM

**Comment by Reonu** [comment]
Hi! Thanks for the suggestion.

This is outside of the scope of the project, but it would be a great candidate for a mod when mod support comes.

**Comment by mwinding** [comment]
Fair enough, thanks!
