### ISSUE TITLE
Crashes on startup (Windows 10 LTSC X64)

### ISSUE THREAD

**Issue by Kippykip** [Mr-Wiseguy/Zelda64Recomp#34]
Double clicking the executable (with or without a n64 rom present) on my main Windows 10 LTSC X64 build just crashes
![image_2024-05-11_130529845](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/33023808/f1e4fd5c-a1f9-4c4b-846d-cf5af43897ac)

If there's a specific filepath I need to name the rom, let me know.
GPU: GeForce 1060 6GB
CPU: AMD Ryzen 3600X

**Comment by hazemimam** [comment]
im having same issue im also windows 10

**Comment by Ammako** [comment]
Not enough info. 2019? 2021? 1809 may be too old but 21H2 works

**Comment by Kippykip** [comment]
> Not enough info. 2019? 2021? 1809 may be too old but 21H2 works

Version	10.0.17763 Build 17763

**Comment by Ammako** [comment]
If you don't have a reason for staying on 2019, I would upgrade to 2021. Windows 10 1809 lacks some features and APIs or whatever that newer games sometimes rely on. You can do an in-place upgrade.

Though it's still possible there could be another reason why it's crashing, and upgrading might not necessarily fix it. If you have a spare drive or something you could test LTSC 2021 on first to see if the game works, that would be a good idea. You could re-test a fresh install of 2019 on the same hardware too at the same time.

but also, before you do all that, it might be worth checking application logs in event viewer (Windows Logs --> Application), look for Error down the list and find the ones that refer to Zelda64Recompiled. It may at least give more information about why the crash is happening and could help figure out if it's something that can be fixed, or if this is some kind of Windows 10 1809 incompatibility.

**Comment by Darthagnon** [comment]
I'm on Win10 v1709.

I went to `Start >> Administrative Tools >> Event Viewer >> Windows Logs >> Application` and looked for Application Errors. Those for Zelda64Recomp were all as follows:
```
Faulting application name: Zelda64Recompiled.exe, version: 0.0.0.0, time stamp: 0x663da193
Faulting module name: ucrtbase.dll, version: 10.0.16299.820, time stamp: 0xe26f28c3
Exception code: 0xc0000409
Fault offset: 0x000000000006b64e
Faulting process id: 0x46b4
Faulting application start time: 0x01daa3ef73409701
Faulting application path: D:\Users\Darthagnon\Downloads\Zelda Majora's Mask PC Recompiled\Zelda64Recompiled-v1.0.0-Windows\Zelda64Recompiled.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 0e823352-19e5-4a9d-9dfc-c360a46c21ba
Faulting package full name: 
Faulting package-relative application ID: 
```

I tried supplying `ucrtbase.dll` from a newer version of Windows next to the executable, but it did nothing.

**Comment by Kippykip** [comment]
> If you don't have a reason for staying on 2019, I would upgrade to 2021. Windows 10 1809 lacks some features and APIs or whatever that newer games sometimes rely on. You can do an in-place upgrade.
> 
> Though it's still possible there could be another reason why it's crashing, and upgrading might not necessarily fix it. If you have a spare drive or something you could test LTSC 2021 on first to see if the game works, that would be a good idea. You could re-test a fresh install of 2019 on the same hardware too at the same time.
> 
> but also, before you do all that, it might be worth checking application logs in event viewer (Windows Logs --> Application), look for Error down the list and find the ones that refer to Zelda64Recompiled. It may at least give more information about why the crash is happening and could help figure out if it's something that can be fixed, or if this is some kind of Windows 10 1809 incompatibility.

Interesting, legit I only just upgraded from LTSB 2016 a few weeks ago to this version so I could play CS2.
Didn't realise I'm still out of date.

**Comment by Lemonov-S** [comment]
Same issue here, but I'm on 2021 LTSC and it still happens.

**Comment by delibrete** [comment]
I had the same issue, except the application would just close, no warning or anything. I couldn't even get to the main menu. 

I was on Windows 10 1809 LTSC and it wouldn't open. The only way I solved this was by upgrading windows to 1909 (it still wouldn't open), then finally to 22H2. It now works on 22H2.

If you really want LTSC, it _might_ work on 21H2, but I haven't tried this.

**Comment by Ammako** [comment]
Works here on LTSC 2021. One reason I can think for why it might not work is because there are certain libraries LTSC doesn't include by default, because of Store being disabled by default; for instance, emoji picker doesn't work by default because of missing libraries. By installing certain UWP apps they may pull missing dependencies which ends up making other things work. Example: nvidia control panel getting installed made the emoji picker work for me.

If this is the culprit, I don't know exactly which missing library might be the problem here. I may have manually installed a couple libraries a while ago too but I wouldn't remember which ones. I'll share my list of installed packages in a bit, then you can compare and see if there are any you're missing, and if installing them fixes it.

(Also: if there's anything you uninstalled or deactivated compared to the default install, it would be useful to know.)

**Comment by Ammako** [comment]
<details>
  <summary>Packages</summary>

```
PS C:\Windows\system32> Get-AppxPackage -AllUsers | Select PackageFullName

PackageFullName
---------------
c5e2524a-ea46-4f67-841f-6a9465d9d515_10.0.19041.1023_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.SecHealthUI_10.0.19041.1023_neutral__cw5n1h2txyewy
MicrosoftWindows.Client.CBS_120.2212.3920.0_x64__cw5n1h2txyewy
windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy
Windows.PrintDialog_6.2.1.0_neutral_neutral_cw5n1h2txyewy
Microsoft.VCLibs.140.00.UWPDesktop_14.0.33519.0_x64__8wekyb3d8bbwe
Microsoft.VCLibs.140.00.UWPDesktop_14.0.33519.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WindowsSubsystemForLinux_2.1.5.0_x64__8wekyb3d8bbwe
1527c705-839a-4832-9118-54d4Bd6a0c89_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
c5e2524a-ea46-4f67-841f-6a9465d9d515_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
E2A4F912-2574-4A75-9BB0-0D023378592B_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.AAD.BrokerPlugin_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
Microsoft.AccountsControl_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.AsyncTextService_10.0.19041.4239_neutral__8wekyb3d8bbwe
Microsoft.BioEnrollment_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.CredDialogHost_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.ECApp_10.0.19041.4239_neutral__8wekyb3d8bbwe
Microsoft.LockApp_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.Windows.Apprep.ChxApp_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.AssignedAccessLockApp_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.CallingShellApp_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.CapturePicker_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.Windows.CloudExperienceHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.ContentDeliveryManager_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.NarratorQuickStart_10.0.19041.4239_neutral_neutral_8wekyb3d8bbwe
Microsoft.Windows.OOBENetworkCaptivePortal_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.Windows.OOBENetworkConnectionFlow_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.Windows.ParentalControls_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.PeopleExperienceHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.PinningConfirmationDialog_1000.19041.4239.0_neutral__cw5n1h2txyewy
Microsoft.Windows.SecHealthUI_10.0.19041.4239_neutral__cw5n1h2txyewy
Microsoft.Windows.ShellExperienceHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.StartMenuExperienceHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.XGpuEjectDialog_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.XboxGameCallableUI_1000.19041.4239.0_neutral_neutral_cw5n1h2txyewy
MicrosoftWindows.Client.CBS_1000.19056.1000.0_x64__cw5n1h2txyewy
MicrosoftWindows.UndockedDevKit_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
NcsiUwpApp_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe
Windows.CBSPreview_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
NVIDIACorp.NVIDIAControlPanel_8.1.966.0_x64__56jybvy8sckqj
Microsoft.MicrosoftEdge.Stable_124.0.2478.97_neutral__8wekyb3d8bbwe
Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.4239.0_neutral_neutral_8wekyb3d8bbwe
Microsoft.Win32WebViewHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy
Microsoft.Windows.Search_1.14.15.19041_neutral_neutral_cw5n1h2txyewy
```

</details>

Off the top of my head, VCLibs may not be included by default in LTSC. So that's worth checking for.

**Comment by Ammako** [comment]
Are you still having problems? I just reinstalled LTSC 2021, and with 1.1.0 of Zelda64Recompiled it fails to start when Visual C++ Redistributable 2015-2022 is missing (gives a bunch of errors about it), but once installed, everything runs fine.

**Comment by Reonu** [comment]
Closing since this seems to have been an issue with a missing runtime and the user hasn't replied again. Feel free to re-open if you're still having the issue.
