### ISSUE TITLE
Add OpenGL 3.0 support 

### ISSUE THREAD

**Issue by sardonix** [Mr-Wiseguy/Zelda64Recomp#342]

**Comment by Mr-Wiseguy** [comment]
This would be a change in RT64, not this project. With that said, OpenGL and other older API support is not practical as RT64 is designed to use all the features available to modern APIs and adding support for older ones would basically require writing an entirely new renderer. There would be basically zero benefit to doing that, as any GPU made from the past 12 years can run DX12/Vulkan and the performance on older APIs would be worse.
