### ISSUE TITLE
[Help Request] How to change aim controls from inverted to regular?

### ISSUE THREAD

**Issue by ghost** [Mr-Wiseguy/Zelda64Recomp#344]
Read the title.

**Comment by Reonu** [comment]
It's in the "General" tab of the settings (which you can access by pressing ESC or the "Select" button on your controller)

**Comment by ghost** [comment]
> It's in the "General" tab of the settings (which you can access by pressing ESC or the "Select" button on your controller)

![Screenshot (89)](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/171515060/1407c192-2caf-4bf0-8d7a-f0effb466478)

I don't see the option.

**Comment by Mr-Wiseguy** [comment]
You're on an old version, you need to be on 1.1.0 to have that option. 1.1.1 will be coming out in less than half an hour so you can wait for that instead if you'd prefer.

**Comment by ghost** [comment]
Thank you so much!
