### ISSUE TITLE
Resolved Question, Non-Issue

### ISSUE THREAD

**Issue by DagothUrTheFalse** [Mr-Wiseguy/Zelda64Recomp#356]
I think a text file that goes over all patches and changes from the original games recompiled code would help make this project more approachable for people who want to help, and for people to better understand and appreciate the project from a non developer side.

If this is already provided in some fashion then ignore this, I just don't see anything besides the patches folder.

**Comment by DagothUrTheFalse** [comment]
This might even be something sorted out by the git versioning system or github but as a non-developer I am unaware of such.

**Comment by Reonu** [comment]
Hi, thanks for the interest.

If you look for comments containing the word `@recomp` you can find comments explaining every one of the changes that the project makes to the game (all of which are in the patches folder). Any code editor will allow you to search for this word across the entire codebase.

**Comment by DagothUrTheFalse** [comment]
Thank you, have a nice day.
