### ISSUE TITLE
Changing Rom

### ISSUE THREAD

**Issue by Landon2099** [Mr-Wiseguy/Zelda64Recomp#37]
I need to change the selected rom. How is this done? I apologize if this is a bad question. Thank you all for your hard work.

**Comment by sherpz** [comment]
press windows + r and type "appdata" then hit enter
press the "Local" folder
scroll down till you see the folder named "Zelda64Recompiled" and delete it
this will delete all your configurations but you will be able to change roms, i just figured this out
hope this helps
