### ISSUE TITLE
[Feature Request] A/B swap toggle for menu interaction

### ISSUE THREAD

**Issue by Francisco17C** [Mr-Wiseguy/Zelda64Recomp#372]
Hi, I'm using the Switch pro controller and was wondering if it could be possible to add a toggle in settings to swap the buttons **A** and **B** for their use on menus of the launcher, In game with the button remapping I have no problems but when I want to adjust something like sound or controls is sometimes confusing to use B for accepting as i'm used to Nintendo's button placing, Thanks.

**Comment by briaguya0** [comment]
a similar issue https://github.com/Zelda64Recomp/Zelda64Recomp/issues/362 was closed recently but I believe that one was asking to *automatically* change accept/cancel layout based on device. if i'm understanding this correctly it's just asking for an option to toggle between south as accept/east as back and east as accept/south as back (similar to the option steam decks have) which seems reasonable

**Comment by Francisco17C** [comment]
> a similar issue #362 was closed recently but I believe that one was asking to _automatically_ change accept/cancel layout based on device. if i'm understanding this correctly it's just asking for an option to toggle between south as accept/east as back and east as accept/south as back (similar to the option steam decks have) which seems reasonable

Exactly, a toggle so that the button on south (regardless of controller) is cancel instead of accept and and the button on the east is accept.

**Comment by Mr-Wiseguy** [comment]
I think the cleanest solution here would be to extend https://github.com/Zelda64Recomp/Zelda64Recomp/pull/181 to cover the accept button, since that would allow choosing a good accept button on any controller and not just xbox/switch.

**Comment by Francisco17C** [comment]
> I think the cleanest solution here would be to extend #181 to cover the accept button, since that would allow choosing a good accept button on any controller and not just xbox/switch.

That would be great
