### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by sanityormadness** [Mr-Wiseguy/Zelda64Recomp#373]
[remove]

**Comment by Mr-Wiseguy** [comment]
Hi, I think you opened this issue on the wrong project. The screenshots you posted are from 2S2H, and in recomp the flags do show up from far away. Actors do still have draw distance, but that's because I didn't want to affect gameplay by having actors active from any point in the map.

**Comment by sanityormadness** [comment]
Ah, whoops. Yes, this is absolutely the wrong project.

Excuse me while I melt into a puddle of embarrassment.
