### ISSUE TITLE
Feature Request: Better Mini Map

### ISSUE THREAD

**Issue by GFreak01** [Mr-Wiseguy/Zelda64Recomp#379]
It would be awesome to see the full sized map (current floor only) in the bottom right of the screen from time to time.  This would also assist players who don't have maps memorized to see the dungeon map without having to pause the game.

What if you could flip between current mini-map to fill screen map with just a click of the L button?

**Comment by Mr-Wiseguy** [comment]
This is a pretty cool idea, but it'd be outside the scope of the base project. I think it'd make a great mod once modding support comes out.
