### ISSUE TITLE
Unable to initialize Vulkan on Mesa 24.1.1

### ISSUE THREAD

**Issue by nathanjensen1** [Mr-Wiseguy/Zelda64Recomp#380]
**Describe the bug**
Zelda64Recomp v1.1.1 reports missing Vulkan extensions VK_KHR_xlib_surface and VK_KHR_surface when using the Mesa RADV 24.1.1 graphics driver. The vulkaninfo command shows both of these extensions are supported. The previous version of Mesa 24.1.0 works correctly with Zelda64Recomp v1.1.1.

**Screenshots**

![Screenshot from 2024-06-07 18-27-22](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/95645648/4db81e41-2d29-4909-ad00-edf2fcc90558)

![Screenshot from 2024-06-07 18-26-47](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/95645648/e37acd99-4c45-4a19-bf28-cede4daf7e5f)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.1.1
 - CPU: AMD Ryzen 5 7600X
 - GPU: AMD Radeon RX 6600 XT
 - GPU driver: Mesa RADV 24.1.1

**Comment by nathanjensen1** [comment]
I was able to test on another computer with Intel integrated graphics, and it exhibited the exact same behavior. Mesa 24.1.0 works but 24.1.1 does not.

**Comment by spiffeeroo** [comment]
The binary version works for me, but the Appimage does not. I am also using Arch Linux and Mesa RADV 24.1.1.

**Comment by SloppyPuppy** [comment]
Bump, same happened to me after update.
It seems to be something with the new version of the packages on Arch Linux, I downgraded these packages using downgrade and works again. 
`sudo downgrade lib32-vulkan-mesa-layers lib32-vulkan-radeon vulkan-mesa-layers vulkan-radeon`
Although I got integrated radeon graphics.

**Comment by Mr-Wiseguy** [comment]
As stated, this seems to be an issue with the AppImage. If you run into this problem then give the regular binary a shot instead in the meantime while we sort it out. If anyone has an idea for why this happens, we'd definitely appreciate the help here.

**Comment by dcvz** [comment]
@nathanjensen1 and anyone having this issue atm, could you please test out the Release X64 App Image here?
https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9445507391

**Comment by spiffeeroo** [comment]
> @nathanjensen1 and anyone having this issue atm, could you please test out the Release X64 App Image here? https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9445507391

Works for me.

**Comment by nathanjensen1** [comment]
This new AppImage works for me too

**Comment by zwaldowski** [comment]
A new release hasn't been been tagged since this was closed, is it expected to still grab a bleeding-edge AppImage?
