### ISSUE TITLE
App closes on Start Game after ROM is selected

### ISSUE THREAD

**Issue by emufa** [Mr-Wiseguy/Zelda64Recomp#39]
Game closes on boot after selecting the ROM and attempting to boot. ROM has been checked with ROM hasher to ensure is not a bad dump.

**To Reproduce**
1. Run the .exe
2. Select the MM64 ROM
3. Hit "Start Game"

 - Windows 10
 - Version	10.0.19045 Build 19045
 - Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, 2904 Mhz, 8 Core(s), 16 Logical Processor(s)
 - NVIDIA GeForce GTX 1660 Ti

**Comment by bryc** [comment]
Is your ROM sha1 hash `d6133ace5afaa0882cf214cf88daba39e266c078`?

That is what mine was, and this issue did not occur for me.

**Comment by emufa** [comment]
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/88774135/247671f8-36ef-49c5-9caa-26213b0475a7)
yep

**Comment by sherpz** [comment]
try updating your graphic drivers, one of the closed issues got solved by doing that

**Comment by emufa** [comment]
Works!

**Comment by paparansen** [comment]
got the same issue, rom hash is correct, latest driver.
using i5-6500t with HD530.

**Comment by bryc** [comment]
Just speculating, but seems like the culprit might be some GPU feature being used that only exists in recent NVIDIA (and perhaps AMD) drivers, and may not exist in older integrated Intel graphics, even with the latest drivers.

**Comment by paparansen** [comment]
hmmm... will try it on another, more recent intel machine
and then report back.

**Comment by auwsmit** [comment]
I guess it is based on RT64 so it isn't too surprising, but I'm still kinda surprised that simply updating the NVIDIA driver fixed this issue with no reboot even required

(Windows 11, Ryzen 3600, RTX 2070S)

**Comment by Mr-Wiseguy** [comment]
Closing as the original issue was resolved.
