### ISSUE TITLE
[Request] Please don't zip-archive the appimage version

### ISSUE THREAD

**Issue by AQDuck97** [Mr-Wiseguy/Zelda64Recomp#394]
AppImage is already an archive (as well as executable), zipping only saves ~0.6MiB (48.5MiB to 47.9MiB) but adds unnecessary time for the user to unzip before running.

**Comment by dcvz** [comment]
> AppImage is already an archive (as well as executable), zipping only saves ~0.6MiB (48.5MiB to 47.9MiB) but adds unnecessary time for the user to unzip before running.

You're right! Unfortunately that's a limitation of GitHub's system for uploading and downloading artefacts. There's nothing we can do about it.

**Comment by Mr-Wiseguy** [comment]
Thanks for pointing this out, as mentioned the GitHub build artifacts are zipped so I'll try to remember to unzip them when uploading releases in the future.
