### ISSUE TITLE
Need to map the key to open the settings menu

### ISSUE THREAD

**Issue by plato879** [Mr-Wiseguy/Zelda64Recomp#395]
Hi guys. I've been playing Majora's Mask with the emulator you developed. I thought it would be very interesting to play that game with a controller shaped like Nintendo 64's trident, so I bought one. Right now the controller works, but there is a little issue about the rught C button, which somehow always opens the settings menu of the emulator. Ghis sould not be a problem if I could map somehow else the button to open that menu but this feature seems not to be available. Could you aolve this somehow? After you solved jt, is it possible to update the emulator without losing data such as saved games? Thank you for what you could do.

**Comment by Reonu** [comment]
A correction: this is not an emulator. This is a native PC port of the game.

The ability to remap the menu button was added in 1.1.0. If you don't have the option to do this, then you're on an old version, so please update to the lastest version (1.1.1). This also adds a right stick camera option and other cool features.

Don't worry, your saved game, config etc are stored separately from the game itself (in your localappdata folder) so you can upgrade without worrying about losing anything.

**Comment by Mr-Wiseguy** [comment]
Closing as this feature already exists.
