### ISSUE TITLE
Day transition screen shrinkage does not reset on the title screen

### ISSUE THREAD

**Issue by TSEG6** [Mr-Wiseguy/Zelda64Recomp#402]
**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

I haven't but I'm 99.9% sure this isn't on original hardware, if I'm wrong then wouldn't that be interesting, I guess?

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

I was playing normally

**Describe the bug**
Saving at an owl statue when the screen starts shrinking for a day transition will carry over to the first section of the title screen.

**To Reproduce**
1. Wait until the screen starts shrinking
2. Save at an out statue
3. See issue once you exit to the title screen

**Expected behavior**
Saving and exiting via an owl statue should have the screen not be shrunken on the title screen.

**Video**

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/44306826/d6b21f3e-6909-4f5d-8a32-7355af49a255

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version: [1.1.1]
 - CPU: [Intel i7 12700KF]
 - GPU: [RTX 3070 ti]
 - GPU driver: [555.99]

**Additional context**
I found this by accident lol

**Comment by AngheloAlf** [comment]
I got curious and checked. I got to replicate this bug on my N64, so this seems to be a vanilla bug.

You can see it by looking at Majora's mask not covering all the screen
https://drive.google.com/file/d/1YztCVa-4Rh_W_Gw1AsdpfeVGZkJ_ROSf/view?usp=sharing
(sorry for the terrible quality, I don't have a proper way to record my n64)

**Comment by Mr-Wiseguy** [comment]
Beat me to it, I was also recording footage of the game on my N64 as well after verifying that it exists in the original game. Closing since this is a vanilla issue.

**Comment by TSEG6** [comment]
Wow, I was so sure that this couldn't have been a bug with the original game, but what do you know.
