### ISSUE TITLE
Switch N64 Controller C-Right Binding Issue (ALSO: GC Controller L & R Triggers Broken)

### ISSUE THREAD

**Issue by ButtSavage** [Mr-Wiseguy/Zelda64Recomp#41]
**Describe the bug**
When trying to set C Right on the switch online N64 controller it seems to be bound be default to escape so it closes the menu instead of binding, at least for me.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.0
 - CPU: Intel i7-8700
 - GPU: NVIDIA GeForce RTX 2060 SUPER

**Additional context**
Maybe an option to bind options menu open and close or disable escape to close on the binding screen?

EDIT: Would also like to note gamecube controllers L and R triggers constantly activate even when not pressing, probably analog trigger related?

**Comment by FSR-1** [comment]
use betterjoy for cemu customized for nso n64 controller and then connect it with steam input (launch the game from steam) and customize the controller layout

**Comment by ButtSavage** [comment]
Sadly that didn't work, c right still brings up the options menu and doesn't bind.

**Comment by RyouFuchiKyou** [comment]
> use betterjoy for cemu customized for nso n64 controller and then connect it with steam input (launch the game from steam) and customize the controller layout

Betterjoy has been non-functioning for a long time and a useless piece of software when Steam exists. Side note: Steam Input is not being excepted by the game. Unsure why.

Can confirm C Right on the Switch Online N64 Controller is not map-able. Definitely needs fixing.

OS: Windows 10
Version: 1.0.0
CPU: AMD Ryzen 9 5950X
GPU: EVGA FTW3 & NVIDIA GeForce RTX 3080 12GB

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/31379544/d6a9cb7d-006c-4edb-a049-23061d978a7d)
 This is what the Right C Button is registering as. This might help with a fix. I used this: https://gamepadviewer.com/

**Comment by FSR-1** [comment]
> Betterjoy has been non-functioning for a long time and a useless piece of software when Steam exists.

well it fixed  my issue so i dont know what your on about i used the one made for the n64 online controller since it was the only way i found out how to get it working with n rage

**Comment by FSR-1** [comment]
> You're one of the few. Just because some random piece of software exists doesn't mean something shouldn't be fixed.

never said the issue shouldn't be fixed i already made a issue report about it and hopefully in the next few versions you will be able to change the menu button i only just said what fixed the z button being stuck for me as well as the menu button being c right

**Comment by FSR-1** [comment]
> Sadly that didn't work, c right still brings up the options menu and doesn't bind.

have you gone into steam settings and rebinded the controller

**Comment by RyouFuchiKyou** [comment]
> steam settings and rebinded the controller

There's no way to force a controller to work only through steam. This program lacks an option to select your input device, and in and of itself is a problem.

**Comment by ButtSavage** [comment]
For now I'm just binding C-Right to the small ZR button on the nso n64 controller since that one registers properly.

**Comment by Ammako** [comment]
I guess this would be why you can't bind the "Select" button on xinput. but it doesn't close the menu here, it just cancels out of the binding without doing anything.

You can manually bind that button by editing the controls.json in local appdata, set input_id: 4 and input_type: 3, but despite being bound, it still just opens the menu instead of sending that input to the game.

**Comment by rkroll17** [comment]
I'm having the same issue

**Comment by tbchek** [comment]
I added the compiler as a non-steam program and used steam input to remap the C-buttons. Works fine now as a band-aid fix for anyone that wants to use an N64 controller.

**Comment by Uchira1430** [comment]
also having the issue with the C right button. hoping for a fix soon!

**Comment by Deozaan** [comment]
For those playing on Steam Deck, I configured the NSO N64 controller through Steam Input like so:

| NSO N64 Button | Default Mapping | Custom Mapping |
|---|---|---|
| C-Right | Select | Right Joystick Click |
| ZR | Left Stick Click | Select |

So now I can toggle the menu with ZR on the NSO N64 controller and map C-Right without interfering with mappings for other controllers. I've also shared this as a Community Layout on Deck, though I'm not sure if/how community layouts are shared for non-Steam games.

Here's a screenshot of what my layout looks like:
https://steamcommunity.com/sharedfiles/filedetails/?id=3247378653

**Comment by sorokya** [comment]
Also can't properly setup controls with a Mayflash N64 USB adapter (model PC043).

D-Pad/C-Buttons refuse to bind to any action.
Analog stick moves to a different row in the settings.

**Comment by m9henri** [comment]
> For those playing on Steam Deck, I configured the NSO N64 controller through Steam Input like so:
> 
> NSO N64 Button	Default Mapping	Custom Mapping
> C-Right	Select	Right Joystick Click
> ZR	Left Stick Click	Select
> So now I can toggle the menu with ZR on the NSO N64 controller and map C-Right without interfering with mappings for other controllers. I've also shared this as a Community Layout on Deck, though I'm not sure if/how community layouts are shared for non-Steam games.
> 
> Here's a screenshot of what my layout looks like: https://steamcommunity.com/sharedfiles/filedetails/?id=3247378653

Bruh my start button won't work now. @Deozaan I have a n64 usb controller from amazon and I can't use my start button as it is mapped to the PS button (It's a virtual PS3 controller but rebuilt as a n64 controller ig) and I don't know how to remap the PS button.

**Comment by Deozaan** [comment]
> Bruh my start button won't work now. @Deozaan I have a n64 usb controller from amazon and I can't use my start button as it is mapped to the PS button (It's a virtual PS3 controller but rebuilt as a n64 controller ig) and I don't know how to remap the PS button.

Bruh nothing I said has anything to do with a N64 USB Controller from Amazon.

**Comment by Ammako** [comment]
Maybe WiinUPro might be an option? It supports Switch Pro Controllers, maybe it'll support the NSO controllers too. Then in the UI you can assign different key mappings for the emulated xbox controller for any problematic buttons.

**Comment by m9henri** [comment]
It sadly didn't work. It is not an NSO controller btw, it's this controller
<https://amzn.eu/d/6MmR6uz> right here. If you got any other ways, feel
free to contact me again.

Am Do., 16. Mai 2024 um 22:11 Uhr schrieb Ammako ***@***.***>:

**Comment by Reonu** [comment]
Fixed by #181

**Comment by CuddleBear92** [comment]
I'm struggling with this one, says its fixed in a commit earlier than the current latest release but it wont bind out of the box? 
Is it expecting a 3rd party program to fix it? I see the gamecontrollerdb.txt file contains an entry for the "NSO N64 Controller".
Whatever I try, I cant get it to bind and be useful.

EDIT: for some reason i can get it to bind now... not quite sure why thats the case. it was already updated ages ago.
Icons for to right C button and the extra "screenshot" button on the controller are both wrong in the game.
