### ISSUE TITLE
Analog camera ocarina dive desync 

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#415]
When using the ocarina dive, the C buttons get desynced with the new analog camera

1. Enable analog camera with the right stick of a controller
2.Go to the second orange stripe near the wall in the laundry pool.
3.Put on Zora mask
4.Side hop
5.Go to the center of where the wall's lip touches the void.
6. Do a triple slash
7. Quickly press the ocarina Dpad button, or the C button assigned to it.
8. Play any song that Link knows so long as the song playing animation cuts off while voiding out.

**Expected behavior**
The song that was played, such as the song of time gets stored and can be reopened at any dialog prompt's finish.

**Unexpected behavior**
When looking with the right stick, it both looks around as link as well as triggering C stick buttons

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/71539195-8ccc-4174-9945-a6f18bb5778e)

 - Debian 12.5
 - Version: 1.1.1
 - AMD 5600x
 - Nvidia 3060
 - Nvidia 535.183.01 proprietary drivers
 
**Additional context**
The analog camera was never part of the n64 release of OoT, so this is a new bug not present on the n64

**Comment by Mr-Wiseguy** [comment]
This trick puts the game in a very glitched state, so I think it's reasonable to expect that even new features would behave strangely when it's performed. It's even more reasonable to me if the feature can be turned off like this one. Making sure that every new feature never behaves weirdly under heavily glitched game states would grind the development to a halt as every contributor (including myself) would need to learn basically every glitch that can be performed. Closing this as a wontfix, but I'd accept a PR that turns off analog camera when the game is in this state as long as it doesn't affect the analog cam feature during normal gameplay.
