### ISSUE TITLE
Inconsistent hook-shot behavior

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#420]
I noticed I nolonger can hookshot on the boxes in the center of clocktown

**Expected behavior**
I should be able to use the hookshot on wooden surfaces in clocktown that are part of the map
You can do this on the Gamecube Collector's addition disk

**Unexpected behavior**
The hookshot bounces off the boxes in the center of clocktown, and in the pirate's fortress. 

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/a8d4075d-e908-4859-ba6e-2c3f67922147)
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/626f7d2b-e13f-4e32-836c-21f33bc96c19)
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/8f2f6226-21b3-40a1-8afa-033255ab6134)

 - Debian 12.5
 - Version: 1.1.1
 - AMD 5600x
 - Nvidia 3060
 - Nvidia 535.183.01 proprietary drivers
 
**Additional context**
I am not sure if the skulltula weirdness is an OoT and MM difference, but I know the boxes are glitched as I did this on the Wii running the GC collector's addition

**Comment by Mr-Wiseguy** [comment]
None of the hookshot targets you mentioned work any differently in the original game. Here's footage of each that I recorded from my N64.

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/cdd2739c-d388-4573-98ca-0231c7a9e9fe

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/b63b1ec8-d03c-4ac0-bf6c-4cf2aa468184

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/3bf51545-a908-43e4-89b2-8885cf553b67

I also tested on my copy of the collector's edition and the results are the same there. This is not the first issue you've opened where the behavior in recomp matched the original game, please do not open further issue reports without testing the original first.

**Comment by Reonu** [comment]
Here's a video proving that the GameCube version also behaves just like Recomp:

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/15913880/7253b058-7c41-4049-9f5d-d9aec6c0f57e

**Comment by ActuallyTheOwner** [comment]
Maybe I misremembered, what version allowed this?
