### ISSUE TITLE
Random hangs on boot with Wayland on Nvidia

### ISSUE THREAD

**Issue by Reonu** [Mr-Wiseguy/Zelda64Recomp#423]
On Nvidia systems running Wayland, the game can randomly hang up on boot, displaying one single frame of the main menu and then being locked up with 100% CPU load on one thread forever.

Debugging it shows that the `RT64 Present` thread is getting stuck on `vkWaitForFences` forever.

It's a bit unclear whether this is an Nvidia driver bug, a Wayland bug, or an xWayland bug, though the Nvidia driver seems like the most likely culprit. Either way, adding native Wayland support to the game (either by adding it to RT64 or by letting SDL handle surface creation) might fix it, but it might not.

Help would be appreciated with this issue.

**Comment by Reonu** [comment]
Darío and me debugged and fixed this, so it's now fixed on RT64. This will now be fixed when this project pulls RT64.

**Comment by Mr-Wiseguy** [comment]
Fixed by #424.
