### ISSUE TITLE
Ocarina dropping inputs for songs (Not the same as on OoT)

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#427]
**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
Yes, I could not get the glitch to happen on hardware for Majora's mask, but it does happen in Ocarina of Time.

I did not use any glitches

The ocarina drops inputs

**To Reproduce**
1. Unlock any ocarina song
2. Play the song too fast

**Expected behavior**
No inputs are dropped

**Screenshots**
file:///home/wellswole/Videos/2024-07-02 17-55-08.mp4
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/7cc93193-b693-4e7a-b748-2e6426ac7307)

**KDE plasma 5.27.5
 - Debian GNU/Linux 12 (bookworm) x86_64
 - kernel 6.7.12+bpo-amd64 
 - AMD 5600x
 - Nvidia RTX 3060
 -  Driver Version: 535.183.01

**Additional context**
Sorry for not specifying hardware in my last update.
I am using a gamecube controller with a gbros adapter, but noticed it also happens with keyboard input.

**Comment by ActuallyTheOwner** [comment]
file:///home/wellswole/Videos/2024-07-02 17-55-08.mp4

**Comment by ActuallyTheOwner** [comment]
It seems that I am having issues uploading a video I had of the issue

**Comment by ActuallyTheOwner** [comment]
https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/9074386e-1630-4459-b228-7eb2298a998b

**Comment by ActuallyTheOwner** [comment]
Note, the game has less lag on PC, this could be why I only had the bug replicate in OoT

**Comment by ActuallyTheOwner** [comment]
It is possible this is in the base game, but should be fixed as other unofficial ports do for OoT.
I could not find info online

**Comment by ActuallyTheOwner** [comment]
https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/791026c0-8212-49c3-b64e-f5a3b859853e

The bug is different then I thought
It seems this is not the same bug as in OoT
I noticed **even playing songs slow fails**

**Comment by Mr-Wiseguy** [comment]
This bug does not exist in OoT, and it does exist in every version of MM. When you take out the ocarina, the game will discard song inputs for the first 3 frames (150 milliseconds) that you're able to play notes. I've already written a fix for it that I'll push later today, which will end up in the next release.
