### ISSUE TITLE
The exe dont open

### ISSUE THREAD

**Issue by Abilthedev** [Mr-Wiseguy/Zelda64Recomp#43]
Hey when i doble click the exe it just loading blue circle for briev moment 

When i dont click the exe my cpu usage is 1 percent but if i open it it  jump to whoping 50-78 percent dispate it was not opening and nothing in the task manager 

I using windows 10
Pleass heellp me i want this badly.did i need put this on c hard drive

**Comment by Mr-Wiseguy** [comment]
Please try a newer release of recomp as well as updating your graphics, and state your hardware specs and OS version as requested in the issue template. Closing due to lack of information, but feel free to reopen after doing what I suggested if you still can't run it.
