### ISSUE TITLE
Majora's mask recomp v1.1.1 save file (For those who need it)

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#432]
I beat the recomp on the US rom.
Slot 1 is 100% 
Slot 2 is a race file
file:///home/wellswole/Desktop/mm.n64.us.1.0.bin

**Comment by ActuallyTheOwner** [comment]
Sorry, github failed to upload, so I put it in a .zip
[mm.n64.us.1.0.bin.zip](https://github.com/user-attachments/files/16124109/mm.n64.us.1.0.bin.zip)

**Comment by 111ebobo** [comment]
> I beat the recomp on the US rom.
> Slot 1 is 100% 
> Slot 2 is a race file
> file:///home/wellswole/Desktop/mm.n64.us.1.0.bin

Can you provide the stone tower temple save right before the boss battle (I just lost my save)? @ActuallyTheOwner

**Comment by 111ebobo** [comment]
> > I beat the recomp on the US rom.
> > Slot 1 is 100% 
> > Slot 2 is a race file
> > file:///home/wellswole/Desktop/mm.n64.us.1.0.bin
> 
> Can you provide the stone tower temple save right before the boss battle (I just lost my save)? @ActuallyTheOwner 

7 hearts, no fairy upgrades, no completed side quests

**Comment by ActuallyTheOwner** [comment]
unfortunatly, I made a mistake on the race file, it has not skipped through cutscenes in clocktown or get extra rupees
Also, I beat the dungeons in backwards order, so that was a while ago. I do not have it backed up.
