### ISSUE TITLE
Crash after finishing swamp

### ISSUE THREAD

**Issue by HeikePruskowsky** [Mr-Wiseguy/Zelda64Recomp#434]
**Describe the bug**
Whenever I enter a new area _after having finished the swamp_, the game will (most certainly) crash.
What makes the problem worse (I guess?) is that the crash does not occur consistently.
I did not take advantage of any bugs / cheats / glitches. 

Crashing happened when I...

- tried entering Romani Ranch while having the bunny hood equipped (I got the bunny hood before, but only after finishing the swamp re-entering the area crashes the game)
- tried entering Snowhead mountain for the very first time (game crashed after shooting down the ice stalactite while having the bunny hood equipped)
(I saw a few frames of Link walking into the next area before the game stuttered and crashed, 
I had a vague idea of "hm, looks like Link is walking too fast for the frames to keep up", so I wondered if the issue might have to do with the bunny hood, so I tried again after unequipping the bunny hood and this time the game let me enter the mountain area without crashing)
- after having successfully entered Snowhead: crash upon entering the smithy's house (not having equipped the bunny hood)

**To Reproduce**
See save file. (maybe)

**Expected behavior**
Not crash and being able to continue the game. (Please!)

**Desktop:**

    OS: Windows 10 Pro (22H2)
    Version: 1.1.1
    CPU: Intel i7-10750H
    GPU: NVIDIA GeForce GTX 2070 Super with Max-Q Design
    GPU driver: GeForce Game Ready Driver 556.12

**Additional context**
Thank you so much for your work. <3

[saves.zip](https://github.com/user-attachments/files/16200348/saves.zip)

**Comment by Mr-Wiseguy** [comment]
Thanks for the report and for uploading your save file. Unfortunately, I'm unable to reproduce the crashes you mentioned with the save file you sent on the 1.1.1 executable. Could you also upload the json files in your appdata folder? Also, by any chance are you using a version downloaded from the github action builds for the HD textures branch? It'll still show 1.1.1 in the launcher. This sounds similar to a crash that was fixed very recently for that branch.

**Comment by HeikePruskowsky** [comment]
>Unfortunately, I'm unable to reproduce the crashes you mentioned...

I was afraid that'd be your answer....:(

I downloaded/used only the "official" version (1.1.1) from github's release page (not any action build).
(I tried version 1.1.0 at some point, but (as expected) that older version is not compatible with the newest Nvidia driver. (crash upon booting the game))

[Zelda64Recompiled - Kopie.zip](https://github.com/user-attachments/files/16201846/Zelda64Recompiled.-.Kopie.zip)

**Comment by Mr-Wiseguy** [comment]
> (I tried version 1.1.0 at some point, but (as expected) that older version is not compatible with the newest Nvidia driver. (crash upon booting the game))

That's not as expected, there's no reason that 1.1.0 should be crashing on the latest Nvidia driver. I have the same driver version installed as you and 1.1.0 runs fine for me (even with the saves and json files you sent). I don't have the exact same graphics card (mine is a 3080), so I'll ask a friend of mine who has an RTX 2000 GPU to try to reproduce the issue as well.

In the meantime, it may be worth using [DDU](https://github.com/Wagnard/display-drivers-uninstaller) to completely remove your graphics drivers so you can do a clean install of the latest version, in case there's some issue with your driver install or lingering installs from older graphics cards if you've ever upgraded.

**Comment by Reonu** [comment]
I just booted up my laptop which has an RTX 2070, updated the Nvidia driver to 556.12, and tried the scenarios you described as causing crashes on 1.1.1. No issues.

Then I tried 1.1.0, which you mentioned would not work at all, and that also worked perfectly.

So I'm not sure what the issue is, but it doesn't seem to be something that happens to everyone on this GPU architecture or driver at least. I suggest you follow Wiseguy's advice and use DDU to do a completely clean reinstall of your drivers.

**Comment by HeikePruskowsky** [comment]
I used DDU and reinstalled the newest Nvidia driver.
Looks like that fixed the issue.
I explored the mountain area for a bit and did not experience any more crashes. (v1.1.1)
Also, v1.1.0 does not crash upon start-up anymore.

Thank you. <3

**Comment by Reonu** [comment]
Glad it was fixed!
