### ISSUE TITLE
Moth animation on torches not interpolated to high framerates

### ISSUE THREAD

**Issue by Chalking** [Mr-Wiseguy/Zelda64Recomp#459]
(Played on steam deck)

The animation for moths flying around torches do not update higher than 20fps.

![Moth](https://github.com/user-attachments/assets/466e98ee-4dd9-4b1f-9d6b-b43fb9807e36)

 (Note: not a screenshot from the port, as it would have to be an animation to illustrate the issue and I don't have the means to record on Steam Deck, I'm just uploading this screenshot to be clear which moths I'm talking about.

**Comment by Mr-Wiseguy** [comment]
Thanks for the report, this is now fixed by https://github.com/Zelda64Recomp/Zelda64Recomp/pull/460 which will be in the next release.
