### ISSUE TITLE
I would like to change the rom that the recomp is using so that i can use a patched version of the game but there isn't any way to do so.

### ISSUE THREAD

**Issue by FDmonk** [Mr-Wiseguy/Zelda64Recomp#464]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**

**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**

**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**

**Describe the bug**

**To Reproduce**
2. etc.

**Expected behavior**

**Screenshots**
Please attach a screenshot of the bug.

**Desktop (please complete the following information):**
 - OS: [Windows 10, Windows 11, Linux distro]
 - Version: [e.g. 1.0.0]
 - CPU: [e.g. Intel Core ..., AMD Ryzen ..., etc.]
 - GPU: [e.g. NVIDIA GeForce .../Radeon RX .../Intel UHD .../etc.]
 - GPU driver: [e.g Nvidia driver 545.XX, AMD driver 24.X.X, etc]

**Additional context**

**Comment by Reonu** [comment]
As explained in the FAQ and as has been explained multiple times in this issue tracker, this project is a port of **one specific game** and therefore **takes one specific ROM**, it is not an emulator and therefore it **cannot** "run" any arbitrary ROM.

Modding support is being actively worked on and will not require you to provide a different ROM. You will be able to download and load mods with the normal US ROM. Please be patient.
