### ISSUE TITLE
[Question] What are the second control options for? 

### ISSUE THREAD

**Issue by LtheZ** [Mr-Wiseguy/Zelda64Recomp#466]
I'm looking at the controls menu and it gives you two options for each action. Is it like a combo control? Or just 2 buttons that do the same thing? If it is a combo control (ex. Holding LT+d-pad up/left/down/right would act as c buttons) I can't get it working. 

I hope there isn't an issue of this being put here, I don't know how to use discord.

**Comment by Reonu** [comment]
It's just a second button in case you want to map the same action to 2 buttons for whatever reason.
