### ISSUE TITLE
Issue: Compilation Fails Due to Undefined RECOMP_FUNC Macro

### ISSUE THREAD

**Issue by Nymnz** [Mr-Wiseguy/Zelda64Recomp#467]
When attempting to build the project, the compilation fails with errors indicating that the RECOMP_FUNC macro is undefined. This issue appears across multiple source files, resulting in numerous errors where RECOMP_FUNC is used to annotate function definitions.

**Steps to Reproduce:**
1. Follow the BUILDING.md guide
2. Run the following commands:
`cmake -S . -B build-cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build build-cmake --target Zelda64Recompiled --config Release
`
3. Observe the compilation errors.
**Observed Behavior**
The build process fails with errors like the following:
`/home/nymnz/gitrepos/Zelda64Recomp/RecompiledFuncs/funcs_102.c:2849:1: error: unknown type name 'RECOMP_FUNC'
RECOMP_FUNC void func_80883BEC(uint8_t* rdram, recomp_context* ctx)`
**Expected Behavior:**
The RECOMP_FUNC macro should be defined, allowing the project to compile successfully without errors related to undefined types or macros.

**Comment by Mr-Wiseguy** [comment]
Sorry about that, I updated the recompiler but forgot to merge the PR to work with it here (#465). I've done so now, so pull and update your submodules and try again.

**Comment by Nymnz** [comment]
Thanks, now it works without any issues!
