### ISSUE TITLE
[Feature Request] "Sitting Action"

### ISSUE THREAD

**Issue by TheRTGGaming** [Mr-Wiseguy/Zelda64Recomp#469]
I know this is a stupid request but if you watch the intro. Link is sitting down on the tower. It was never added to the game and i am sure this is going to be rejected but if you do plan it.

How it can work.

When link reaches a "Sitting" chair, bench or some place that he can put his but you can take the animation from the intro into the playable action while he sits on the chair or bench. that way rather then stand there lifeless waiting for time to pass he can be sitting down.

**Comment by Mr-Wiseguy** [comment]
This is out of scope for the base project. Somebody could make this as a mod when 1.2 releases with modding support.
