### ISSUE TITLE
Distribution of Fontworks' Chiaro font

### ISSUE THREAD

**Issue by TheFireRed** [Mr-Wiseguy/Zelda64Recomp#47]
As much as I love Chiaro, I don't think Fontworks/Monotype are going to allow free distribution of a licensed font.
https://lets.fontworks.co.jp/fonts/196

**Comment by Reonu** [comment]
Anda, cuánto tiempo. Otro interesante hilo de TheFireRed :)

No creo que esto sea un problema porque nuestro proyecto es totalmente gratuito, y hay más proyectos gratuitos que usan esta fuente y no pasa nada. No obstante, por supuesto, la cambiaremos si nos lo piden ellos, o si encontramos una fuente gratuita que sea suficientemente similar.
