### ISSUE TITLE
[Feature Request] (Ocarina of time) Let Child Link ride Epona, Like in Majora's mask

### ISSUE THREAD

**Issue by TheRTGGaming** [Mr-Wiseguy/Zelda64Recomp#474]
We all want it, and it makes sense. When you guys come out with OOT, can you add a Majora's mask feature that lets young Link be able to ride Epona around Hyrule. I know that once you become an adult and start getting the warp songs. I feel... the child link should be able to ride Epona. If not, you can ignore this request.

**Comment by Mr-Wiseguy** [comment]
This is out of scope of the base project, so this is something that somebody could make as a mod once OoT is added.
