### ISSUE TITLE
[Question] Any ETA on Ocarina of Time support?

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Mr-Wiseguy/Zelda64Recomp#475]
Is there any ETA on when support of Ocarina of Time will be added? I finished Majora’s Mask a few weeks back and am super excited to play Ocarina of Time!

**Comment by Mr-Wiseguy** [comment]
I can't give an ETA since I work on recomp in my free time which varies based on my job, but it will be what I work on after the coming 1.2 update (which will introduce mod support).

**Comment by RyanMitchellWilson** [comment]
Makes sense for sure, thanks so much for the hard work!
