### ISSUE TITLE
Build Instructions Need an Update

### ISSUE THREAD

**Issue by lkoger** [Mr-Wiseguy/Zelda64Recomp#478]
While attempting to build the project on Windows, I received the following error:

```
C:\Users\<redacted_username>\Documents\workspace\Zelda64Recomp\lib\N64ModernRuntime\ultramodern\src\events.cpp(532,40): warning : unused variable 'setup_result' [-Wunused-variable]
    532 |     ultramodern::renderer::SetupResult setup_result = renderer_setup_result.load();
        |                                        ^~~~~~~~~~~~
  4 warnings generated.
  [423/1077] Generating C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/patches/patches.bin, C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/patches.c, C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/recomp_overlays.inl, C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/funcs.h
  FAILED: C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/patches/patches.bin C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/patches.c C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/recomp_overlays.inl C:/Users/<redacted_username>/Documents/workspace/Zelda64Recomp/RecompiledPatches/funcs.h 
  C:\WINDOWS\system32\cmd.exe /C "cd /D C:\Users\<redacted_username>\Documents\workspace\Zelda64Recomp && .\N64Recomp patches.toml"
  Function func_80BB5AAC is not marked as a replacement, but a function with the same name was found in the reference symbols!
  Strict mode validation failed!
  Function count: 1631
  Working dir: C:\Users\<redacted_username>\Documents\workspace\Zelda64Recomp
  
  [424/1077] Generating ../src/shaders/RasterPSLibraryMS.hlsl.dxil
  [425/1077] Generating ../src/shaders/RasterVSDynamic.hlsl.dxil
```

I looked through the Github Actions and saw that the build processes for both Windows and Linux and saw where a very specific commit (**f8d439aeee6048b7365d1cb3bcd2578ec27a0288**) is being used to build the **N64Recomp** and **RSPRecomp** tools in the [N64Recomp](https://github.com/N64Recomp/N64Recomp) repo.

After checking out that commit and rebuilding the tools, I was able to successfully build on Windows.

The implementation of the **Validate** action suggests that this is a known issue. I would update the instructions myself, but I was not sure whether this was an issue with a fix upcoming soon. I assume that the owner and/or contributors would have some input.

**Comment by Mr-Wiseguy** [comment]
Good catch, this was an oversight that happened during a PR merge. I recently turned on "strict mode" when recompiling patches, which validates that every patch was tagged correctly, but this PR was submitted before the strict mode functionality was added to the recompiler and the latest N64Recomp PR fully enabled it.

**Comment by Mr-Wiseguy** [comment]
This has been fixed now, thanks again for pointing it out.
