### ISSUE TITLE
[Feature Request] Launch straight into game with command line argument.

### ISSUE THREAD

**Issue by t0mtee** [Mr-Wiseguy/Zelda64Recomp#479]
For example, using `-mm` would launch straight into Majora's Mask, and when OoT becomes available `-oot` will launch straight into Ocarina of Time. Would be useful to have for game launchers such as Playnite.

**Comment by Reonu** [comment]
Closing as duplicate of #161

**Comment by t0mtee** [comment]
Apologies, completely missed it
