### ISSUE TITLE
odd layering of transparent textures

### ISSUE THREAD

**Issue by SstarLit** [Mr-Wiseguy/Zelda64Recomp#480]
Not checked if original behaviour

**Describe the bug**
on Vulkan or Auto, certain transparent textures like water or tree leaves, or grotto holes will always draw in front of certain others, regardless of depth in comparison. it's made obvious by a transformation mask's white screen fadein and fadeout for what is a transparent texture

1. go somewhere a with a transparent texture like water or tree leaves
2. put mask on and look at where the transparent texture is 
3. jraphics
![Screenshot 2024-09-09 013518](https://github.com/user-attachments/assets/e81f097a-a1a0-4706-a781-06280443415f)

**Expected behavior**
transparent textures should render in order from distance to camera

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 10.0.22631 Build 22631
 - CPU: i3-8100
 - GPU: Radeon RX 6600
 - GPU driver: Driver Version 24.10.37.04-240823a-407010C-AMD-Software-Adrenalin-Edition 

**Screenshot**
distant tree clearly drawn in front of very close tree
![Screenshot 2024-09-09 004905](https://github.com/user-attachments/assets/95b1c498-ded1-46b9-9097-b1bd2bdd85d1)
tree leaves and part of the map's forest border stand out and dont change amongst the environment going from barely visible 
![Screenshot 2024-09-09 010309](https://github.com/user-attachments/assets/02ed2d2d-4d9c-4606-ba97-0e472daa5ad4)
distant tall grass starting to fade away, and thus drawing in front of the transparent flame of a bubble
![Screenshot 2024-09-09 012754](https://github.com/user-attachments/assets/3ccd29a4-8499-44a6-a556-074c34a1cc24)
grotto hole and southern swamp border in termina field standing out in the white fade-in
![Screenshot 2024-09-09 013114](https://github.com/user-attachments/assets/f1d60749-47eb-4ece-be4b-1538e69af281)
Buttons rendered in front of transparent fire effect of goron's roll.
![Screenshot 2024-09-09 013433](https://github.com/user-attachments/assets/b6373aa4-e814-41b8-a783-40ca24deb43e)
fading tall grass and swamp wall in termina field being the only thing visible as the white fade of a transformation mask is too strong to see anything else.
![Screenshot 2024-09-09 012459](https://github.com/user-attachments/assets/49f81765-9b5b-4126-9fc7-35c521d8ce1c)
water draws in front of the white fade, opaque textures do not then also draw behind the transparency oddity
![Screenshot 2024-09-09 023230](https://github.com/user-attachments/assets/134aeb4e-b76f-4bab-a5d6-589676bfafc9)

**Comment by Mr-Wiseguy** [comment]
These are all how the actual original game works. Some of these are the fact that the game doesn't sort translucent draws (like the trees and bushes drawing on top of surfaces that are closer to the camera), and the rest are surfaces that don't have fog set up, since the game uses fog for the fade effect with transformation masks. I can record footage from console later (if somebody else doesn't get to it first), but I suggest looking at footage of the original game if you don't have a console when you're unsure if something was how it originally worked.

**Comment by DarioSamo** [comment]
> Expected behavior
> transparent textures should render in order from distance to camera

You may be confusing this port with Majora's Mask for the Dreamcast.

**Comment by Mr-Wiseguy** [comment]
For example, if you look at this video (which you can tell is N64-captured footage because it was recorded using an UltraHDMI mod) at 7:57:53, you can see the fog used in the song of double time effect not affecting some plants in the background: https://www.youtube.com/watch?v=iNjX7UzRQyU

![image](https://github.com/user-attachments/assets/f87b5863-b489-4985-9ce1-89824b396bf0)

**Comment by Mr-Wiseguy** [comment]
Here are some other images of these effects happening on the original N64 version from that same video:

Water not fading with the rest of the scene when putting on a mask (left edge):
![image](https://github.com/user-attachments/assets/fbbef6b2-4459-43be-9297-f46018c7d2f8)

Transparent effects drawn on top of further away ones (the goron roll fire drawn behind the background shrub)
![image](https://github.com/user-attachments/assets/e6ad023d-c37b-4046-ad9c-45f3495a94ed)

**Comment by Reonu** [comment]
Hi there. I just got the chance to sit down and use my N64.

Like Wiseguy said, this is an issue with the vanilla game. Just in case there were any doubts left, here's a few screenshots captured from my N64 with a capture card.

Here you can see the issue with the trees rendering in the wrong order.
![Screenshot 2024-09-10 23-53-35](https://github.com/user-attachments/assets/fe3e80ed-1408-4b7c-ac07-121cc32656c2)
![Screenshot 2024-09-10 23-53-46](https://github.com/user-attachments/assets/69dde4a7-dad8-4729-a89b-251e9121bb06)

Here you can see the grotto hole and the bushes in the southern swamp edge of Termina Field staying visible during the white "fade-in" (which is actually achieved using the N64's fog effect on the materials)
![Screenshot 2024-09-10 23-55-12](https://github.com/user-attachments/assets/1733de9b-2c32-4aa1-923a-da4b66be9173)

And you can also see the issue with the notes on the wall:
![2024-09-10 23-58-50 mp4_snapshot_00 24 819](https://github.com/user-attachments/assets/e06e3f23-d1fb-4c56-b691-ca257aab5b48)

In the future, when you find visual quirks or oddities like these, please verify that they don't happen on N64 before reporting them. The issue template asks for a reason. Thanks!
