### ISSUE TITLE
Persistent D-pad / special item 1-4 binding functionality bug

### ISSUE THREAD

**Issue by jongdetim** [Mr-Wiseguy/Zelda64Recomp#481]
**Describe the bug**
After changing control bindings ingame on a wired xbox 360 controller, some items are displayed as mapped to the d-pad on the HUD. However, I can no longer change those mappings. No matter what control bindings I choose, I cannot remove or alter what is mapped to special item 1-4 using the d-pad. In the in-game pause menu, when fairy-item3 are bound to the d-pad, i can use the d-pad to assign items. If the special item 1-4 are bound the the d-pad, using the d-pad buttons will just move pages through the in-game pause menu, exactly like LT and RT do. Resetting settings or restarting the game or the application don't resolve this. Furthermore, it is now impossible to map any items to special item1-4, even if i change the keybindings to, for instance, right analog trigger.

**To Reproduce**
Bind look/fairy/item1-3/special item 1-4 all to the d-pad buttons. Now assign some items. Change the bindings so that only fairy/item1-3 are bound to the d-pad and notice that it's possible to map items in-game. Now change the bindings so that special item1-4 are the only actions bound to the d-pad. It's now no longer possible to map items using the d-pad.

**Expected behavior**
Items should map to special item 1-4 from the in-game pause menu.

**Desktop**
 - OS: [Windows 10]

**Comment by Mr-Wiseguy** [comment]
Apologies, but I'm unclear on what you mean. If you're asking how to change what items are bound to the special items slots, then the answer is you can't. The special item slots are always the ocarina and the 3 transformation masks. They don't work like the regular item slots that allow you to place any item on them.

**Comment by jongdetim** [comment]
Then it was a complete misunderstanding on my part. I assumed it was possible to map anything to the special item slots. I just happened to get the deku mask as I was changing controller bindings. My bad!

**Comment by Mr-Wiseguy** [comment]
No worries! Full binding would be nice, I just didn't get around to it for release. It's possible it may get added later (or maybe somebody will make a mod to allow it after 1.2 releases with mod support).
