### ISSUE TITLE
Game crashes when start game is pressed

### ISSUE THREAD

**Issue by Tommmahawk** [Mr-Wiseguy/Zelda64Recomp#483]
I believe I attempted to use a Majora's Mask Redux ROM during the initial set up and now can't figure out how to select the correct ROM cause the application only allows me to "start Game" before crashing.

How do I change the ROM the application is trying to play?

 - OS: Windows 11
 - Version: 1.1.1
 - GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
 - Processor	AMD Ryzen 7 4800H with Radeon Graphics    2.90 GHz
 - Installed RAM	16.0 GB (15.4 GB usable)
 - System type	64-bit operating system, x64-based processor

**Comment by Mr-Wiseguy** [comment]
There's no issue with your ROM. The program will detect if you provided an incorrect ROM and will only accept the exact correct one.

Double check that you're on the latest GPU driver, and make sure that you did it by downloading the latest driver from your GPU vendor's website. Don't use Windows to update your drivers, as it will usually give you an outdated one. Additionally make sure that you have the latest visual C++ redistributable installed.

**Comment by Tommmahawk** [comment]
I'll give this a go, thank you

**Comment by Mr-Wiseguy** [comment]
Did that solve the issue for you?

**Comment by Tommmahawk** [comment]
I’m happy to report it did! I’m now waiting for the game to get texture packs and randomizers added. Thank you. Thomas Brickell On Sep 26, 2024, at 10:56 PM, Wiseguy ***@***.***> wrote:﻿
Did that solve the issue for you?
