### ISSUE TITLE
Gyro doesn't work if controller was connected after game was opened

### ISSUE THREAD

**Issue by MarioLuigi0404** [Mr-Wiseguy/Zelda64Recomp#490]
Gyro functionality simply does not work if the gyro controller is connected after the game starts, or if the controller is disconnected and later re-connected.

**To Reproduce**
1. Open game
2. Disconnect any controllers with gyro
3. Reconnect gyro-enabled controller (in my case, a Switch Pro Controller)
4. Attempt to use gyro-compatible items

**Expected behavior**
Gyro aim should work regardless of when the controller was connected, or if it gets disconnected.

**Desktop:**
 - OS: Windows 11
 - Version: 1.1.1
 - CPU: Ryzen 7 5700X3D
 - GPU: NVIDIA GeForce RTX 3060 12GB
 - GPU driver: Nvidia driver 560.94

**Additional context**

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. I can't reproduce this issue, even using the exact same controller as you. Are you using any input wrappers like Steam or BetterJoy?

**Comment by MarioLuigi0404** [comment]
Ah, Steam seems to have been the cause. Thought I had disabled Steam Input but I guess not.

**Comment by Mr-Wiseguy** [comment]
Glad to hear that's resolved, feel free to reopen this if you have any further issues.
