### ISSUE TITLE
[Feature Request] Portable mode

### ISSUE THREAD

**Issue by chrism69** [Mr-Wiseguy/Zelda64Recomp#493]
I'd like to see an option for portable mode, so all saves / settings files etc get stored in the same folder, rather than AppData.

**Comment by Reonu** [comment]
This feature already exists and was implemented with #368 . Closing as completed.

**Comment by chrism69** [comment]
That does not work on Windows. I deleted the Zelda64Recompiled folder in AppData and made a portable.txt, but it just recreates the AppData folder.

**Comment by Mr-Wiseguy** [comment]
It was added after version 1.1.1 released so it's not technically out yet, but it's in any of the development builds. For example, you can download the texture pack development build (from [here](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/447)) and use that even if you aren't using any texture packs.

**Comment by chrism69** [comment]
Ah that works, thanks.
