### ISSUE TITLE
Visual bug on latest Nvidia driver with RTX 2060

### ISSUE THREAD

**Issue by TheTrueShadow** [Mr-Wiseguy/Zelda64Recomp#498]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**
NVIDIA Version 565.90
**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
No it does not occur on original hardware
**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**
Yes
**Describe the bug**
A visual flash on the screen in the setting menu when framerate is set to display 
**To Reproduce**
1. Go to Graphics
2. Set Framerate to display
3. Open settings area 
4. You should see the flashing of black 

**Expected behavior**
No flash on any frame rate
**Screenshots**
Please attach a screenshot of the bug.
![Zelda64Recompiled_0igyvf8CST](https://github.com/user-attachments/assets/57f288ef-89cc-41eb-8c65-b2205b285c98)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.2-dev and any version
 - CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
 - GPU: RTX 2060
 - GPU driver: NVIDIA 565.90

**Additional context**
It looks more severe and happens more then on the gif show because its compressed also it looks bad because of compression too, also it usually takes up more of the screen its usually half and it appears top and bottom

**Comment by DarioSamo** [comment]
For additional context, this seems related to MSAA and seems to go away if you disable it.

As it stands it mostly looks like it's a driver regression and I was unable to spot any errors in the current code. People have also confirmed a driver rollback solves the issue. We'll wait to see what happens on the next driver update and see if it's necessary to add a workaround. For now, simply disable MSAA if you experience the issue.

We've seen the issue on an RTX 3070 as well, but not on a 3080 Ti and a 3090 Ti.

**Comment by TheTrueShadow** [comment]
That's interesting well okay I will try that thanks and I will update you next driver update

**Comment by DarioSamo** [comment]
We've managed to find a workaround and we're pretty certain this is a driver bug for now. The reason behind it seems to be that contents from command lists running in parallel doing Resolve operations can leak to the other, so the internal 240p renderer is affecting the high resolution one and vice-versa.

Doing the Resolve operation manually with a pixel shader solves the problem. This bug does not show up in drivers previous to 565.90 as far as we know.

Sadly this will require some work as we need driver version detection to activate the workaround, but if NVIDIA doesn't get around to fixing the issue, we should have something for it fairly soon.

**Comment by TheTrueShadow** [comment]
Yeah it most likely is a driver bug with Nvidia's D3D12 because other games that run under D3D12 have similar issues on my end also my workaround that seems to work for me is run the game in vulkan it seems to stop these issues all together and at this moment Nvidia hadn't fixed it in the latest driver update they have actually made it worse with their current changes so as I said before Vulkan is my current workaround for this issue. 
(Edit) To mention the game that I said that had an issue too is the cod series and yes I didn't have that issue on any driver previous to 565.90 either.

**Comment by DarioSamo** [comment]
Could you please test out [this build](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/504) and confirm if the issue is gone while you have MSAA enabled?

**Comment by TheTrueShadow** [comment]
> Could you please test out [this build](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/504) and confirm if the issue is gone while you have MSAA enabled?

This workaround seems to have fixed the issues and fixed some other issues too like my mouse not appearing out of game unless the setting menu is opened. 

(Edit) thanks for your hard work
(Sorry for the late reply my github notifications appear to be delayed)
