### ISSUE TITLE
[Feature Request] Translations (aka localization, i18n) into project

### ISSUE THREAD

**Issue by lucmsilva651** [Mr-Wiseguy/Zelda64Recomp#500]
Hi! There is a long time that I don't see this project, and I'm here to ask if you guys (the devs) are planning to do a localization project to this. If yes, I can help with an translation to Brazilian Portuguese. There is a large community of Zelda fans here, but sadly I'm not involved with these.

My intention here is help these communities to find this project and see that something was really made for them, by brazilians, and for brazilians.

Anyways, I like to help with these open-source projects like yours. It is great to see that this project evolved so far!

~ Lucas ;)

**Comment by Mr-Wiseguy** [comment]
Hi, thanks for your interest in helping with this.

I do plan on supporting custom translations in the project, but right now my focus is on modding support for the 1.2 release and Ocarina of Time support for the version after that. The main obstacle for i18n is that I'll need to add a way for the game to render text that supports proper text shaping and right-to-left languages, which in turn will need some new functionality in the renderer that this project uses (RT64). This means that it's probably going to be a long time before I'm able to get custom translation support working unfortunately.

When custom translation support is added I'll be sure to mention it in the release video for that version to let people who are interested in making custom translations know that it's ready.

**Comment by lucmsilva651** [comment]
> The main obstacle for i18n is that I'll need to add a way for the game to render text that supports proper text shaping and right-to-left languages, which in turn will need some new functionality in the renderer that this project uses (RT64).

Yes, I agree that this will need some time and effort to do.

Also, if you do translation support in the future, feel free to mention me and others interested on this. I'll be grateful to help.

Thanks for the reply!
~ Lucas ;)
