### ISSUE TITLE
Game crashes upon opening with a blackscreen

### ISSUE THREAD

**Issue by gdandsm64fan123** [Mr-Wiseguy/Zelda64Recomp#502]
## If you have a crash on startup, please make sure your graphics drivers are up to date before submitting a bug report.

**What is your GPU driver version? Old drivers, particularly on Nvidia, are known to cause crashes on boot on 1.1.0. If you are on Nvidia and the game is crashing on boot, please update to driver version 555.85 or newer before opening an issue.**
Yes, they are updated.
**Have you checked whether this issue is vanilla behavior? In other words, does it occur on original hardware?**
Dawg i didnt even get to play
**Were you playing with intended mechanics, or using glitches? If it's the latter, which glitches?**
I DIDNT GET TO PLAY
**Describe the bug**
It goes blackscreen then crashes

**To Reproduce**
1. Open the executable
2. wait
3. Crash

**Expected behavior**
Extraction of the ROM

**Screenshots**
![Captura de pantalla (8)](https://github.com/user-attachments/assets/d2fef93b-b0c3-4b82-bd6c-1a518c0536c6)
![Captura de pantalla (13)](https://github.com/user-attachments/assets/19bd7198-2e44-47f0-a501-58ce1d554373)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: SO 19045.5011
 - CPU: Intel Celeron N2806
 - GPU: Intel HD Graphics
 - GPU driver: Intel HD Graphics Driver 15.33.19.3540
**Additional context**
idk what to put here

**Comment by Mr-Wiseguy** [comment]
Your CPU's integrated GPU doesn't support D3D12 or vulkan because it's too old (it's from 2013), so recomp won't be able to work on it. Please refer to the system requirements listed in the readme: https://github.com/Zelda64Recomp/Zelda64Recomp?tab=readme-ov-file#system-requirements.

**Comment by gdandsm64fan123** [comment]
alr thanks, kinda sad i cant try this :(

**Comment by gdandsm64fan123** [comment]
are there any alternatives to this for my cpu?
i got the sm64 decomp to work with a 2013 pc so can u tell me?

**Comment by Mr-Wiseguy** [comment]
SM64PC uses a different graphics engine that is much less accurate, which is fine because SM64 doesn't need a very accurate graphics engine to look correct. For recomp we chose to build the graphics engine using more modern technology so that it can be very accurate and also still be fast, that way it will work correctly for many games and not just Majora's Mask. Unfortunately, that means recomp won't be able to run on very old hardware. Sorry about that.
