### ISSUE TITLE
Multiple errors occur when trying to build project

### ISSUE THREAD

**Issue by bMac244** [Mr-Wiseguy/Zelda64Recomp#505]
When trying to build, CMake fails at 29/927 with the following error.

`zsh: command not found: nproc
[29/927] cd /Users/cat1217/Zelda64Reco...ng LD=ld.lld OBJCOPY=llvm-objcopy make
FAILED: CMakeFiles/PatchesBin /Users/cat1217/Zelda64Recomp/patches/patches.elf /Users/cat1217/Zelda64Recomp/build-cmake/CMakeFiles/PatchesBin 
cd /Users/cat1217/Zelda64Recomp/patches && /usr/local/Cellar/cmake/3.30.5/bin/cmake -E env CC=clang LD=ld.lld OBJCOPY=llvm-objcopy make
clang -target mips -mips2 -mabi=32 -O2 -G0 -mno-abicalls -mno-odd-spreg -mno-check-zero-division -fomit-frame-pointer -ffast-math -fno-unsafe-math-optimizations -fno-builtin-memset -Wall -Wextra -Wno-incompatible-library-redeclaration -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-variable -Wno-missing-braces -Wno-unsupported-floating-point-opt -nostdinc -D_LANGUAGE_C -DMIPS -I dummy_headers -I ../lib/mm-decomp/include -I ../lib/mm-decomp/src -I ../lib/mm-decomp/assets -I../lib/rt64/include actor_transform_tagging.c -MMD -MF actor_transform_tagging.d -c -o actor_transform_tagging.o
clang (LLVM option parsing): Unknown command line argument '-mno-check-zero-division'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--memory-check-merge-threshold'?
clang (LLVM option parsing): Unknown command line argument '-mips-ssection-threshold=0'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--mfs-count-threshold=0'?
clang (LLVM option parsing): Unknown command line argument '-mgpopt'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--pgso'?
make: *** [actor_transform_tagging.o] Error 1
[34/927] Building C object rt64/src/co...ir/__/__/__/lib/compress/zstd_lazy.c.o
ninja: build stopped: subcommand failed.`

**Comment by Mr-Wiseguy** [comment]
What environment are you building in?

**Comment by Mr-Wiseguy** [comment]
Judging from your N64Recomp issue you're on MacOS, so you won't be able to build this repo. The only thing available currently for MacOS is this testing PR: https://github.com/Zelda64Recomp/Zelda64Recomp/pull/382. If you have trouble building that branch then you'll have to comment in the PR.
