### ISSUE TITLE
About RetroAchivements Support

### ISSUE THREAD

**Issue by FoxbitDreamtail** [Mr-Wiseguy/Zelda64Recomp#506]
Go to #65

**Comment by LittleCube-hax** [comment]
This has been brought up a couple times already, I think it would be quite feasible from a mod with a native lib.

That being said, I don't believe Master Quest is currently planned to be added, given one of the other issues mentioning it. Someone could introduce MQ through another mod, though.

**Comment by FoxbitDreamtail** [comment]
ok, I didn't know because on a issues search for retroachivements, nothing showed up.

**Comment by LittleCube-hax** [comment]
Ah yeah, no worries 😋 GitHub search is often terrible.

**Comment by FoxbitDreamtail** [comment]
so.. should I close this or keep it open so that search works properly?

**Comment by LittleCube-hax** [comment]
Ah, well I suppose I just wanted to provide more information. Ultimately that's Wiseguy's decision, but the last time someone duped #65 Reonu closed it, so I imagine it's better that this one is closed too to save them the trouble.

The links you've provided are definitely helpful though! Thank you very much for opening this regardless.

**Comment by Ammako** [comment]
> so.. should I close this or keep it open so that search works properly?

It will show up in search even if the issue is closed, as long as the person searching looks through closed issues too.

**Comment by FoxbitDreamtail** [comment]
ok, so I'll close this as a redirect to #65.
