### ISSUE TITLE
[Feature Request] Borderless Windowed and/or triple buffering 

### ISSUE THREAD

**Issue by 5kulld** [Mr-Wiseguy/Zelda64Recomp#512]
Not sure if this is a common issue or not but I experience a decent amount of screen tearing (this is common across all games) and I usually just fix it by setting VSync, Triple buffering or Borderless windowed on. Borderless windowed not only helps with screen tearing but makes it easier to alt-tab to your other open tabs, so I think it'd be a great addition for qol.

**Comment by DarioSamo** [comment]
Borderless windowed mode is already the only fullscreen mode currently supported.

Triple buffering will be enabled by default on the next update.

> Not sure if this is a common issue or not but I experience a decent amount of screen tearing (this is common across all games

If you do, it's probably because it's forced off by your driver. V-Sync is already forced on RT64 and tearing should not be possible.

**Comment by 5kulld** [comment]
Hey it's the same person from the discord, you can close this issue it was like you said a setting I enabled in the driver

**Comment by 5kulld** [comment]
Enhanced sync in AMD settings was messing with it causing screen tearing.
