### ISSUE TITLE
[Feature Request] Please make or enable a portable version

### ISSUE THREAD

**Issue by grimson73** [Mr-Wiseguy/Zelda64Recomp#52]
Hi,

Is it possible to make this app 'portable'?
Settings are now (hardcoded?) stored in:
%USERPROFILE%\AppData\Local\Zelda64Recompiled\

I would like to make the suggestion to make the app portable so that one folder contains all data.
Start app portable when for example when user creates the following in the binary folder:
\Zelda64Recompiled (folder) 
\portable.txt file (file like Dolphin Emulator makes itself 'portable')

Thank you!

**Comment by bryc** [comment]
This issue was already reported today.

**Comment by grimson73** [comment]
> This issue was already reported today.

Ah I see, sorry did not search carefully for earlier 'issues' on this matter. Thanks!
