### ISSUE TITLE
Menu freezes unless I launch it from terminal

### ISSUE THREAD

**Issue by AQDuck97** [Mr-Wiseguy/Zelda64Recomp#54]
**Describe the bug**
When I try to launch the game from a file manager, the game just freezes immediately and I have to do `killall Zelda64Recompiled -9` to properly kill it (just `killall Zelda64Recompiled` does not work, even with sudo).
It also _occasionally_ freezes when I launch it from terminal with no error messages (gets to `Loaded font face 'PromptFont' [regular] from 'assets/promptfont/promptfont.ttf'.` then hangs, but it also gets to that when it successfully launches)
Sometimes it freezes on a black screen, sometimes on the menu (before the backgorund fades in)

**To Reproduce**
1. Make binary executable
2. Run it from a file manager or terminal (higher chance of working from terminal)

**Expected behavior**
The game should either close if it crashed (would be nice with error message in terminal) or run properly

**Screenshots**
Kept launching it from terminal until it froze, I couldn't interact with any of the buttons and the background image never loaded.
![bild](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/102743075/1446dd88-0717-4019-baa5-19824941fefc)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Linux Zen 6.8.9
 - CPU: Ryzen 7 5800X
 - GPU: Radeon RX 580 / Nvidia RTX 3080

**Additional context**
I also have an Nvidia RTX 3080 but it's not the primary GPU and should not be used by the game. Tried launching it with `prime-run` as well (should use the 3080) with similar results (sometimes worked, sometimes didn't)
Also might be worth mentioning that I'm on Wayland.

**Comment by Mr-Wiseguy** [comment]
Do you have any luck with the latest release of this project? It's odd that you mentioned having to make the binary executable, since the tar.gz in the GitHub releases already has it marked with that permission. Additionally, you can try the AppImage to see if that resolves this issue.

**Comment by AQDuck97** [comment]
> Do you have any luck with the latest release of this project? It's odd that you mentioned having to make the binary executable, since the tar.gz in the GitHub releases already has it marked with that permission. Additionally, you can try the AppImage to see if that resolves this issue.

No, same result with v1.1.1's appimage
I only really play on Steam Deck though where I haven't had any such issues, so definitely something on my system but not sure what as it sometimes load and sometimes doesn't.

**Comment by dcvz** [comment]
Bit of a long shot but could you give this app image a try?

https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9445507391

**Comment by AQDuck97** [comment]
> Bit of a long shot but could you give this app image a try?
> 
> https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9445507391

Release version freezes like before, but running the debug version in terminal caused an immediate crash (not hang) and this output:
```
Loaded font face 'PromptFont' [regular] from 'assets/promptfont/promptfont.ttf'.
Zelda64Recompiled: /__w/Zelda64Recomp/Zelda64Recomp/lib/rt64/src/vulkan/rt64_vulkan.cpp:3165: virtual void RT64::VulkanCommandQueue::executeCommandLists(const RenderCommandList **, uint32_t, RenderCommandFence *): Assertion `swapChain->acquireNextTextureSemaphoreSignaled' failed.
/tmp/.mount_Zelda6CRQcqM/AppRun: line 20: 722941 Aborted                 (core dumped) ./Zelda64Recompiled
```

**Comment by Xreel9** [comment]
i have the same issue using cachyos and endeavour i really don't know what's causing it even the windows version crash so idk what's going on. hopefully it gets resolve soon

**Comment by Mr-Wiseguy** [comment]
@AQDuck97 Does this build fix the issue for you? It resolves a Wayland freeze on startup that sounds similar to the issue you described: https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9751410884

**Comment by AQDuck97** [comment]
> @AQDuck97 Does this build fix the issue for you? It resolves a Wayland freeze on startup that sounds similar to the issue you described: https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9751410884

Seems like it! Launched it 20-ish times with no issues.

**Comment by Mr-Wiseguy** [comment]
Great to hear! Closing this issue now, but feel free to reply here if it comes up again to reopen the issue.
