### ISSUE TITLE
Could you do this for Paper Mario N64?

### ISSUE THREAD

**Issue by zqpvr** [Mr-Wiseguy/Zelda64Recomp#58]

**Comment by Ammako** [comment]
N64Recomp should support every game, once it's ready. This particular repo is only going to be Zelda 64, other games can be compiled separately.

**Comment by OG0mez** [comment]
This project is only for Zelda (MM/ OOT), but you can use the Recomp on other games just have to tweak it

**Comment by zqpvr** [comment]
So I compile https://github.com/pmret/papermario which is easy enough, get the elf and somehow use that from my understanding?

**Comment by Ammako** [comment]
No, N64Recomp is a separate program by Mr Wiseguy which takes a n64 rom file and returns C code for it, which you can build for PC. It's not available yet.

The paper mario decompilation is a separate thing. The C code from it is for building a N64 rom, it's not a PC port.

**Comment by zqpvr** [comment]
oh

**Comment by Alto1772** [comment]
Creating the PM recomp port isn't that sloppily easy, and still require some of deep knowledge of the game anyhow. Building the rom from the decomp and generating it with N64Recomp isn't getting you a PC port like that easily, you still need some other requirements like graphics, audio, display, and etc.

**Comment by Reonu** [comment]
Thank for your interest, however, this is outside the scope of this project, so I'm closing the issue.

If you have the required skills, please feel free to use the [N64Recomp tool](https://github.com/Mr-Wiseguy/N64Recomp) to make your own recomps though!
