### ISSUE TITLE
8BitDo Ultimate Bluetooth Controller Doesn't Work with USB dongle. 

### ISSUE THREAD

**Issue by Applepi** [Mr-Wiseguy/Zelda64Recomp#60]
When in USB 2.4Ghz mode the controller isn't detected in any way shape or form. Bluetooth works but due to interference it's unusable.

**To Reproduce**
1. Use 8BitDo Ultimate Bluetooth Controller  in 2.4ghz USB mode
2. Doesn't work

**Expected behavior**
It should work it's a USB game pad.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.0.0 I think
 - CPU: Ryzen 7000 Mobile
 - GPU:  Ryzen 7000 Mobile

**Additional context**
I had this same problem with fallout New Vegas where it would show up in windows game pad and when I get in game nothing. I previously fixed this using steam input but with this not being on steam I don't know how to add it as a non-steam game to add support.

I tried installing the driver software and putting it in both switch and xbox mode but that didn't make a difference.

I uninstalled the steam input extended driver support that also didn't make a difference.

**Comment by justinbeaty** [comment]
I have the same controller and it worked perfectly using 2.4GHz mode. I'm on a pretty fresh Windows 10 install though.

**Comment by Applepi** [comment]
Looks like I was able to get it to work in 2.4ghz mode by connecting the
controller via USB and factory defaulting the controller from the 8bitdo
software.

**Comment by Mr-Wiseguy** [comment]
This is the exact controller I used for testing most of the time during development (in 2.4GHz mode as well) so I know it works. It sounds like you got it working after that factory reset, so I'll close this for now.
