### ISSUE TITLE
Interpolation of motions that shouldn't be interpolated.

### ISSUE THREAD

**Issue by elexor** [Mr-Wiseguy/Zelda64Recomp#61]
Things like scene cuts in the game need to be marked somehow to avoid interpolating over them as they seem to cause a warping effect.
Also some character instant pose changes warp weridly.

**Comment by niklakis** [comment]
I have recorded some weird things I noticed with animations and timings in general but just to be sure I went and checked some footage on youtube and a lot of the problems are there on the original version as well, just exaggerated a bit by the higher framerate. If I have time I will hook up my n64 to check my PAL version as well.

These were recorded with a 30fps cap as it was the closest I could stand to the original framerate. ver 1.1.0


https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5071672/adf55575-9236-4a46-a4ee-660fc2d29193

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5071672/b8de126f-d295-4b71-af15-d07e45e375b2

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5071672/222eb61c-3a9d-410d-9bc0-efc0ba26f3a8

**Comment by Mr-Wiseguy** [comment]
As mentioned, these issues are generally present in the original game and are just more noticeable because of the higher framerate. Closing due to this, but feel free to reopen if you have any specific examples that definitely don't occur in the original version.
