### ISSUE TITLE
cremia cutscene link model bugged 

### ISSUE THREAD

**Issue by FSR-1** [Mr-Wiseguy/Zelda64Recomp#76]
![Screenshot (301)](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/169501359/5a043e77-f6f5-456a-ba3a-d14965b38139)

**Comment by Reonu** [comment]
Closing it in favor of #201 which has more info.

**Comment by FSR-1** [comment]
> Closing it in favour of #201 which has more info.

thx i didn't know why this happened glad that post could better explain it
