### ISSUE TITLE
[Feature Request] Invert Y Axis Camera

### ISSUE THREAD

**Issue by Dumbledork01** [Mr-Wiseguy/Zelda64Recomp#77]
Could you add an option for inverting the camera Y axis for controller users? I looked through the code and figured it shouldn't be too difficult to replace the Y axis user input to a negative value if the user chooses this option, I just don't know your architecture well enough to make that PR and couldn't get it to compile on my windows machine...sorry :)

**Comment by Reonu** [comment]
This is now being tracked in #206 . PRs welcome.
