### ISSUE TITLE
[Feature Request] Song Of Double Time Hour Increments

### ISSUE THREAD

**Issue by Dumbledork01** [Mr-Wiseguy/Zelda64Recomp#78]
Similar to the 3DS port, a way to choose the actual hour you skip to would be nice as well. If that's too hard, another option would be a cheat in the GUI that could allow you to choose which hour to skip to. Either would be super nice for those of us who don't love the 6 hour increments.

**Comment by Eblo** [comment]
> If that's too hard, another option would be a cheat in the GUI that could allow you to choose which hour to skip to.

This exists. Open your `general.json` file (on Windows this is in `%LOCALAPPDATA%/Zelda64Recompiled`) and set the `debug_mode`  value to `true`. When you next boot the application, you should have this menu under Settings:

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/7004497/1a21205b-87f3-40e9-861e-5fbff2623d6b)

**Comment by Dumbledork01** [comment]
@Eblo Dang, I didn't realize there was a debug mode you could activate! Thanks for the reply. I'll leave the request in case the creator wants to implement a feature to integrate it into gameplay, but honestly, if he creates a build-guide I'll probably try to create a PR myself for the feature because it sounds fun to implement haha.

**Comment by Mr-Wiseguy** [comment]
Closing as this would be out of the scope of the base project. I do think that it would be a cool mod once modding support is released.
