### ISSUE TITLE
Auto save bug

### ISSUE THREAD

**Issue by TheTrueShadow** [Mr-Wiseguy/Zelda64Recomp#80]
**Describe the bug**
Not sure if this is a bug or not but the built-in autosave feature doesn't work on any glitched days like 4th day or 0th day

**To Reproduce**
1. Do the 4th day glitch or 0 the day
2. Do anything that would auto save

**Expected behavior**
Auto save should save regardless of day

**Screenshots**
Not applicable 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.0.0
 - CPU:  Intel Core I5 9600K
 - GPU:  NVIDIA RTX 2060 6gb

**Additional context**
The game does not run the autosave feature on the 0th and fourth day which it does normally occur on the normal 3-day cycle so I think either that it's based off a clock so that means it would be broken or it's based off some other in-game timer that doesn't exist on these days.

**Comment by JohnDarc95** [comment]
It looks like there's logic to disable auto-saving if its within the last 3 hours of the 3rd day or later

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/37269096/521facaa-bf5f-495e-acf3-3fc497c08fe6)

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/37269096/7fd9dd71-c201-4b3a-871a-7f3a976b66ff)

Still not sure about Day 0 though. Internally it may be stored as some junk value so it might also register as >= 4?

**Comment by TheTrueShadow** [comment]
I don't think that's the case in a way because KZ of you know what that is it  shows value as day 0 but that could be KZ doing things its own way and 4 day I know it's a separate value and that makes sense that it stops after 3rd day to prevent soft locks

**Comment by JohnDarc95** [comment]
Yeah you're probably right, it would be interesting to see why day 0 stops it. Maybe day 0 causes one of the other conditions in the second screenshot to become false other than 'reached final 3 hours'

At the very least if you fork the repo and make a build removing the "if (day >= 4) || ", I'd love to heard if fixing it for day 4 would actually be that simple

**Comment by TheTrueShadow** [comment]
I will definitely try and I'll let you know here

**Comment by Deozaan** [comment]
When you start a new game normally (no glitches), the game doesn't start auto-saving until you walk out of the clock tower for the first time, which is when it says Dawn of the First Day and the clock starts ticking. So there's probably some logic in there somewhere that prevents auto-saving before the clock starts ticking.

> ![image](https://private-user-images.githubusercontent.com/37269096/329911005-7fd9dd71-c201-4b3a-871a-7f3a976b66ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTQwMTgsIm5iZiI6MTcxNTgxMzcxOCwicGF0aCI6Ii8zNzI2OTA5Ni8zMjk5MTEwMDUtN2ZkOWRkNzEtYzIwMS00YjNhLTg3MWEtN2YzYTk3NmI2NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDIyNTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YjkzMWE0Y2FlY2RkOTk0Y2UwOTI5NjZiZTZhNjc2OTk5ZjM2NDdmZjliMjllYzc3YzBjMDhjZTEwMmQ4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aqIV6Nfu-H7P3hN_N85i1tFnTWfcA15C4zLsSKohgjk)

My guess based on this screenshot is that it is either `Environtment_IsTimeStopped()` or `gSaveContext.save.cutsceneIndex < 0xFFF0`.

**Comment by Reonu** [comment]
Thanks for the issue report.

This is all intentional. The game checks that ALL these conditions are met before autosaving:
```
        // Check the following conditions:
        // * The UI is in a normal state.
        // * Time is passing.
        // * No message is on screen.
        // * The game is not paused.
        // * No cutscene is running.
        // * The game is not in cutscene mode.
        // * The clock has not reached the final 3 hours.
        // * The player is allowed to pause.
```
This prevents a variety of nasty bugs that could result from the game autosaving at the wrong time and there are no plans to change this behavior.
