### ISSUE TITLE
Abnormal ReShade Shader Load

### ISSUE THREAD

**Issue by BlueSkyDefender** [Mr-Wiseguy/Zelda64Recomp#82]
Issue:
Low Frame rate from almost any shader when ReShade is used.

Reproduce:
Install ReShade and load a basic shader Frame Rate drops at an abnormal rate.
And is made way worst when loading a more complex Shader.

Expected behavior:
Shader should have comparable performance to other DX12 api's/game/emulators
 
**Screenshots**
Shader On Frame Rate sub 60fps 
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16185319/8da443df-ce3f-40a0-bf30-1108b0b44fd6)
Shader OFF Game close enough to 120fps
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16185319/69cacb35-1b1a-4f1d-bfc2-fd833e8ed7ee)

The drop should be somewhere around  80fps  not sub 60 if the shader has a load around 4ms. This issue may be tied to the overlay issue.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Version	10.0.22631 Build 22631
 - CPU: AMD Ryzen 7600
 - GPU:  NVIDIA GeForce RTX 4060ti

Additional context:
This issue may be tied to one of your known issue. listed as:
```Overlays such as MSI Afterburner and other software such as Wallpaper Engine can cause performance issues with this project that prevent the game from rendering correctly. Disabling such software is recommended.```

**Comment by Reonu** [comment]
Thank you for your issue.

However, this is not a Zelda 64 Recompiled issue. It's a ReShade issue, so please report it to them.

As for the overlay stuff (MSI Afterburner etc) that's not a Zelda 64 Recompiled issue either. MSI Afterburner seems to bottleneck RT64's present queue and prevents Recomp from rendering frames as fast as it can.
