### ISSUE TITLE
[Feature Request] Free Look

### ISSUE THREAD

**Issue by Koops128** [Mr-Wiseguy/Zelda64Recomp#86]
Really impressed with this whole thing. The only thing I'm wondering about is if there's any plans to support Free Look (the ability to move the camera with the right stick).

**Comment by lolcatplays** [comment]
https://github.com/Mr-Wiseguy/Zelda64Recomp#planned-features

**Comment by YO-SC** [comment]
its out now :D

**Comment by Reonu** [comment]
Added by #264 ;)
