### ISSUE TITLE
Mayflash Magic NIS Wireless Bluetooth Controller Issue

### ISSUE THREAD

**Issue by TheSkipper1995** [Mr-Wiseguy/Zelda64Recomp#87]
**Describe the bug**
My computer has no native bluetooth device, so I use this: [Mayflash USB](https://www.amazon.com/MAYFLASH-Bluetooth-Controller-Raspberry-Compatible/dp/B079B5KHWQ) in order to use my Nintendo Switch Pro Controller. It does not work unless I use the "Xinput" mode.

**To Reproduce**
Just use Mayflash Magic NIS Bluetooth in "Switch" or "Switch Pro" mode.

**Expected behavior**
I would expect it to work with "Switch" or "Switch Pro" mode.

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/70816633/65e5ff68-c9d1-4652-a659-5be0264cd1d0)

**Desktop:**
 - OS: Windows 10
 - Version: 2024-04 Cumulative Update Preview for Windows 10 Version 22H2 for x64-based Systems (KB5036979)
 - CPU: AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
 - GPU: NVIDIA GeForce RTX 3070 (EVGA)

**Comment by TheSkipper1995** [comment]
Bumping this in case it was missed because I'd really like to use gyro.

The readme says "Gamepad mappers such as BetterJoy or DS4Windows may intercept gyro data and prevent the game from receiving it. Most controllers are natively supported, so turning gamepad mappers off is recommended if you want to use gyro."
How exactly is the game intended to natively support a Switch controller? Are you supposed to plug it into a USB port via the charging cable?

**Comment by Reonu** [comment]
> Bumping this in case it was missed because I'd really like to use gyro.
> 
> The readme says "Gamepad mappers such as BetterJoy or DS4Windows may intercept gyro data and prevent the game from receiving it. Most controllers are natively supported, so turning gamepad mappers off is recommended if you want to use gyro."
> How exactly is the game intended to natively support a Switch controller? Are you supposed to plug it into a USB port via the charging cable?

Yes. Or connect it via Bluetooth. What's confusing about that?

**Comment by TheSkipper1995** [comment]
> Yes. Or connect it via Bluetooth. What's confusing about that?

I'm confused because the Magic-NS dongle that I'm using is supposed to be a bluetooth adapter but the game won't detect my Switch Pro controller with it unless it's set to Xinput mode; which I'm assuming is why it isn't allowing gyro.

I've tried just plugging it in via the charging cable, but I don't know how to make it "turn on" exactly. Any button press just makes the controller try to sync to something that doesn't exist.

And my computer has no internal bluetooth and so I must use some kind of external adapter if I want bluetooth to be an option.

So I need either:

- a.) A way to make the game recognize it via plugging it in with the charging cable. Is there some kind of step I'm missing to prevent the Switch Pro controller from being "off" and trying to sync when plugged into my PC?
- b.) A suggestion for an external bluetooth adapter that is known for certain to work with the Switch Pro controller and this game. So I can just buy it.

**Comment by Mr-Wiseguy** [comment]
There's nothing to do to make it recognize the pro controller. You just plug it into the PC with a USB cable and recomp will detect it. There are articles online on how to connect a pro controller to PC (and also covers how to do it with bluetooth): https://www.pcmag.com/how-to/how-to-use-a-nintendo-switch-pro-controller-on-a-pc. Note that you don't need to follow the Steam setup part of that article.

If you have problems with that process then it's not related to this project, as many people including myself have used their pro controllers already without issues.

**Comment by TheSkipper1995** [comment]
Both that article and similar ones I've tried looking at seem to be outdated. There is no "General Controller Settings" that they're describing anymore. So I guess I'm gonna have to take this to Steam Support. Sorry to bother you.

**Comment by Mr-Wiseguy** [comment]
You don't need Steam for recomp to recognize a Switch Pro controller, and in fact Steam can actively cause problems with other programs if Steam Input is enabled while a Steam game isn't running. I would try again after closing Steam.

**Comment by TheSkipper1995** [comment]
Ok apparently disabling steam input and also closing steam seemed to work. Cool. Thanks for indulging me and sorry for being obnoxious :)

**Comment by Mr-Wiseguy** [comment]
Glad to hear it's working now, enjoy playing!
