### ISSUE TITLE
Where are saves stored?

### ISSUE THREAD

**Issue by jvne2134** [Mr-Wiseguy/Zelda64Recomp#88]
I've been looking around and can't seem to find it

**Comment by jvne2134** [comment]
Took a look at the source code, fyi for future people ig

The save path is on \user\AppData\Local\Zelda64Recompiled\

**Comment by eclemens** [comment]
This should be documented

**Comment by jvne2134** [comment]
yeah it defo should be mentioned somewhere lol

**Comment by Reonu** [comment]
> yeah it defo should be mentioned somewhere lol

It's in the readme.

**Comment by jvne2134** [comment]
wasnt there before, i made sure to check  (or im just fucking retarded)

**Comment by Reonu** [comment]
> wasnt there before, i made sure to check

I added it 2 weeks ago:
https://github.com/Zelda64Recomp/Zelda64Recomp/commit/4873460b8887962d20e1fb4f8c9cb010a4c4f61d

**Comment by jvne2134** [comment]
oh yeah that makes sense hahaha

thank you bro :3
