### ISSUE TITLE
Can't change roms once one is selected, therefore can't change languages.

### ISSUE THREAD

**Issue by GioVio123** [Mr-Wiseguy/Zelda64Recomp#90]
Ran Zelda64Recomp with a US rom, tried to do so again WITH an European one, tried to find ways to change from the UI, tried to erase files, download them again, restart my pc.
So far, I can't get it to play for another region so that I can get the italian or spanish translation.

**Comment by JimBimBum** [comment]
yeah it uses usa roms only

**Comment by GioVio123** [comment]
Would the code need to change in order to run the european versions? I am gonna attempt to bruteforce it meanwhile.

**Comment by GioVio123** [comment]
Tried it, runs like shit.

**Comment by lolcatplays** [comment]
local appdata is where the files are stored.

**Comment by Mr-Wiseguy** [comment]
You can't change ROMs because this project only supports one version. This isn't an emulator, so it can't load an arbitrary ROM, as different versions have different code, assets, and ROM layouts. Multilang support is a planned feature to be implemented in the base project in the future.

**Comment by lolcatplays** [comment]
Would it work with asset replaced roms? like a model swap. Like have you tried using patcher 64 and then disabling rom checks?

**Comment by Deses** [comment]
They should add support for other regions when other high priority task have been completed,

**Comment by GioVio123** [comment]
I am opening the issue thread for any updates that might surface, despite the length of time it took to make this desicion

**Comment by Mr-Wiseguy** [comment]
As I explained earlier, this is not a bug or oversight. Recomp can't change ROMs because it's not an emulator, meaning it only supports one specific ROM. Translation support will be provided via a different mechanism in the future. Please do not reopen this issue.
