### ISSUE TITLE
New to git, please help

### ISSUE THREAD

**Issue by Chairmanofgaming** [Mr-Wiseguy/Zelda64Recomp#92]
Hello, I am sorry to post this here.
I am new to the git platform and don't understand how to use it well.
Could someone let me know the steps to get this program to work?
I already have my image of the game, and I cloned the repo to my desktop an extracted it, but I do not know what to do from there.
I am using Manjaro linux (Arch, same as steam deck)
I assume I should see an executable for this game, but I dont see it in the folder. 
Am I doing something wrong?
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/169578932/20dd8c55-c974-42a4-90b7-8c8c5d6e39ec)
Any help would be greatly appreciate, but would not be upset if asked to delete or if post got deleted by mods.

**Comment by lolcatplays** [comment]
When in doubt read the readme description always.. 
https://github.com/Mr-Wiseguy/Zelda64Recomp?tab=readme-ov-file#building

**Comment by Fondant** [comment]
also before that have you tried the [release](https://github.com/Mr-Wiseguy/Zelda64Recomp/releases) to see if you can just run the compiled version

**Comment by Chairmanofgaming** [comment]
> also before that have you tried the [release](https://github.com/Mr-Wiseguy/Zelda64Recomp/releases) to see if you can just run the compiled version

OMG that was so much easier, how did you get there from https://github.com/Mr-Wiseguy/Zelda64Recomp?

**Comment by LoadingZone98** [comment]
> how did you get there from https://github.com/Mr-Wiseguy/Zelda64Recomp?

![releases](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/160391734/51c0c32a-3a6d-4b7d-a2a8-d0c8f58f3c14)
Unfortunately the link you are supposed to click is black, making it blend in with plain text instead of being blue and underlined like normal hyperlinks.

**Comment by AQDuck97** [comment]
@Chairmanofgaming You may want to close this issue as solved (button that says "close with comment")

**Comment by Reonu** [comment]
Closing as the issue has been solved.
