### ISSUE TITLE
Not really an Issue. More of a suggestion

### ISSUE THREAD

**Issue by NotAestheticL** [Mr-Wiseguy/Zelda64Recomp#93]
I was wondering if it was possible to add a connection to Retroachievements.org to the whole project so you can earn Achievements while playing the game.

Sorry if this is the wrong place for this question but i dont know how to manouver through github and i dont know where to suggest stuff like this

**Comment by briaguya0** [comment]
dupe of https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/65

**Comment by NotAestheticL** [comment]
> dupe of #65

sorry didnt see it

**Comment by Rucadi** [comment]
Please, close the issue since this is a dupe @NotAestheticL
